import { useEffect, useRef, useState } from "react";
import { Autocomplete } from "../../components/ui/Autocomplete";
import { Modal } from "../../components/ui/Modal";
import { Sanidad_mensajeError } from "../../hooks/useSanidad";
import * as S from "../../services/sanidad.service";
import type { AlmacenSanidad, CatalogoSanidad, DestinoAnimalSanidad, DestinoLoteSanidad, ExistenciaSanidad, LoteFuenteSanidad, ProductoSanidad } from "../../types/sanidad.types";
import { Fecha_datetimeLocalAContratoGuatemala } from "../../utils/fecha";

type Alcance = "INDIVIDUAL" | "POR_ANIMAL" | "TOTAL_LOTE";
interface FuenteFormulario { IntClave: number; ObjAlmacen: AlmacenSanidad | null; ObjLote: LoteFuenteSanidad | null; StrCantidad: string }
interface DetalleFormulario { IntClave: number; ObjProducto: ProductoSanidad | null; StrDosis: string; IntUnidadId: number | null; IntViaId: number | null; StrAlcance: Alcance; ArrExistencias: ExistenciaSanidad[]; ArrFuentes: FuenteFormulario[] }
const Sanidad_nuevaFuente = (IntClave: number): FuenteFormulario => ({ IntClave, ObjAlmacen: null, ObjLote: null, StrCantidad: "" });
const Sanidad_nuevoDetalle = (IntClave: number, IntFuente: number): DetalleFormulario => ({ IntClave, ObjProducto: null, StrDosis: "", IntUnidadId: null, IntViaId: null, StrAlcance: "INDIVIDUAL", ArrExistencias: [], ArrFuentes: [Sanidad_nuevaFuente(IntFuente)] });
const Sanidad_idCatalogo = (Obj: CatalogoSanidad) => Obj.tipoAplicacionId ?? Obj.viaAdministracionId ?? Obj.unidadDosisId ?? 0;
const ObjDecimalPositivo = /^(?!0+(?:\.0{1,6})?$)\d{1,18}(?:\.\d{1,6})?$/;

export function PaginaRegistrarSanidad() {
  const IntSiguiente = useRef(1);
  const [StrDestino, establecerDestino] = useState<"ANIMAL" | "LOTE">("ANIMAL");
  const [ObjAnimal, establecerAnimal] = useState<DestinoAnimalSanidad | null>(null);
  const [ObjLote, establecerLote] = useState<DestinoLoteSanidad | null>(null);
  const [StrFecha, establecerFecha] = useState(""); const [StrProxima, establecerProxima] = useState("");
  const [IntTipoId, establecerTipoId] = useState<number | null>(null);
  const [StrMotivo, establecerMotivo] = useState(""); const [StrDiagnostico, establecerDiagnostico] = useState(""); const [StrObservaciones, establecerObservaciones] = useState("");
  const [ArrTipos, establecerTipos] = useState<CatalogoSanidad[]>([]); const [ArrVias, establecerVias] = useState<CatalogoSanidad[]>([]); const [ArrUnidades, establecerUnidades] = useState<CatalogoSanidad[]>([]);
  const [ArrProductos, establecerProductos] = useState<ProductoSanidad[]>([]); const [ArrAlmacenes, establecerAlmacenes] = useState<AlmacenSanidad[]>([]); const [ArrDetalles, establecerDetalles] = useState<DetalleFormulario[]>([]);
  const [BoolConfirmar, establecerConfirmar] = useState(false); const [BoolProcesando, establecerProcesando] = useState(false); const [StrError, establecerError] = useState<string | null>(null); const [StrExito, establecerExito] = useState<string | null>(null);
  useEffect(() => { void Promise.all([S.Sanidad_catalogo("tipos-aplicacion", true), S.Sanidad_catalogo("vias-administracion", true), S.Sanidad_catalogo("unidades-dosis", true), S.Sanidad_productos(true), S.Sanidad_almacenes()]).then(([ObjTipos, ObjVias, ObjUnidades, ObjProductos, ArrAlmacenesRespuesta]) => { establecerTipos(ObjTipos.datos); establecerVias(ObjVias.datos); establecerUnidades(ObjUnidades.datos); establecerProductos(ObjProductos.datos.filter(Obj => Obj.activo && Obj.habilitacionSanidad?.activo)); establecerAlmacenes(ArrAlmacenesRespuesta); }).catch(ObjError => establecerError(Sanidad_mensajeError(ObjError))); }, []);
  function Sanidad_actualizarDetalle(IntClave: number, ObjCambio: Partial<DetalleFormulario>) { establecerDetalles(Arr => Arr.map(Obj => Obj.IntClave === IntClave ? { ...Obj, ...ObjCambio } : Obj)); }
  function Sanidad_actualizarFuente(IntDetalle: number, IntFuente: number, ObjCambio: Partial<FuenteFormulario>) { establecerDetalles(Arr => Arr.map(Obj => Obj.IntClave !== IntDetalle ? Obj : { ...Obj, ArrFuentes: Obj.ArrFuentes.map(ObjFuente => ObjFuente.IntClave === IntFuente ? { ...ObjFuente, ...ObjCambio } : ObjFuente) })); }
  async function Sanidad_seleccionarProducto(IntClave: number, ObjProducto: ProductoSanidad | null) { Sanidad_actualizarDetalle(IntClave, { ObjProducto, ArrExistencias: ObjProducto ? await S.Sanidad_existencias(ObjProducto.productoId) : [], ArrFuentes: [Sanidad_nuevaFuente(IntSiguiente.current++)] }); }
  function Sanidad_validar() {
    if (!(StrDestino === "ANIMAL" ? ObjAnimal : ObjLote)) return "Seleccione un destino válido."; if (!StrFecha) return "Indique fecha y hora efectiva."; if (!IntTipoId) return "Seleccione el tipo de aplicación."; if (!StrMotivo.trim()) return "El motivo o indicación es obligatorio.";
    const ObjProductos = new Set<number>();
    for (const ObjDetalle of ArrDetalles) {
      if (!ObjDetalle.ObjProducto || !ObjDetalle.IntUnidadId || !ObjDetalle.IntViaId) return "Complete producto, unidad clínica y vía."; if (ObjProductos.has(ObjDetalle.ObjProducto.productoId)) return "Cada producto debe aparecer en un único detalle clínico."; ObjProductos.add(ObjDetalle.ObjProducto.productoId);
      if (!ObjDecimalPositivo.test(ObjDetalle.StrDosis)) return "La dosis debe ser un decimal positivo."; if (StrDestino === "ANIMAL" && ObjDetalle.StrAlcance !== "INDIVIDUAL") return "El destino animal requiere alcance Individual."; if (StrDestino === "LOTE" && ObjDetalle.StrAlcance === "INDIVIDUAL") return "Seleccione el alcance del lote.";
      const ObjFuentes = new Set<string>(); for (const ObjFuente of ObjDetalle.ArrFuentes) { if (!ObjFuente.ObjAlmacen || !ObjDecimalPositivo.test(ObjFuente.StrCantidad)) return "Complete almacén y cantidad física en cada fuente."; if (!ObjFuente.ObjLote) return "Seleccione el lote de Inventario."; const StrClave = `${ObjFuente.ObjAlmacen.inventarioId}:${ObjFuente.ObjLote.loteInventarioId}`; if (ObjFuentes.has(StrClave)) return "No repita exactamente la misma fuente física."; ObjFuentes.add(StrClave); }
    } return null;
  }
  async function Sanidad_confirmarRegistro() { const StrValidacion = Sanidad_validar(); if (StrValidacion) { establecerError(StrValidacion); return; } establecerProcesando(true); try { await S.Sanidad_registrar({ tipoAplicacionId: IntTipoId!, fechaAplicacion: Fecha_datetimeLocalAContratoGuatemala(StrFecha), proximaAplicacion: StrProxima || null, destino: StrDestino === "ANIMAL" ? { tipo: "ANIMAL", animalId: ObjAnimal!.animalId } : { tipo: "LOTE", loteProduccionId: ObjLote!.loteProduccionId }, motivo: StrMotivo.trim(), diagnostico: StrDiagnostico.trim() || null, observaciones: StrObservaciones.trim() || null, detalles: ArrDetalles.map(Obj => ({ productoId: Obj.ObjProducto!.productoId, dosisClinica: Obj.StrDosis, unidadDosisId: Obj.IntUnidadId!, viaAdministracionId: Obj.IntViaId!, alcanceDosis: Obj.StrAlcance, fuentes: Obj.ArrFuentes.map(ObjFuente => ({ inventarioId: ObjFuente.ObjAlmacen!.inventarioId, loteInventarioId: ObjFuente.ObjLote!.loteInventarioId, cantidad: ObjFuente.StrCantidad })) })) }); establecerExito("Aplicación sanitaria registrada correctamente."); establecerConfirmar(false); establecerDetalles([]); } catch (ObjError) { establecerError(Sanidad_mensajeError(ObjError)); establecerConfirmar(false); } finally { establecerProcesando(false); } }
  return <div className="alimentacion-contenido"><header className="alimentacion-seccion-encabezado"><div><h2>Registrar aplicación sanitaria</h2><p>Hecho clínico con consumo opcional de productos de Inventario.</p></div></header>{StrError && <p role="alert" className="mensaje-error">{StrError}</p>}{StrExito && <p role="status" className="mensaje-exito">{StrExito}</p>}
    <section className="alimentacion-formulario"><fieldset><legend>Destino</legend><div className="alimentacion-selector-destino"><label><input type="radio" checked={StrDestino === "ANIMAL"} onChange={() => { establecerDestino("ANIMAL"); establecerLote(null); establecerDetalles(Arr => Arr.map(Obj => ({ ...Obj, StrAlcance: "INDIVIDUAL" }))); }} /> Animal</label><label><input type="radio" checked={StrDestino === "LOTE"} onChange={() => { establecerDestino("LOTE"); establecerAnimal(null); establecerDetalles(Arr => Arr.map(Obj => ({ ...Obj, StrAlcance: "POR_ANIMAL" }))); }} /> Lote</label></div>{StrDestino === "ANIMAL" ? <Autocomplete StrEtiqueta="Animal" StrPlaceholder="Buscar por código o identificación..." ObjSeleccion={ObjAnimal} Autocomplete_buscar={S.Sanidad_animales} Autocomplete_clave={Obj => Obj.animalId} Autocomplete_etiqueta={Obj => `${Obj.identificacion} — ${Obj.tipoAnimal.nombre} — ${Obj.asignaciones[0]?.lote.codigo ?? "—"}`} Autocomplete_seleccionar={establecerAnimal} /> : <Autocomplete StrEtiqueta="Lote de Producción" StrPlaceholder="Buscar por código o nombre..." ObjSeleccion={ObjLote} Autocomplete_buscar={S.Sanidad_lotesProduccion} Autocomplete_clave={Obj => Obj.loteProduccionId} Autocomplete_etiqueta={Obj => `${Obj.codigo} — ${Obj.nombre} — ${Obj.tipoAnimal.nombre}`} Autocomplete_seleccionar={establecerLote} />}</fieldset>
      <div className="sanidad-datos-generales"><label>Fecha y hora efectiva<input type="datetime-local" required value={StrFecha} onChange={ObjEvento => establecerFecha(ObjEvento.target.value)} /></label><label>Tipo de aplicación<select required value={IntTipoId ?? ""} onChange={ObjEvento => establecerTipoId(ObjEvento.target.value ? Number(ObjEvento.target.value) : null)}><option value="">Seleccione</option>{ArrTipos.map(Obj => <option key={Sanidad_idCatalogo(Obj)} value={Sanidad_idCatalogo(Obj)}>{Obj.nombre}</option>)}</select></label><label>Motivo / indicación<input required value={StrMotivo} onChange={ObjEvento => establecerMotivo(ObjEvento.target.value)} /></label><label>Próxima aplicación (opcional)<input type="date" value={StrProxima} onChange={ObjEvento => establecerProxima(ObjEvento.target.value)} /></label><label>Diagnóstico (opcional)<textarea value={StrDiagnostico} onChange={ObjEvento => establecerDiagnostico(ObjEvento.target.value)} /></label><label>Observaciones (opcional)<textarea value={StrObservaciones} onChange={ObjEvento => establecerObservaciones(ObjEvento.target.value)} /></label></div>
      <fieldset><legend>Detalles clínicos y fuentes</legend>{ArrDetalles.length === 0 && <p className="alimentacion-aviso">Aplicación sin consumo de Inventario.</p>}{ArrDetalles.map((ObjDetalle, IntIndice) => <DetalleSanidadFormulario key={ObjDetalle.IntClave} ObjDetalle={ObjDetalle} IntIndice={IntIndice} StrDestino={StrDestino} StrFecha={StrFecha} ArrProductos={ArrProductos} ArrAlmacenes={ArrAlmacenes} ArrVias={ArrVias} ArrUnidades={ArrUnidades} Sanidad_actualizarDetalle={Sanidad_actualizarDetalle} Sanidad_actualizarFuente={Sanidad_actualizarFuente} Sanidad_seleccionarProducto={Sanidad_seleccionarProducto} Sanidad_nuevaClave={() => IntSiguiente.current++} Sanidad_quitar={() => establecerDetalles(Arr => Arr.filter(Obj => Obj.IntClave !== ObjDetalle.IntClave))} />)}<button type="button" className="boton-secundario" onClick={() => establecerDetalles(Arr => [...Arr, Sanidad_nuevoDetalle(IntSiguiente.current++, IntSiguiente.current++)])}>Agregar producto</button></fieldset>
      <button type="button" className="boton-primario" disabled={BoolProcesando} onClick={() => { const StrValidacion = Sanidad_validar(); if (StrValidacion) establecerError(StrValidacion); else establecerConfirmar(true); }}>Revisar y confirmar</button></section>
    <Modal BoolAbierto={BoolConfirmar} StrTitulo="Confirmar aplicación sanitaria" Autenticacion_cerrar={() => establecerConfirmar(false)}><p><strong>Destino:</strong> {StrDestino === "ANIMAL" ? ObjAnimal?.identificacion : ObjLote?.codigo}</p><p><strong>Fecha:</strong> {StrFecha.replace("T", " ")}</p><p><strong>Motivo:</strong> {StrMotivo}</p>{ArrDetalles.length === 0 ? <p><strong>Aplicación sin consumo de Inventario</strong></p> : <ul>{ArrDetalles.map(Obj => <li key={Obj.IntClave}>{Obj.ObjProducto?.nombre}: {Obj.StrDosis} · {Obj.ArrFuentes.length} fuente(s)</li>)}</ul>}<button className="boton-primario" disabled={BoolProcesando} onClick={() => void Sanidad_confirmarRegistro()}>{BoolProcesando ? "Registrando…" : "Confirmar aplicación"}</button></Modal>
  </div>;
}

function DetalleSanidadFormulario(Prop: { ObjDetalle: DetalleFormulario; IntIndice: number; StrDestino: "ANIMAL" | "LOTE"; StrFecha: string; ArrProductos: ProductoSanidad[]; ArrAlmacenes: AlmacenSanidad[]; ArrVias: CatalogoSanidad[]; ArrUnidades: CatalogoSanidad[]; Sanidad_actualizarDetalle: (IntClave: number, ObjCambio: Partial<DetalleFormulario>) => void; Sanidad_actualizarFuente: (IntDetalle: number, IntFuente: number, ObjCambio: Partial<FuenteFormulario>) => void; Sanidad_seleccionarProducto: (IntClave: number, ObjProducto: ProductoSanidad | null) => Promise<void>; Sanidad_nuevaClave: () => number; Sanidad_quitar: () => void }) {
  const { ObjDetalle: D } = Prop;
  return <article className="sanidad-detalle"><Autocomplete StrEtiqueta={`Producto ${Prop.IntIndice + 1}`} StrPlaceholder="Buscar por código o nombre..." ObjSeleccion={D.ObjProducto} Autocomplete_buscar={async StrBusqueda => Prop.ArrProductos.filter(Obj => `${Obj.codigo} ${Obj.nombre}`.toLowerCase().includes(StrBusqueda.toLowerCase()))} Autocomplete_clave={Obj => Obj.productoId} Autocomplete_etiqueta={Obj => `${Obj.codigo} — ${Obj.nombre} — ${Obj.unidadMedida}`} Autocomplete_seleccionar={Obj => void Prop.Sanidad_seleccionarProducto(D.IntClave, Obj)} />
    <div className="sanidad-clinico"><label>Dosis clínica<input inputMode="decimal" value={D.StrDosis} onChange={ObjEvento => Prop.Sanidad_actualizarDetalle(D.IntClave, { StrDosis: ObjEvento.target.value })} /></label><label>Unidad clínica<select value={D.IntUnidadId ?? ""} onChange={ObjEvento => Prop.Sanidad_actualizarDetalle(D.IntClave, { IntUnidadId: ObjEvento.target.value ? Number(ObjEvento.target.value) : null })}><option value="">Seleccione</option>{Prop.ArrUnidades.map(Obj => <option key={Sanidad_idCatalogo(Obj)} value={Sanidad_idCatalogo(Obj)}>{Obj.nombre}</option>)}</select></label><label>Vía de administración<select value={D.IntViaId ?? ""} onChange={ObjEvento => Prop.Sanidad_actualizarDetalle(D.IntClave, { IntViaId: ObjEvento.target.value ? Number(ObjEvento.target.value) : null })}><option value="">Seleccione</option>{Prop.ArrVias.map(Obj => <option key={Sanidad_idCatalogo(Obj)} value={Sanidad_idCatalogo(Obj)}>{Obj.nombre}</option>)}</select></label><label>Alcance<select disabled={Prop.StrDestino === "ANIMAL"} value={D.StrAlcance} onChange={ObjEvento => Prop.Sanidad_actualizarDetalle(D.IntClave, { StrAlcance: ObjEvento.target.value as Alcance })}>{Prop.StrDestino === "ANIMAL" ? <option value="INDIVIDUAL">Individual</option> : <><option value="POR_ANIMAL">Por animal</option><option value="TOTAL_LOTE">Total del lote</option></>}</select><small>La dosis clínica no calcula automáticamente el consumo físico.</small></label></div>
    {D.ObjProducto && <div className="sanidad-fuentes"><h4>Fuentes físicas ({D.ObjProducto.unidadMedida})</h4>{D.ArrFuentes.map((ObjFuente, IntIndice) => { const ObjInventarios = new Set(D.ArrExistencias.map(Obj => Obj.inventarioId)); return <div className="sanidad-fuente" key={ObjFuente.IntClave}><Autocomplete StrEtiqueta={`Almacén ${IntIndice + 1}`} StrPlaceholder="Buscar almacén..." ObjSeleccion={ObjFuente.ObjAlmacen} Autocomplete_buscar={async StrBusqueda => Prop.ArrAlmacenes.filter(Obj => ObjInventarios.has(Obj.inventarioId) && `${Obj.codigo} ${Obj.nombre}`.toLowerCase().includes(StrBusqueda.toLowerCase()))} Autocomplete_clave={Obj => Obj.inventarioId} Autocomplete_etiqueta={Obj => `${Obj.codigo} — ${Obj.nombre}`} Autocomplete_seleccionar={Obj => Prop.Sanidad_actualizarFuente(D.IntClave, ObjFuente.IntClave, { ObjAlmacen: Obj, ObjLote: null })} />{ObjFuente.ObjAlmacen && <Autocomplete StrEtiqueta="Lote de Inventario" StrPlaceholder="Buscar lote..." ObjSeleccion={ObjFuente.ObjLote} Autocomplete_buscar={async StrBusqueda => (await S.Sanidad_lotesInventario(D.ObjProducto!.productoId, ObjFuente.ObjAlmacen!.inventarioId, Prop.StrFecha ? Fecha_datetimeLocalAContratoGuatemala(Prop.StrFecha) : undefined)).filter(Obj => Obj.lote.codigoLote.toLowerCase().includes(StrBusqueda.toLowerCase()))} Autocomplete_clave={Obj => Obj.loteInventarioId} Autocomplete_etiqueta={Obj => `${Obj.lote.codigoLote} — Disponible: ${Obj.existenciaActual} ${D.ObjProducto!.unidadMedida} — ${Obj.lote.fechaVencimiento ? `Vence: ${Obj.lote.fechaVencimiento}` : "Sin vencimiento"}`} Autocomplete_seleccionar={Obj => Prop.Sanidad_actualizarFuente(D.IntClave, ObjFuente.IntClave, { ObjLote: Obj })} />}<label>Cantidad física<input inputMode="decimal" value={ObjFuente.StrCantidad} onChange={ObjEvento => Prop.Sanidad_actualizarFuente(D.IntClave, ObjFuente.IntClave, { StrCantidad: ObjEvento.target.value })} /></label><button type="button" disabled={D.ArrFuentes.length === 1} onClick={() => Prop.Sanidad_actualizarDetalle(D.IntClave, { ArrFuentes: D.ArrFuentes.filter(Obj => Obj.IntClave !== ObjFuente.IntClave) })}>Quitar fuente</button></div>; })}<button type="button" onClick={() => Prop.Sanidad_actualizarDetalle(D.IntClave, { ArrFuentes: [...D.ArrFuentes, Sanidad_nuevaFuente(Prop.Sanidad_nuevaClave())] })}>Agregar fuente</button></div>}
    <button type="button" onClick={Prop.Sanidad_quitar}>Quitar producto</button></article>;
}
