import { useState, type FormEvent } from "react";
import { Autocomplete } from "../ui/Autocomplete";
import type { AlmacenInventario, DatosAjuste, DatosEntrada, DatosSalida, DatosTransferencia, LoteInventario, ProductoInventario, ProveedorInventario } from "../../types/inventario.types";
import { Inventario_decimalValido, Inventario_opcional } from "../../utils/inventario";
import { Inventario_unidadesCompatibles } from "../../utils/unidadesInventario";

type TipoFormulario = "COMPRA" | "INVENTARIO_INICIAL" | "DEVOLUCION_PROVEEDOR" | "MERMA" | "DISPOSICION" | "CONTEO_FISICO" | "TRANSFERENCIA";
interface Propiedades { StrTipo: TipoFormulario; ArrProductos: ProductoInventario[]; ArrAlmacenes: AlmacenInventario[]; ArrProveedores: ProveedorInventario[]; ArrLotes: LoteInventario[]; BoolProcesando: boolean; Inventario_cancelar: () => void; Inventario_guardar: (ObjDatos: DatosEntrada | DatosSalida | DatosAjuste | DatosTransferencia) => Promise<void> }

export function FormularioOperacion({ StrTipo, ArrProductos, ArrAlmacenes, ArrProveedores, ArrLotes, BoolProcesando, Inventario_cancelar, Inventario_guardar }: Propiedades) {
  const [IntProductoId, establecerProducto] = useState(0); const [IntAlmacenId, establecerAlmacen] = useState(0); const [IntDestinoId, establecerDestino] = useState(0); const [IntProveedorId, establecerProveedor] = useState(0); const [IntLoteId, establecerLote] = useState(0); const [StrUnidadComercial, establecerUnidadComercial] = useState(""); const [StrCantidad, establecerCantidad] = useState(""); const [StrCosto, establecerCosto] = useState(""); const [StrFabricacion, establecerFabricacion] = useState(""); const [StrVencimiento, establecerVencimiento] = useState(""); const [StrDocumento, establecerDocumento] = useState(""); const [StrMotivo, establecerMotivo] = useState(""); const [StrObservaciones, establecerObservaciones] = useState(""); const [StrError, establecerError] = useState<string | null>(null);
  const ObjProducto = ArrProductos.find((ObjItem) => ObjItem.productoId === IntProductoId); const BoolTransferencia = StrTipo === "TRANSFERENCIA"; const BoolCompra = StrTipo === "COMPRA"; const BoolEntrada = BoolCompra || StrTipo === "INVENTARIO_INICIAL"; const BoolAjuste = StrTipo === "CONTEO_FISICO"; const BoolProveedor = BoolCompra || StrTipo === "DEVOLUCION_PROVEEDOR"; const BoolRequiereCosto = BoolEntrada;
  const ObjProveedorSeleccionado = ArrProveedores.find((ObjProveedor) => ObjProveedor.proveedorId === IntProveedorId) ?? null; const ArrLotesProducto = ArrLotes.filter((ObjLote) => ObjLote.productoId === IntProductoId && ObjLote.activo);
  function Inventario_normalizarBusqueda(StrValor: string) { return StrValor.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase(); }
  async function Inventario_buscarProductos(StrBusqueda: string) { const StrFiltro = Inventario_normalizarBusqueda(StrBusqueda); return ArrProductos.filter((ObjItem) => Inventario_normalizarBusqueda(ObjItem.codigo).includes(StrFiltro) || Inventario_normalizarBusqueda(ObjItem.nombre).includes(StrFiltro)); }
  async function Inventario_buscarProveedores(StrBusqueda: string) { const StrFiltro = Inventario_normalizarBusqueda(StrBusqueda); return ArrProveedores.filter((ObjItem) => Inventario_normalizarBusqueda(ObjItem.codigo).includes(StrFiltro) || Inventario_normalizarBusqueda(ObjItem.nombre).includes(StrFiltro) || Inventario_normalizarBusqueda(ObjItem.nombreComercial ?? "").includes(StrFiltro)); }
  function Inventario_seleccionarProducto(ObjSeleccion: ProductoInventario | null) { establecerProducto(ObjSeleccion?.productoId ?? 0); establecerLote(0); establecerProveedor(0); establecerUnidadComercial(ObjSeleccion?.unidadMedida ?? ""); }
  async function Inventario_enviar(ObjEvento: FormEvent) { ObjEvento.preventDefault(); establecerError(null); if (!IntProductoId || !IntAlmacenId || !Inventario_decimalValido(StrCantidad, BoolAjuste) || StrCantidad === "0") { establecerError("Seleccione producto y almacén e ingrese una cantidad válida."); return; } if (BoolEntrada && (!StrUnidadComercial || !Inventario_decimalValido(StrCosto))) { establecerError("Indique la unidad de medida y un precio total válido."); return; } if (BoolCompra && !IntProveedorId) { establecerError("La compra requiere proveedor."); return; } if (StrFabricacion && StrVencimiento && StrFabricacion > StrVencimiento) { establecerError("La fabricación no puede ser posterior al vencimiento."); return; } if (BoolTransferencia && (!IntDestinoId || IntDestinoId === IntAlmacenId)) { establecerError("Seleccione un almacén de destino diferente."); return; } if (!BoolEntrada && !IntLoteId) { establecerError("El producto requiere lote."); return; } if (BoolAjuste && !StrMotivo.trim()) { establecerError("El conteo físico requiere motivo."); return; }
    const ObjComun = { productoId: IntProductoId, cantidad: StrCantidad, documentoReferencia: Inventario_opcional(StrDocumento), motivo: Inventario_opcional(StrMotivo), observaciones: Inventario_opcional(StrObservaciones), ...(IntLoteId ? { loteInventarioId: IntLoteId } : {}) };
    if (BoolTransferencia) await Inventario_guardar({ ...ObjComun, inventarioOrigenId: IntAlmacenId, inventarioDestinoId: IntDestinoId } as DatosTransferencia);
    else if (BoolAjuste) await Inventario_guardar({ ...ObjComun, inventarioId: IntAlmacenId, subtipo: "CONTEO_FISICO", motivo: StrMotivo.trim() } as DatosAjuste);
    else if (BoolEntrada) await Inventario_guardar({ productoId: IntProductoId, inventarioId: IntAlmacenId, subtipo: StrTipo, cantidadComercial: StrCantidad, unidadComercial: StrUnidadComercial, precioTotalIngreso: StrCosto, ...(IntProveedorId ? { proveedorId: IntProveedorId } : {}), fechaFabricacion: Inventario_opcional(StrFabricacion), fechaVencimiento: Inventario_opcional(StrVencimiento), documentoReferencia: Inventario_opcional(StrDocumento), motivo: Inventario_opcional(StrMotivo), observaciones: Inventario_opcional(StrObservaciones) } as DatosEntrada);
    else await Inventario_guardar({ ...ObjComun, inventarioId: IntAlmacenId, subtipo: StrTipo, ...(IntProveedorId ? { proveedorId: IntProveedorId } : {}) } as DatosSalida);
  }
  return <form className="inventario-formulario" onSubmit={(ObjEvento) => void Inventario_enviar(ObjEvento)}><div className="formulario-dos-columnas">{StrTipo === "INVENTARIO_INICIAL" ? <Autocomplete<ProductoInventario> StrEtiqueta="Producto" StrPlaceholder="Buscar producto por código o nombre..." ObjSeleccion={ObjProducto ?? null} Autocomplete_buscar={Inventario_buscarProductos} Autocomplete_clave={(ObjItem) => ObjItem.productoId} Autocomplete_etiqueta={(ObjItem) => `${ObjItem.codigo} · ${ObjItem.nombre}`} Autocomplete_seleccionar={Inventario_seleccionarProducto} /> : <div className="campo-formulario"><label htmlFor="op-producto">Producto</label><select id="op-producto" value={IntProductoId} onChange={(ObjEvento) => Inventario_seleccionarProducto(ArrProductos.find((ObjItem) => ObjItem.productoId === Number(ObjEvento.target.value)) ?? null)} required><option value={0}>Seleccione</option>{ArrProductos.map((ObjItem) => <option value={ObjItem.productoId} key={ObjItem.productoId}>{ObjItem.codigo} · {ObjItem.nombre}</option>)}</select></div>}<div className="campo-formulario"><label htmlFor="op-almacen">{BoolTransferencia ? "Almacén origen" : "Almacén"}</label><select id="op-almacen" value={IntAlmacenId} onChange={(ObjEvento) => establecerAlmacen(Number(ObjEvento.target.value))} required><option value={0}>Seleccione</option>{ArrAlmacenes.map((ObjItem) => <option value={ObjItem.inventarioId} key={ObjItem.inventarioId}>{ObjItem.codigo} · {ObjItem.nombre}</option>)}</select></div>
  {BoolTransferencia && <div className="campo-formulario"><label htmlFor="op-destino">Almacén destino</label><select id="op-destino" value={IntDestinoId} onChange={(ObjEvento) => establecerDestino(Number(ObjEvento.target.value))} required><option value={0}>Seleccione</option>{ArrAlmacenes.filter((ObjItem) => ObjItem.inventarioId !== IntAlmacenId).map((ObjItem) => <option value={ObjItem.inventarioId} key={ObjItem.inventarioId}>{ObjItem.codigo} · {ObjItem.nombre}</option>)}</select></div>}
  {BoolCompra || StrTipo === "INVENTARIO_INICIAL" ? <Autocomplete<ProveedorInventario> StrEtiqueta={BoolCompra ? "Proveedor" : "Proveedor (opcional)"} StrPlaceholder="Buscar proveedor por código o nombre..." ObjSeleccion={ObjProveedorSeleccionado} Autocomplete_buscar={Inventario_buscarProveedores} Autocomplete_clave={(ObjItem) => ObjItem.proveedorId} Autocomplete_etiqueta={(ObjItem) => `${ObjItem.codigo} · ${ObjItem.nombreComercial || ObjItem.nombre}`} Autocomplete_seleccionar={(ObjItem) => establecerProveedor(ObjItem?.proveedorId ?? 0)} /> : BoolProveedor && <div className="campo-formulario"><label htmlFor="op-proveedor">Proveedor</label><select id="op-proveedor" value={IntProveedorId} onChange={(ObjEvento) => establecerProveedor(Number(ObjEvento.target.value))} required><option value={0}>Seleccione</option>{ArrProveedores.map((ObjItem) => <option value={ObjItem.proveedorId} key={ObjItem.proveedorId}>{ObjItem.codigo} · {ObjItem.nombreComercial || ObjItem.nombre}</option>)}</select></div>}
  {!BoolEntrada && <div className="campo-formulario"><label htmlFor="op-lote">Lote</label><select id="op-lote" value={IntLoteId} onChange={(ObjEvento) => establecerLote(Number(ObjEvento.target.value))}><option value={0}>Seleccione</option>{ArrLotesProducto.map((ObjItem) => <option value={ObjItem.loteInventarioId} key={ObjItem.loteInventarioId}>{ObjItem.codigoLote}{ObjItem.fechaVencimiento ? ` · vence ${ObjItem.fechaVencimiento.slice(0, 10)}` : " · sin vencimiento"}</option>)}</select></div>}
  {BoolEntrada && <><div className="campo-formulario"><label htmlFor="op-unidad-comercial">Unidad de medida</label><select id="op-unidad-comercial" value={StrUnidadComercial} onChange={(ObjEvento) => establecerUnidadComercial(ObjEvento.target.value)} required><option value="">Seleccione</option>{Inventario_unidadesCompatibles(ObjProducto?.unidadMedida ?? "").map((ObjUnidad) => <option key={ObjUnidad.StrValor} value={ObjUnidad.StrValor}>{ObjUnidad.StrEtiqueta}</option>)}</select></div><div className="campo-formulario"><label htmlFor="op-fabricacion">Fabricación</label><input id="op-fabricacion" type="date" value={StrFabricacion} onChange={(ObjEvento) => establecerFabricacion(ObjEvento.target.value)} /></div><div className="campo-formulario"><label htmlFor="op-vencimiento">Vencimiento</label><input id="op-vencimiento" type="date" value={StrVencimiento} onChange={(ObjEvento) => establecerVencimiento(ObjEvento.target.value)} /></div></>}
  <div className="campo-formulario"><label htmlFor="op-cantidad">{BoolEntrada ? "Cantidad a ingresar" : "Cantidad"} {ObjProducto && !BoolEntrada ? `(${ObjProducto.unidadMedida})` : ""}</label><input id="op-cantidad" inputMode="decimal" value={StrCantidad} onChange={(ObjEvento) => establecerCantidad(ObjEvento.target.value)} required /></div>{BoolRequiereCosto && <div className="campo-formulario"><label htmlFor="op-costo">Precio total del ingreso (Q)</label><input id="op-costo" inputMode="decimal" value={StrCosto} onChange={(ObjEvento) => establecerCosto(ObjEvento.target.value)} required /></div>}<div className="campo-formulario"><label htmlFor="op-documento">Documento de referencia</label><input id="op-documento" value={StrDocumento} maxLength={150} onChange={(ObjEvento) => establecerDocumento(ObjEvento.target.value)} /></div><div className="campo-formulario"><label htmlFor="op-motivo">Motivo</label><input id="op-motivo" value={StrMotivo} maxLength={500} onChange={(ObjEvento) => establecerMotivo(ObjEvento.target.value)} required={BoolAjuste} /></div><div className="campo-formulario campo-ancho"><label htmlFor="op-observaciones">Observaciones</label><textarea id="op-observaciones" value={StrObservaciones} maxLength={1000} onChange={(ObjEvento) => establecerObservaciones(ObjEvento.target.value)} /></div></div>{StrError && <p className="mensaje-error" role="alert">{StrError}</p>}<div className="modal-acciones"><button type="button" className="boton-secundario" onClick={Inventario_cancelar} disabled={BoolProcesando}>Cancelar</button><button type="submit" className="boton-primario" disabled={BoolProcesando}>{BoolProcesando ? "Procesando…" : "Continuar"}</button></div></form>;
}
