import { useMemo, useState, type FormEvent } from "react";
import type { AlmacenInventario, DatosAjuste, DatosEntrada, DatosSalida, DatosTransferencia, LoteInventario, ProductoInventario, ProveedorInventario, ProveedorProducto } from "../../types/inventario.types";
import { Inventario_decimalValido, Inventario_opcional } from "../../utils/inventario";

type TipoFormulario = "COMPRA" | "INVENTARIO_INICIAL" | "DEVOLUCION_PROVEEDOR" | "MERMA" | "DISPOSICION" | "CONTEO_FISICO" | "TRANSFERENCIA";
interface Propiedades { StrTipo: TipoFormulario; ArrProductos: ProductoInventario[]; ArrAlmacenes: AlmacenInventario[]; ArrProveedores: ProveedorInventario[]; ArrRelaciones: ProveedorProducto[]; ArrLotes: LoteInventario[]; BoolProcesando: boolean; Inventario_cancelar: () => void; Inventario_guardar: (ObjDatos: DatosEntrada | DatosSalida | DatosAjuste | DatosTransferencia) => Promise<void> }

export function FormularioOperacion({ StrTipo, ArrProductos, ArrAlmacenes, ArrProveedores, ArrRelaciones, ArrLotes, BoolProcesando, Inventario_cancelar, Inventario_guardar }: Propiedades) {
  const [IntProductoId, establecerProducto] = useState(0); const [IntAlmacenId, establecerAlmacen] = useState(0); const [IntDestinoId, establecerDestino] = useState(0); const [IntProveedorId, establecerProveedor] = useState(0); const [IntLoteId, establecerLote] = useState(0); const [BoolLoteNuevo, establecerLoteNuevo] = useState(false); const [StrCodigoLote, establecerCodigoLote] = useState(""); const [StrCantidad, establecerCantidad] = useState(""); const [StrCosto, establecerCosto] = useState(""); const [StrFabricacion, establecerFabricacion] = useState(""); const [StrVencimiento, establecerVencimiento] = useState(""); const [StrDocumento, establecerDocumento] = useState(""); const [StrMotivo, establecerMotivo] = useState(""); const [StrObservaciones, establecerObservaciones] = useState(""); const [StrError, establecerError] = useState<string | null>(null);
  const ObjProducto = ArrProductos.find((ObjItem) => ObjItem.productoId === IntProductoId); const BoolTransferencia = StrTipo === "TRANSFERENCIA"; const BoolCompra = StrTipo === "COMPRA"; const BoolAjuste = StrTipo === "CONTEO_FISICO"; const BoolProveedor = BoolCompra || StrTipo === "DEVOLUCION_PROVEEDOR";
  const ArrRelacionesProducto = useMemo(() => ArrRelaciones.filter((ObjRelacion) => ObjRelacion.productoId === IntProductoId && ObjRelacion.activo), [ArrRelaciones, IntProductoId]);
  const ArrProveedoresPermitidos = ArrProveedores.filter((ObjProveedor) => ArrRelacionesProducto.some((ObjRelacion) => ObjRelacion.proveedorId === ObjProveedor.proveedorId)); const ArrLotesProducto = ArrLotes.filter((ObjLote) => ObjLote.productoId === IntProductoId && ObjLote.activo);
  async function Inventario_enviar(ObjEvento: FormEvent) { ObjEvento.preventDefault(); establecerError(null); if (!IntProductoId || !IntAlmacenId || !Inventario_decimalValido(StrCantidad, BoolAjuste) || StrCantidad === "0") { establecerError("Seleccione producto y almacén e ingrese una cantidad válida."); return; } if (BoolCompra && (!IntProveedorId || !Inventario_decimalValido(StrCosto))) { establecerError("La compra requiere proveedor y costo unitario válido."); return; } if (BoolTransferencia && (!IntDestinoId || IntDestinoId === IntAlmacenId)) { establecerError("Seleccione un almacén de destino diferente."); return; } if (ObjProducto?.manejaLotes && !IntLoteId && !(BoolCompra || StrTipo === "INVENTARIO_INICIAL") || ObjProducto?.manejaLotes && BoolLoteNuevo && !StrCodigoLote.trim()) { establecerError("El producto requiere lote."); return; } if (BoolAjuste && !StrMotivo.trim()) { establecerError("El conteo físico requiere motivo."); return; }
    const ObjComun = { productoId: IntProductoId, cantidad: StrCantidad, documentoReferencia: Inventario_opcional(StrDocumento), motivo: Inventario_opcional(StrMotivo), observaciones: Inventario_opcional(StrObservaciones), ...(IntLoteId ? { loteInventarioId: IntLoteId } : {}) };
    if (BoolTransferencia) await Inventario_guardar({ ...ObjComun, inventarioOrigenId: IntAlmacenId, inventarioDestinoId: IntDestinoId } as DatosTransferencia);
    else if (BoolAjuste) await Inventario_guardar({ ...ObjComun, inventarioId: IntAlmacenId, subtipo: "CONTEO_FISICO", motivo: StrMotivo.trim() } as DatosAjuste);
    else if (BoolCompra || StrTipo === "INVENTARIO_INICIAL") await Inventario_guardar({ ...ObjComun, inventarioId: IntAlmacenId, subtipo: StrTipo, ...(IntProveedorId ? { proveedorId: IntProveedorId } : {}), ...(BoolLoteNuevo ? { codigoLote: StrCodigoLote.trim(), fechaFabricacion: Inventario_opcional(StrFabricacion), fechaVencimiento: Inventario_opcional(StrVencimiento) } : {}), ...(StrCosto ? { costoUnitario: StrCosto } : {}) } as DatosEntrada);
    else await Inventario_guardar({ ...ObjComun, inventarioId: IntAlmacenId, subtipo: StrTipo, ...(IntProveedorId ? { proveedorId: IntProveedorId } : {}) } as DatosSalida);
  }
  return <form className="inventario-formulario" onSubmit={(ObjEvento) => void Inventario_enviar(ObjEvento)}><div className="formulario-dos-columnas"><div className="campo-formulario"><label htmlFor="op-producto">Producto</label><select id="op-producto" value={IntProductoId} onChange={(ObjEvento) => { establecerProducto(Number(ObjEvento.target.value)); establecerLote(0); establecerProveedor(0); }} required><option value={0}>Seleccione</option>{ArrProductos.map((ObjItem) => <option value={ObjItem.productoId} key={ObjItem.productoId}>{ObjItem.codigo} · {ObjItem.nombre}</option>)}</select></div><div className="campo-formulario"><label htmlFor="op-almacen">{BoolTransferencia ? "Almacén origen" : "Almacén"}</label><select id="op-almacen" value={IntAlmacenId} onChange={(ObjEvento) => establecerAlmacen(Number(ObjEvento.target.value))} required><option value={0}>Seleccione</option>{ArrAlmacenes.map((ObjItem) => <option value={ObjItem.inventarioId} key={ObjItem.inventarioId}>{ObjItem.codigo} · {ObjItem.nombre}</option>)}</select></div>
  {BoolTransferencia && <div className="campo-formulario"><label htmlFor="op-destino">Almacén destino</label><select id="op-destino" value={IntDestinoId} onChange={(ObjEvento) => establecerDestino(Number(ObjEvento.target.value))} required><option value={0}>Seleccione</option>{ArrAlmacenes.filter((ObjItem) => ObjItem.inventarioId !== IntAlmacenId).map((ObjItem) => <option value={ObjItem.inventarioId} key={ObjItem.inventarioId}>{ObjItem.codigo} · {ObjItem.nombre}</option>)}</select></div>}
  {BoolProveedor && <div className="campo-formulario"><label htmlFor="op-proveedor">Proveedor</label><select id="op-proveedor" value={IntProveedorId} onChange={(ObjEvento) => establecerProveedor(Number(ObjEvento.target.value))} required><option value={0}>Seleccione</option>{ArrProveedoresPermitidos.map((ObjItem) => <option value={ObjItem.proveedorId} key={ObjItem.proveedorId}>{ObjItem.codigo} · {ObjItem.nombreComercial || ObjItem.nombre}</option>)}</select></div>}
  {ObjProducto?.manejaLotes && <><div className="campo-formulario"><label htmlFor="op-lote">Lote</label><select id="op-lote" value={IntLoteId} onChange={(ObjEvento) => { establecerLote(Number(ObjEvento.target.value)); establecerLoteNuevo(false); }}><option value={0}>Seleccione</option>{ArrLotesProducto.map((ObjItem) => <option value={ObjItem.loteInventarioId} key={ObjItem.loteInventarioId}>{ObjItem.codigoLote}{ObjItem.fechaVencimiento ? ` · vence ${ObjItem.fechaVencimiento.slice(0, 10)}` : " · sin vencimiento"}</option>)}</select></div>{(BoolCompra || StrTipo === "INVENTARIO_INICIAL") && <label className="campo-check"><input type="checkbox" checked={BoolLoteNuevo} onChange={(ObjEvento) => { establecerLoteNuevo(ObjEvento.target.checked); establecerLote(0); }} /> Registrar lote nuevo</label>}</>}
  {BoolLoteNuevo && <><div className="campo-formulario"><label htmlFor="op-codigo-lote">Código de lote</label><input id="op-codigo-lote" value={StrCodigoLote} maxLength={100} onChange={(ObjEvento) => establecerCodigoLote(ObjEvento.target.value)} required /></div><div className="campo-formulario"><label htmlFor="op-fabricacion">Fabricación</label><input id="op-fabricacion" type="date" value={StrFabricacion} onChange={(ObjEvento) => establecerFabricacion(ObjEvento.target.value)} /></div><div className="campo-formulario"><label htmlFor="op-vencimiento">Vencimiento</label><input id="op-vencimiento" type="date" value={StrVencimiento} onChange={(ObjEvento) => establecerVencimiento(ObjEvento.target.value)} /></div></>}
  <div className="campo-formulario"><label htmlFor="op-cantidad">Cantidad {ObjProducto ? `(${ObjProducto.unidadMedida})` : ""}</label><input id="op-cantidad" inputMode="decimal" value={StrCantidad} onChange={(ObjEvento) => establecerCantidad(ObjEvento.target.value)} required /></div>{BoolCompra && <div className="campo-formulario"><label htmlFor="op-costo">Costo unitario</label><input id="op-costo" inputMode="decimal" value={StrCosto} onChange={(ObjEvento) => establecerCosto(ObjEvento.target.value)} required /></div>}<div className="campo-formulario"><label htmlFor="op-documento">Documento de referencia</label><input id="op-documento" value={StrDocumento} maxLength={150} onChange={(ObjEvento) => establecerDocumento(ObjEvento.target.value)} /></div><div className="campo-formulario"><label htmlFor="op-motivo">Motivo</label><input id="op-motivo" value={StrMotivo} maxLength={500} onChange={(ObjEvento) => establecerMotivo(ObjEvento.target.value)} required={BoolAjuste} /></div><div className="campo-formulario campo-ancho"><label htmlFor="op-observaciones">Observaciones</label><textarea id="op-observaciones" value={StrObservaciones} maxLength={1000} onChange={(ObjEvento) => establecerObservaciones(ObjEvento.target.value)} /></div></div>{StrError && <p className="mensaje-error" role="alert">{StrError}</p>}<div className="modal-acciones"><button type="button" className="boton-secundario" onClick={Inventario_cancelar} disabled={BoolProcesando}>Cancelar</button><button type="submit" className="boton-primario" disabled={BoolProcesando}>{BoolProcesando ? "Procesando…" : "Continuar"}</button></div></form>;
}
