import { useCallback, useState } from "react";
import { DialogoConfirmacion } from "../../components/ui/DialogoConfirmacion";
import { InsigniaEstado } from "../../components/ui/InsigniaEstado";
import { MensajeError } from "../../components/ui/MensajeError";
import { Modal } from "../../components/ui/Modal";
import { Inventario_mensajeError, useInventarioLista } from "../../hooks/useInventarioLista";
import { useSesion } from "../../hooks/useSesion";
import * as S from "../../services/inventario.service";
import type { AlmacenInventario, CategoriaInventario, DatosAlmacen, DatosCategoria } from "../../types/inventario.types";
import { Inventario_opcional } from "../../utils/inventario";

const Inventario_categorias = (Obj: { pagina: number; limite: number; busqueda?: string; estado?: "ACTIVO" | "INACTIVO" }) => S.Inventario_listarCategorias(Obj);
const Inventario_almacenes = (Obj: { pagina: number; limite: number; busqueda?: string; estado?: "ACTIVO" | "INACTIVO" }) => S.Inventario_listarAlmacenes(Obj);

export function PaginaCatalogosInventario() {
  const { Autenticacion_tienePermiso } = useSesion(); const ObjCategorias = useInventarioLista(Inventario_categorias, {}); const ObjAlmacenes = useInventarioLista(Inventario_almacenes, {});
  const [StrPestana, establecerPestana] = useState<"categorias" | "almacenes">("categorias"); const [ObjCategoria, establecerCategoria] = useState<CategoriaInventario | "nuevo" | null>(null); const [ObjAlmacen, establecerAlmacen] = useState<AlmacenInventario | "nuevo" | null>(null); const [ObjEstado, establecerEstado] = useState<{ StrTipo: "categoria" | "almacen"; IntId: number; BoolActivo: boolean } | null>(null); const [StrError, establecerError] = useState<string | null>(null); const [StrExito, establecerExito] = useState<string | null>(null); const [BoolProcesando, establecerProcesando] = useState(false);
  const Inventario_operar = useCallback(async (ObjAccion: () => Promise<unknown>, StrMensaje: string) => { establecerProcesando(true); establecerError(null); try { await ObjAccion(); establecerExito(StrMensaje); await Promise.all([ObjCategorias.Inventario_recargar(), ObjAlmacenes.Inventario_recargar()]); return true; } catch (ObjError) { establecerError(Inventario_mensajeError(ObjError)); return false; } finally { establecerProcesando(false); } }, [ObjCategorias, ObjAlmacenes]);
  const BoolCatCrear = Autenticacion_tienePermiso("INVENTARIO_CATEGORIAS_CREAR"), BoolCatEditar = Autenticacion_tienePermiso("INVENTARIO_CATEGORIAS_EDITAR"), BoolCatEstado = Autenticacion_tienePermiso("INVENTARIO_CATEGORIAS_CAMBIAR_ESTADO"), BoolAlmCrear = Autenticacion_tienePermiso("INVENTARIO_ALMACENES_CREAR"), BoolAlmEditar = Autenticacion_tienePermiso("INVENTARIO_ALMACENES_EDITAR"), BoolAlmEstado = Autenticacion_tienePermiso("INVENTARIO_ALMACENES_CAMBIAR_ESTADO");
  return <div className="inventario-contenido"><header className="inventario-seccion-encabezado"><div><h2>Catálogos</h2><p>Clasificación y ubicaciones de Inventario.</p></div>{StrPestana === "categorias" && BoolCatCrear && <button className="boton-primario" onClick={() => establecerCategoria("nuevo")}>Nueva categoría</button>}{StrPestana === "almacenes" && BoolAlmCrear && <button className="boton-primario" onClick={() => establecerAlmacen("nuevo")}>Nuevo almacén</button>}</header><div className="inventario-pestanas" role="tablist"><button role="tab" aria-selected={StrPestana === "categorias"} onClick={() => establecerPestana("categorias")}>Categorías</button><button role="tab" aria-selected={StrPestana === "almacenes"} onClick={() => establecerPestana("almacenes")}>Almacenes</button></div>{StrError && <MensajeError StrMensaje={StrError} />}{StrExito && <p role="status" className="mensaje-exito">{StrExito}</p>}
    {StrPestana === "categorias" ? <ListaCatalogo ArrDatos={ObjCategorias.ArrDatos} StrTipo="categoria" BoolEditar={BoolCatEditar} BoolEstado={BoolCatEstado} Inventario_editar={(Obj) => establecerCategoria(Obj as CategoriaInventario)} Inventario_estado={(Obj) => establecerEstado({ StrTipo: "categoria", IntId: (Obj as CategoriaInventario).categoriaId, BoolActivo: Obj.activo })} /> : <ListaCatalogo ArrDatos={ObjAlmacenes.ArrDatos} StrTipo="almacen" BoolEditar={BoolAlmEditar} BoolEstado={BoolAlmEstado} Inventario_editar={(Obj) => establecerAlmacen(Obj as AlmacenInventario)} Inventario_estado={(Obj) => establecerEstado({ StrTipo: "almacen", IntId: (Obj as AlmacenInventario).inventarioId, BoolActivo: Obj.activo })} />}
    <Modal BoolAbierto={ObjCategoria !== null} StrTitulo={ObjCategoria === "nuevo" ? "Nueva categoría" : "Editar categoría"} Autenticacion_cerrar={() => establecerCategoria(null)}>{ObjCategoria && <FormularioCategoria ObjCategoria={ObjCategoria === "nuevo" ? undefined : ObjCategoria} BoolProcesando={BoolProcesando} Inventario_cancelar={() => establecerCategoria(null)} Inventario_guardar={async (Obj) => { const BoolOk = await Inventario_operar(() => ObjCategoria === "nuevo" ? S.Inventario_crearCategoria(Obj) : S.Inventario_editarCategoria(ObjCategoria.categoriaId, Obj), "Categoría guardada."); if (BoolOk) establecerCategoria(null); }} />}</Modal>
    <Modal BoolAbierto={ObjAlmacen !== null} StrTitulo={ObjAlmacen === "nuevo" ? "Nuevo almacén" : "Editar almacén"} Autenticacion_cerrar={() => establecerAlmacen(null)}>{ObjAlmacen && <FormularioAlmacen ObjAlmacen={ObjAlmacen === "nuevo" ? undefined : ObjAlmacen} BoolProcesando={BoolProcesando} Inventario_cancelar={() => establecerAlmacen(null)} Inventario_guardar={async (Obj) => { const BoolOk = await Inventario_operar(() => ObjAlmacen === "nuevo" ? S.Inventario_crearAlmacen(Obj as DatosAlmacen) : S.Inventario_editarAlmacen(ObjAlmacen.inventarioId, Obj), "Almacén guardado."); if (BoolOk) establecerAlmacen(null); }} />}</Modal>
    <DialogoConfirmacion BoolAbierto={ObjEstado !== null} StrTitulo={`${ObjEstado?.BoolActivo ? "Inactivar" : "Activar"} ${ObjEstado?.StrTipo}`} StrMensaje="El registro y todo su historial permanecerán disponibles para consulta." StrConfirmar={ObjEstado?.BoolActivo ? "Inactivar" : "Activar"} BoolProcesando={BoolProcesando} Autenticacion_cancelar={() => establecerEstado(null)} Autenticacion_confirmar={() => { if (!ObjEstado) return; void Inventario_operar(() => ObjEstado.StrTipo === "categoria" ? S.Inventario_estadoCategoria(ObjEstado.IntId, !ObjEstado.BoolActivo) : S.Inventario_estadoAlmacen(ObjEstado.IntId, !ObjEstado.BoolActivo), "Estado actualizado.").then((BoolOk) => { if (BoolOk) establecerEstado(null); }); }} />
  </div>;
}

function ListaCatalogo({ ArrDatos, StrTipo, BoolEditar, BoolEstado, Inventario_editar, Inventario_estado }: { ArrDatos: Array<CategoriaInventario | AlmacenInventario>; StrTipo: "categoria" | "almacen"; BoolEditar: boolean; BoolEstado: boolean; Inventario_editar: (Obj: CategoriaInventario | AlmacenInventario) => void; Inventario_estado: (Obj: CategoriaInventario | AlmacenInventario) => void }) {
  const StrPlural = StrTipo === "categoria" ? "categorías" : "almacenes";
  if (!ArrDatos.length) return <p className="inventario-vacio">{StrTipo === "categoria" ? "No hay categorías registradas." : "No hay almacenes registrados."}</p>;
  return <><div className="inventario-tabla-contenedor" aria-label={`Tabla de ${StrPlural}`}><table><thead><tr>{StrTipo === "almacen" && <th>Código</th>}<th>Nombre</th><th>{StrTipo === "almacen" ? "Ubicación" : "Descripción"}</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{ArrDatos.map((Obj) => <tr key={"categoriaId" in Obj ? Obj.categoriaId : Obj.inventarioId}>{StrTipo === "almacen" && <td>{(Obj as AlmacenInventario).codigo}</td>}<td>{Obj.nombre}</td><td>{StrTipo === "almacen" ? (Obj as AlmacenInventario).ubicacion || "—" : Obj.descripcion || "—"}</td><td><InsigniaEstado StrEstado={Obj.activo ? "ACTIVO" : "INACTIVO"} /></td><td>{BoolEditar && <button onClick={() => Inventario_editar(Obj)}>Editar</button>} {BoolEstado && <button onClick={() => Inventario_estado(Obj)}>{Obj.activo ? "Inactivar" : "Activar"}</button>}</td></tr>)}</tbody></table></div><div className="inventario-tarjetas inventario-catalogo-tarjetas" aria-label={`${StrPlural} en vista móvil`}>{ArrDatos.map((Obj) => { const ObjAlmacen = StrTipo === "almacen" ? Obj as AlmacenInventario : null; return <article className="inventario-catalogo-tarjeta" key={"categoriaId" in Obj ? Obj.categoriaId : Obj.inventarioId}><div className="inventario-catalogo-tarjeta-encabezado"><strong>{ObjAlmacen ? `${ObjAlmacen.codigo} · ${Obj.nombre}` : Obj.nombre}</strong><InsigniaEstado StrEstado={Obj.activo ? "ACTIVO" : "INACTIVO"} /></div>{ObjAlmacen ? <><p><span>Ubicación:</span> {ObjAlmacen.ubicacion || "—"}</p><p><span>Descripción:</span> {ObjAlmacen.descripcion || "—"}</p></> : <p>{Obj.descripcion || "—"}</p>}{(BoolEditar || BoolEstado) && <div className="inventario-catalogo-acciones">{BoolEditar && <button onClick={() => Inventario_editar(Obj)}>Editar</button>}{BoolEstado && <button onClick={() => Inventario_estado(Obj)}>{Obj.activo ? "Inactivar" : "Activar"}</button>}</div>}</article>; })}</div></>;
}

function FormularioCategoria({ ObjCategoria, BoolProcesando, Inventario_cancelar, Inventario_guardar }: { ObjCategoria?: CategoriaInventario; BoolProcesando: boolean; Inventario_cancelar: () => void; Inventario_guardar: (Obj: DatosCategoria) => Promise<void> }) {
  const [StrNombre, establecerNombre] = useState(ObjCategoria?.nombre ?? ""); const [StrDescripcion, establecerDescripcion] = useState(ObjCategoria?.descripcion ?? "");
  return <form onSubmit={(ObjEvento) => { ObjEvento.preventDefault(); void Inventario_guardar({ nombre: StrNombre.trim(), descripcion: Inventario_opcional(StrDescripcion) }); }}><label className="campo-formulario">Nombre<input value={StrNombre} maxLength={150} onChange={(ObjEvento) => establecerNombre(ObjEvento.target.value)} required /></label><label className="campo-formulario">Descripción<textarea value={StrDescripcion} maxLength={500} onChange={(ObjEvento) => establecerDescripcion(ObjEvento.target.value)} /></label><div className="modal-acciones"><button type="button" onClick={Inventario_cancelar}>Cancelar</button><button className="boton-primario" disabled={BoolProcesando}>Guardar</button></div></form>;
}

function FormularioAlmacen({ ObjAlmacen, BoolProcesando, Inventario_cancelar, Inventario_guardar }: { ObjAlmacen?: AlmacenInventario; BoolProcesando: boolean; Inventario_cancelar: () => void; Inventario_guardar: (Obj: DatosAlmacen | Omit<DatosAlmacen, "codigo">) => Promise<void> }) {
  const [StrCodigo, establecerCodigo] = useState(ObjAlmacen?.codigo ?? ""); const [StrNombre, establecerNombre] = useState(ObjAlmacen?.nombre ?? ""); const [StrUbicacion, establecerUbicacion] = useState(ObjAlmacen?.ubicacion ?? ""); const [StrDescripcion, establecerDescripcion] = useState(ObjAlmacen?.descripcion ?? "");
  return <form onSubmit={(ObjEvento) => { ObjEvento.preventDefault(); const ObjDatos = { nombre: StrNombre.trim(), ubicacion: Inventario_opcional(StrUbicacion), descripcion: Inventario_opcional(StrDescripcion) }; void Inventario_guardar(ObjAlmacen ? ObjDatos : { ...ObjDatos, codigo: StrCodigo.trim() }); }}><div className="formulario-dos-columnas"><label className="campo-formulario">Código<input value={StrCodigo} readOnly={!!ObjAlmacen} maxLength={50} onChange={(ObjEvento) => establecerCodigo(ObjEvento.target.value)} required /></label><label className="campo-formulario">Nombre<input value={StrNombre} maxLength={150} onChange={(ObjEvento) => establecerNombre(ObjEvento.target.value)} required /></label><label className="campo-formulario">Ubicación<input value={StrUbicacion} maxLength={300} onChange={(ObjEvento) => establecerUbicacion(ObjEvento.target.value)} /></label><label className="campo-formulario">Descripción<textarea value={StrDescripcion} maxLength={500} onChange={(ObjEvento) => establecerDescripcion(ObjEvento.target.value)} /></label></div><div className="modal-acciones"><button type="button" onClick={Inventario_cancelar}>Cancelar</button><button className="boton-primario" disabled={BoolProcesando}>Guardar</button></div></form>;
}
