import { Prisma } from "../../../generated/prisma/client.js";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import * as R from "./reportes.repository.js";

export interface ConsultaReportesEntrada { pagina?:number;limite?:number;fechaDesde?:Date;fechaHasta?:Date;estado?:string;productoId?:number;inventarioId?:number;vista?:string;modulo?:string;exportar?:boolean }
function Reportes_diaPosterior(Dt:Date){const R=new Date(Dt);R.setUTCDate(R.getUTCDate()+1);return R;}
function Reportes_consulta(C:ConsultaReportesEntrada):R.ConsultaReporte{return{pagina:C.exportar?1:C.pagina??1,limite:C.exportar?100000:Math.min(C.limite??20,100),...(C.fechaDesde?{fechaDesde:C.fechaDesde}:{}),...(C.fechaHasta?{fechaHastaExclusiva:Reportes_diaPosterior(C.fechaHasta)}:{}),...(C.estado?{estado:C.estado}:{}),...(C.productoId?{productoId:C.productoId}:{}),...(C.inventarioId?{inventarioId:C.inventarioId}:{}),...(C.vista?{vista:C.vista}:{}),...(C.modulo?{modulo:C.modulo}:{})};}
function Reportes_normalizar(Valor:unknown):unknown{if(Valor instanceof Prisma.Decimal)return Valor.toString();if(Valor instanceof Date)return Valor.toISOString().replace("T"," ").replace("Z","");if(Array.isArray(Valor))return Valor.map(Reportes_normalizar);if(Valor&&typeof Valor==="object")return Object.fromEntries(Object.entries(Valor).map(([K,V])=>[K,Reportes_normalizar(V)]));return Valor;}
function Reportes_resultado(Obj:{datos:unknown[];total:number},C:R.ConsultaReporte){return{datos:Reportes_normalizar(Obj.datos),paginacion:{pagina:C.pagina,limite:C.limite,total:Obj.total}};}
function Reportes_validarCostos(Obj:unknown){const Arr=JSON.stringify(Reportes_normalizar(Obj));if(Arr.includes('"inventarioTransacciones":[]'))throw new ErrorAplicacion(409,"COSTO_HISTORICO_INCONSISTENTE","No existe una transacción histórica confiable para una fuente física.");}
export async function Reportes_consultar(StrReporte:string,E:ConsultaReportesEntrada){const C=Reportes_consulta(E);let O;switch(StrReporte){case"existencias":O=await R.Reportes_existencias(C);break;case"movimientos":O=await R.Reportes_movimientos(C);break;case"censo":O=await R.Reportes_censo(C);break;case"actividad":O=await R.Reportes_actividad(C);break;case"mediciones":O=await R.Reportes_mediciones(C);break;case"sanidad":O=await R.Reportes_sanidad(C);break;case"ventas":O=await R.Reportes_ventas(C);break;case"costos":O=await R.Reportes_costos(C);Reportes_validarCostos(O.datos);break;default:throw new ErrorAplicacion(404,"REPORTE_NO_ENCONTRADO","El reporte solicitado no existe.");}return Reportes_resultado(O,C);}
export async function Reportes_obtenerFiltros(){return Reportes_normalizar(await R.Reportes_filtros());}
function Reportes_aplanar(Obj:unknown,StrPrefijo=""):Record<string,string>{if(Obj===null||Obj===undefined)return{[StrPrefijo]:""};if(typeof Obj!=="object")return{[StrPrefijo]:String(Obj)};if(Array.isArray(Obj))return{[StrPrefijo]:JSON.stringify(Obj)};return Object.assign({},...Object.entries(Obj).map(([K,V])=>Reportes_aplanar(V,StrPrefijo?`${StrPrefijo}.${K}`:K)));}
function Reportes_csvCelda(Str:string){return /[",\r\n]/.test(Str)?`"${Str.replaceAll('"','""')}"`:Str;}
export function Reportes_crearCsv(ArrDatos:unknown[]){const Arr=ArrDatos.map(O=>Reportes_aplanar(O));const Enc=[...new Set(Arr.flatMap(O=>Object.keys(O)))];return"\uFEFF"+[Enc,...Arr.map(O=>Enc.map(K=>O[K]??""))].map(F=>F.map(Reportes_csvCelda).join(",")).join("\r\n");}
