import { Prisma } from "../../../generated/prisma/client.js";
import { BaseDatos_obtenerCliente } from "../../database/prisma.js";

export interface ConsultaReporte { pagina:number; limite:number; fechaDesde?:Date; fechaHastaExclusiva?:Date; estado?:string; productoId?:number; inventarioId?:number; vista?:string; modulo?:string }
const Db=()=>BaseDatos_obtenerCliente();
const Reportes_periodo=(C:ConsultaReporte,StrCampo:string)=>C.fechaDesde||C.fechaHastaExclusiva?{[StrCampo]:{...(C.fechaDesde?{gte:C.fechaDesde}:{}),...(C.fechaHastaExclusiva?{lt:C.fechaHastaExclusiva}:{})}}:{};

export async function Reportes_existencias(C:ConsultaReporte){
 const where={...(C.productoId?{productoId:C.productoId}:{}),...(C.inventarioId?{existencia:{inventarioId:C.inventarioId}}:{}),...(C.estado==="CERO"?{}:{existenciaActual:{gt:0}})};
 const [datos,total]=await Db().$transaction([Db().inventarioExistenciaLote.findMany({where,include:{existencia:{include:{almacen:true,producto:true}},lote:{include:{proveedor:true}}},orderBy:[{existencia:{producto:{nombre:"asc"}}},{existencia:{almacen:{nombre:"asc"}}},{lote:{codigoLote:"asc"}}],skip:(C.pagina-1)*C.limite,take:C.limite}),Db().inventarioExistenciaLote.count({where})]);return{datos,total};
}
export async function Reportes_movimientos(C:ConsultaReporte){const where={...Reportes_periodo(C,"fechaTransaccion"),...(C.productoId?{existencia:{productoId:C.productoId}}:{}),...(C.inventarioId?{existencia:{inventarioId:C.inventarioId}}:{}),...(C.vista==="MERMAS_BAJAS"?{subtipoTransaccion:{in:["MERMA","DISPOSICION"]}}:{}),...(C.estado?C.estado==="REVERSION"?{transaccionRevertidaId:{not:null}}:C.estado==="REVERTIDO"?{reversion:{isNot:null}}:{reversion:null,transaccionRevertidaId:null}:{})};const [datos,total]=await Db().$transaction([Db().inventarioTransaccion.findMany({where,include:{existencia:{include:{producto:true,almacen:true}},existenciaLote:{include:{lote:true}},reversion:true},orderBy:[{fechaTransaccion:"desc"},{transaccionInventarioId:"desc"}],skip:(C.pagina-1)*C.limite,take:C.limite}),Db().inventarioTransaccion.count({where})]);return{datos,total};}
export async function Reportes_censo(C:ConsultaReporte){const where={estadoActual:C.estado||"ACTIVO"};const [datos,total]=await Db().$transaction([Db().produccionAnimal.findMany({where,include:{tipoAnimal:true,raza:true,asignaciones:{where:{estado:"VIGENTE"},include:{lote:true}}},orderBy:{identificacion:"asc"},skip:(C.pagina-1)*C.limite,take:C.limite}),Db().produccionAnimal.count({where})]);return{datos,total};}
export async function Reportes_actividad(C:ConsultaReporte){const where={...Reportes_periodo(C,"fechaOperacion")};const [datos,total]=await Db().$transaction([Db().produccionOperacion.findMany({where,include:{lote:true,animales:{include:{animal:true}},reversion:true},orderBy:[{fechaOperacion:"desc"},{operacionProduccionId:"desc"}],skip:(C.pagina-1)*C.limite,take:C.limite}),Db().produccionOperacion.count({where})]);return{datos,total};}
export async function Reportes_mediciones(C:ConsultaReporte){const where={...Reportes_periodo(C,"fechaMedicion")};const [datos,total]=await Db().$transaction([Db().produccionMedicion.findMany({where,include:{animal:true,lote:true},orderBy:[{fechaMedicion:"desc"},{medicionId:"desc"}],skip:(C.pagina-1)*C.limite,take:C.limite}),Db().produccionMedicion.count({where})]);return{datos,total};}
export async function Reportes_sanidad(C:ConsultaReporte){const where={...Reportes_periodo(C,"fechaAplicacion"),...(C.estado?{estado:C.estado}:{})};const include={animal:true,lote:true,tipoAplicacion:true,detalles:{include:{producto:true,unidadDosis:true,viaAdministracion:true,fuentes:{include:{existenciaLote:{include:{lote:true}},inventarioTransacciones:{where:{transaccionRevertidaId:null}}}}}}} satisfies Prisma.SanidadAplicacionInclude;const [datos,total]=await Db().$transaction([Db().sanidadAplicacion.findMany({where,include,orderBy:[{fechaAplicacion:"desc"},{aplicacionSanitariaId:"desc"}],skip:(C.pagina-1)*C.limite,take:C.limite}),Db().sanidadAplicacion.count({where})]);return{datos,total};}
export async function Reportes_ventas(C:ConsultaReporte){const where={...Reportes_periodo(C,"fechaVenta"),...(C.estado?{estado:C.estado}:{})};const [datos,total]=await Db().$transaction([Db().ventaRegistro.findMany({where,include:{recibo:true,detalles:{include:{lote:true,animales:{include:{animal:true}}}}},orderBy:[{fechaVenta:"desc"},{ventaId:"desc"}],skip:(C.pagina-1)*C.limite,take:C.limite}),Db().ventaRegistro.count({where})]);return{datos,total};}
export async function Reportes_costos(C:ConsultaReporte){if(C.modulo==="SANIDAD")return Reportes_sanidad(C);const where={...Reportes_periodo(C,"fechaAlimentacion"),...(C.estado?{estado:C.estado}:{})};const [datos,total]=await Db().$transaction([Db().alimentacionRegistro.findMany({where,include:{animal:true,lote:true,detalles:{include:{producto:true,existenciaLote:{include:{lote:true}},inventarioTransacciones:{where:{transaccionRevertidaId:null}}}}},orderBy:[{fechaAlimentacion:"desc"},{alimentacionId:"desc"}],skip:(C.pagina-1)*C.limite,take:C.limite}),Db().alimentacionRegistro.count({where})]);return{datos,total};}
export async function Reportes_filtros(){const [productos,almacenes,lotes,tipos,clientes]=await Promise.all([Db().inventarioProducto.findMany({select:{productoId:true,codigo:true,nombre:true,activo:true},orderBy:{nombre:"asc"}}),Db().inventarioAlmacen.findMany({select:{inventarioId:true,codigo:true,nombre:true,activo:true},orderBy:{nombre:"asc"}}),Db().produccionLote.findMany({select:{loteProduccionId:true,codigo:true,nombre:true,estado:true},orderBy:{nombre:"asc"}}),Db().sanidadTipoAplicacion.findMany({select:{tipoAplicacionId:true,codigo:true,nombre:true,activo:true},orderBy:{nombre:"asc"}}),Db().clienteRegistro.findMany({select:{clienteId:true,codigo:true,nombreCompleto:true,activo:true},orderBy:{nombreCompleto:"asc"}})]);return{productos,almacenes,lotes,tipos,clientes};}
