import { Prisma } from "../../../generated/prisma/client.js";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import { Fecha_convertirAlmacenamientoGuatemalaAInstante,Fecha_convertirInstanteAAlmacenamientoGuatemala,Fecha_formatearInstanteGuatemala,Fecha_obtenerInstanteActual,Fecha_parsearFechaHoraGuatemala } from "../../datetime/fecha.js";
import * as R from "./ventas.repository.js";
const ObjErrores:Record<string,[number,string]>={CLIENTE_NO_ENCONTRADO:[404,"El cliente no existe."],CLIENTE_INACTIVO:[409,"El cliente está inactivo."],ANIMAL_NO_ENCONTRADO:[404,"El animal no existe."],ANIMAL_NO_ACTIVO:[409,"El animal no está activo."],ANIMAL_SIN_ASIGNACION_VIGENTE:[409,"El animal no tiene asignación vigente."],LOTE_INACTIVO:[409,"El lote de origen está inactivo."],LOTE_ORIGEN_INACTIVO:[409,"Debe reabrir el lote original antes de revertir."],ANIMAL_DUPLICADO_EN_VENTA:[400,"Un animal está repetido en la venta."],FECHA_VENTA_ANTERIOR_ASIGNACION:[409,"La fecha de venta es anterior a la asignación vigente."],ACTIVIDAD_POSTERIOR_INCOMPATIBLE:[409,"Existe actividad posterior incompatible con la fecha de venta."],CONFLICTO_CONCURRENCIA:[409,"Uno de los animales fue modificado por otra operación."],VENTA_INCONSISTENTE:[409,"La venta no pudo relacionarse coherentemente con Producción."],VENTA_NO_ENCONTRADA:[404,"La venta no existe."],VENTA_YA_ANULADA:[409,"La venta ya fue anulada."],REVERSION_VENTA_NO_PERMITIDA:[409,"La venta no puede revertirse por dependencias posteriores."],OPERACION_NO_ENCONTRADA:[409,"La operación de Producción no existe."],OPERACION_YA_REVERTIDA:[409,"La operación ya fue revertida."]};
function Ventas_mapearError(ObjError:unknown):never{if(ObjError instanceof ErrorAplicacion)throw ObjError;const StrCodigo=ObjError instanceof Error?ObjError.message:"ERROR_INTERNO";if(ObjErrores[StrCodigo]){const[IntEstado,StrMensaje]=ObjErrores[StrCodigo]!;throw new ErrorAplicacion(IntEstado,StrCodigo,StrMensaje);}if(ObjError instanceof Prisma.PrismaClientKnownRequestError){if(ObjError.code==="P2002")throw new ErrorAplicacion(409,"CONFLICTO_CONCURRENCIA","La venta entra en conflicto con otra operación.");if(ObjError.code==="P2025")throw new ErrorAplicacion(404,"REGISTRO_NO_ENCONTRADO","El registro ya no existe.");}throw ObjError;}
export function Ventas_formatearRespuesta<T>(ObjValor:T):T{if(ObjValor instanceof Date)return Fecha_formatearInstanteGuatemala(Fecha_convertirAlmacenamientoGuatemalaAInstante(ObjValor)) as T;if(Array.isArray(ObjValor))return ObjValor.map(Ventas_formatearRespuesta) as T;if(ObjValor!==null&&typeof ObjValor==="object"&&!(ObjValor instanceof Prisma.Decimal))return Object.fromEntries(Object.entries(ObjValor).map(([StrClave,ObjDato])=>[StrClave,Ventas_formatearRespuesta(ObjDato)])) as T;return ObjValor;}
export const Ventas_listar=R.Ventas_listar;export const Ventas_obtener=R.Ventas_obtener;export const Ventas_buscarClientes=R.Ventas_buscarClientes;export const Ventas_buscarLotes=R.Ventas_buscarLotes;export const Ventas_buscarAnimales=R.Ventas_buscarAnimales;
export async function Ventas_registrar(ObjDatos:{clienteId:number;fechaVenta:string;formaPago:"EFECTIVO"|"TRANSFERENCIA"|"DEPOSITO"|"CREDITO";documentoReferencia?:string|null|undefined;observaciones?:string|null|undefined;animales:Array<{animalId:number;precioVenta:string}>;IntUsuarioId:number;StrIp?:string|undefined}){const DtInstante=Fecha_parsearFechaHoraGuatemala(ObjDatos.fechaVenta);if(DtInstante>Fecha_obtenerInstanteActual())throw new ErrorAplicacion(400,"FECHA_VENTA_FUTURA","La fecha de venta no puede ser futura.");try{return await R.Ventas_registrar({...ObjDatos,fechaVenta:Fecha_convertirInstanteAAlmacenamientoGuatemala(DtInstante),animales:ObjDatos.animales.map(ObjAnimal=>({...ObjAnimal,precioVenta:new Prisma.Decimal(ObjAnimal.precioVenta)}))});}catch(ObjError){Ventas_mapearError(ObjError);}}
export async function Ventas_revertir(IntVentaId:number,StrMotivo:string,IntUsuarioId:number,StrIp?:string){try{return await R.Ventas_revertir(IntVentaId,StrMotivo,IntUsuarioId,StrIp);}catch(ObjError){Ventas_mapearError(ObjError);}}
export const Ventas_diagnosticar=R.Ventas_diagnosticar;
