import { useCallback, useEffect, useState } from "react";
import { useSesion } from "./useSesion";
import * as ObjServicio from "../services/clientes.service";
import { ErrorApi } from "../types/api.types";
import type { CambiosCliente, Cliente, ConsultaClientes, DatosCliente, TipoCliente } from "../types/clientes.types";

const IntLimiteClientes = 20;
function Clientes_mensajeError(ObjError: unknown): string { if (!(ObjError instanceof ErrorApi)) return "No fue posible completar la operacion."; const ObjMensajes: Record<string,string> = { PERMISO_INSUFICIENTE:"No tiene permiso para realizar esta operacion.", CLIENTE_NO_ENCONTRADO:"El cliente ya no existe.", TIPO_CLIENTE_NO_ENCONTRADO:"El tipo seleccionado ya no existe.", TIPO_CLIENTE_INACTIVO:"El tipo seleccionado esta inactivo.", NIT_DUPLICADO:"El NIT ya esta registrado.", DOCUMENTO_DUPLICADO:"El documento ya esta registrado.", CODIGO_DUPLICADO:"No fue posible asignar un codigo unico.", ERROR_RED:"No fue posible comunicarse con el servidor." }; return ObjMensajes[ObjError.StrCodigo] ?? "No fue posible completar la operacion."; }
export function useClientes() {
  const { Autenticacion_manejarErrorProtegido } = useSesion();
  const [ArrClientes, establecerClientes] = useState<Cliente[]>([]); const [ArrTipos, establecerTipos] = useState<TipoCliente[]>([]); const [IntTotal, establecerTotal] = useState(0); const [IntPagina, establecerPagina] = useState(1); const [ObjFiltros, establecerFiltros] = useState<Omit<ConsultaClientes,"pagina"|"limite">>({}); const [BoolCargaInicial, establecerCargaInicial] = useState(true); const [BoolActualizando, establecerActualizando] = useState(false); const [StrError, establecerError] = useState<string|null>(null); const [StrExito, establecerExito] = useState<string|null>(null); const [StrOperacion, establecerOperacion] = useState<string|null>(null);
  const Clientes_cargar = useCallback(async (IntPaginaSolicitada=IntPagina) => { establecerError(null); if(BoolCargaInicial) establecerCargaInicial(true); else establecerActualizando(true); try { const ObjRespuesta=await ObjServicio.Clientes_listar({pagina:IntPaginaSolicitada,limite:IntLimiteClientes,...ObjFiltros}); const IntUltima=Math.max(1,Math.ceil(ObjRespuesta.paginacion.total/IntLimiteClientes)); if(IntPaginaSolicitada>IntUltima){establecerPagina(IntUltima);return;} establecerClientes(ObjRespuesta.datos); establecerTotal(ObjRespuesta.paginacion.total); } catch(ObjError){if(!Autenticacion_manejarErrorProtegido(ObjError)) establecerError(Clientes_mensajeError(ObjError));} finally {establecerCargaInicial(false);establecerActualizando(false);} },[IntPagina,ObjFiltros,BoolCargaInicial,Autenticacion_manejarErrorProtegido]);
  useEffect(()=>{void Clientes_cargar(IntPagina);},[IntPagina,ObjFiltros]);
  useEffect(()=>{void ObjServicio.Clientes_obtenerTipos().then((ObjRespuesta)=>establecerTipos(ObjRespuesta.datos)).catch((ObjError)=>{if(!Autenticacion_manejarErrorProtegido(ObjError)) establecerError(Clientes_mensajeError(ObjError));});},[Autenticacion_manejarErrorProtegido]);
  const Clientes_ejecutar=useCallback(async<T,>(StrClave:string,ObjAccion:()=>Promise<T>,Clientes_mensaje:(ObjResultado:T)=>string)=>{establecerOperacion(StrClave);establecerError(null);establecerExito(null);try{const ObjResultado=await ObjAccion();establecerExito(Clientes_mensaje(ObjResultado));await Clientes_cargar(IntPagina);return ObjResultado;}catch(ObjError){if(!Autenticacion_manejarErrorProtegido(ObjError)) establecerError(Clientes_mensajeError(ObjError));throw ObjError;}finally{establecerOperacion(null);}},[Autenticacion_manejarErrorProtegido,Clientes_cargar,IntPagina]);
  return { ArrClientes,ArrTipos,ArrTiposActivos:ArrTipos.filter((ObjTipo)=>ObjTipo.activo),IntTotal,IntPagina,IntLimite:IntLimiteClientes,BoolCargaInicial,BoolActualizando,StrError,StrExito,StrOperacion,establecerPagina,Clientes_aplicarFiltros:(ObjNuevos:Omit<ConsultaClientes,"pagina"|"limite">)=>{establecerPagina(1);establecerFiltros(ObjNuevos);},Clientes_crear:(ObjDatos:DatosCliente)=>Clientes_ejecutar("crear",()=>ObjServicio.Clientes_crear(ObjDatos),(ObjRespuesta)=>`Cliente ${ObjRespuesta.datos.codigo} creado correctamente.`),Clientes_editar:(IntId:number,ObjDatos:CambiosCliente)=>Clientes_ejecutar(`editar-${IntId}`,()=>ObjServicio.Clientes_editar(IntId,ObjDatos),()=>"Cliente actualizado correctamente."),Clientes_cambiarEstado:(IntId:number,BoolActivo:boolean)=>Clientes_ejecutar(`estado-${IntId}`,()=>ObjServicio.Clientes_cambiarEstado(IntId,BoolActivo),()=>"Estado del cliente actualizado correctamente.") };
}
