import { useCallback, useEffect, useState } from "react";
import { useSesion } from "./useSesion";
import { ErrorApi } from "../types/api.types";
import type { RespuestaLista } from "../types/inventario.types";

export const IntLimiteInventario = 20;
export function Inventario_mensajeError(ObjError: unknown): string {
  if (!(ObjError instanceof ErrorApi)) return "No fue posible completar la operación.";
  const ObjMensajes: Record<string, string> = {
    VALIDACION_INVALIDA: "Revise los datos ingresados.", PERMISO_INSUFICIENTE: "No tiene permiso para realizar esta operación.", CATEGORIA_NO_ENCONTRADA: "La categoría ya no existe.", CATEGORIA_INACTIVA: "La categoría seleccionada está inactiva.", CATEGORIA_DUPLICADA: "Ya existe una categoría con ese nombre.", ALMACEN_NO_ENCONTRADO: "El almacén ya no existe.", ALMACEN_INACTIVO: "El almacén está inactivo.", CODIGO_ALMACEN_DUPLICADO: "El código del almacén ya está registrado.", PRODUCTO_NO_ENCONTRADO: "El producto ya no existe.", PRODUCTO_INACTIVO: "El producto está inactivo.", CODIGO_PRODUCTO_DUPLICADO: "El código del producto ya está registrado.", MANEJO_LOTES_NO_MODIFICABLE: "El manejo de lotes no puede cambiarse porque el producto ya tiene actividad.", LOTE_REQUERIDO: "Debe seleccionar o registrar un lote.", LOTE_NO_ENCONTRADO: "El lote ya no existe.", LOTE_DUPLICADO: "Ese código de lote ya existe para el producto.", LOTE_INACTIVO: "El lote está inactivo.", LOTE_VENCIDO: "El lote está vencido para esta operación.", COSTO_LOTE_DIFERENTE: "El costo no coincide con el costo único del lote.", EXISTENCIA_NO_ENCONTRADA: "La existencia ya no está disponible.", STOCK_INSUFICIENTE: "No hay existencia suficiente para completar la operación.", PROVEEDOR_NO_ENCONTRADO: "El proveedor ya no existe.", PROVEEDOR_INACTIVO: "El proveedor está inactivo.", PROVEEDOR_PRODUCTO_NO_ENCONTRADO: "El proveedor no ofrece este producto.", PROVEEDOR_PRODUCTO_INACTIVO: "La relación proveedor-producto está inactiva.", PROVEEDOR_LOTE_NO_COINCIDE: "El proveedor no corresponde al lote seleccionado.", SUBTIPO_NO_PERMITIDO: "La operación seleccionada no está permitida.", ALMACEN_DESTINO_INVALIDO: "El almacén de destino debe ser diferente al origen.", MOVIMIENTO_NO_ENCONTRADO: "El movimiento ya no existe.", MOVIMIENTO_YA_REVERTIDO: "El movimiento ya fue revertido.", REVERSION_NO_PERMITIDA: "Este movimiento no puede revertirse.", REVERSION_TRANSFERENCIA_REQUIERE_ENDPOINT: "La transferencia debe revertirse como una operación completa.", TRANSFERENCIA_NO_ENCONTRADA: "La transferencia ya no existe.", TRANSFERENCIA_YA_REVERTIDA: "La transferencia ya fue revertida.", TRANSFERENCIA_INCONSISTENTE: "La transferencia no contiene movimientos coherentes.", ERROR_RED: "No fue posible comunicarse con el servidor.",
  };
  return ObjMensajes[ObjError.StrCodigo] ?? ObjError.message ?? "No fue posible completar la operación.";
}
export function useInventarioLista<TDato, TFiltros extends object>(Inventario_solicitar: (ObjConsulta: TFiltros & { pagina: number; limite: number }) => Promise<RespuestaLista<TDato>>, ObjFiltrosIniciales: TFiltros) {
  const { Autenticacion_manejarErrorProtegido } = useSesion();
  const [ArrDatos, establecerDatos] = useState<TDato[]>([]); const [IntTotal, establecerTotal] = useState(0); const [IntPagina, establecerPagina] = useState(1); const [ObjFiltros, establecerFiltros] = useState<TFiltros>(ObjFiltrosIniciales); const [BoolCargando, establecerCargando] = useState(true); const [BoolActualizando, establecerActualizando] = useState(false); const [StrError, establecerError] = useState<string | null>(null);
  const Inventario_cargar = useCallback(async (IntPaginaSolicitada = IntPagina) => { BoolCargando ? establecerCargando(true) : establecerActualizando(true); establecerError(null); try { const ObjRespuesta = await Inventario_solicitar({ ...ObjFiltros, pagina: IntPaginaSolicitada, limite: IntLimiteInventario }); const IntUltima = Math.max(1, Math.ceil(ObjRespuesta.paginacion.total / IntLimiteInventario)); if (IntPaginaSolicitada > IntUltima) { establecerPagina(IntUltima); return; } establecerDatos(ObjRespuesta.datos); establecerTotal(ObjRespuesta.paginacion.total); } catch (ObjError) { if (!Autenticacion_manejarErrorProtegido(ObjError)) establecerError(Inventario_mensajeError(ObjError)); } finally { establecerCargando(false); establecerActualizando(false); } }, [Inventario_solicitar, ObjFiltros, IntPagina, BoolCargando, Autenticacion_manejarErrorProtegido]);
  useEffect(() => { void Inventario_cargar(IntPagina); }, [IntPagina, ObjFiltros]);
  return { ArrDatos, IntTotal, IntPagina, IntLimite: IntLimiteInventario, BoolCargando, BoolActualizando, StrError, establecerPagina, Inventario_aplicarFiltros: (ObjNuevos: TFiltros) => { establecerPagina(1); establecerFiltros(ObjNuevos); }, Inventario_recargar: () => Inventario_cargar(IntPagina) };
}
