import { useCallback, useEffect, useState } from "react";
import { useSesion } from "./useSesion";
import * as ObjServicio from "../services/proveedores.service";
import { ErrorApi } from "../types/api.types";
import type { CambiosProveedor, ConsultaProveedores, DatosProveedor, Proveedor, TipoProveedor } from "../types/proveedores.types";
const IntLimiteProveedores=20;
function Proveedores_mensajeError(ObjError:unknown):string{if(!(ObjError instanceof ErrorApi))return"No fue posible completar la operacion.";const ObjMensajes:Record<string,string>={PERMISO_INSUFICIENTE:"No tiene permiso para realizar esta operacion.",PROVEEDOR_NO_ENCONTRADO:"El proveedor ya no existe.",TIPO_PROVEEDOR_NO_ENCONTRADO:"El tipo seleccionado ya no existe.",TIPO_PROVEEDOR_INACTIVO:"El tipo seleccionado esta inactivo.",NIT_DUPLICADO:"El NIT ya esta registrado.",DOCUMENTO_DUPLICADO:"El documento ya esta registrado.",CODIGO_DUPLICADO:"No fue posible asignar un codigo unico.",ERROR_RED:"No fue posible comunicarse con el servidor."};return ObjMensajes[ObjError.StrCodigo]??"No fue posible completar la operacion.";}
export function useProveedores(){const{Autenticacion_manejarErrorProtegido}=useSesion();const[ArrProveedores,establecerProveedores]=useState<Proveedor[]>([]);const[ArrTipos,establecerTipos]=useState<TipoProveedor[]>([]);const[IntTotal,establecerTotal]=useState(0);const[IntPagina,establecerPagina]=useState(1);const[ObjFiltros,establecerFiltros]=useState<Omit<ConsultaProveedores,"pagina"|"limite">>({});const[BoolCargaInicial,establecerCargaInicial]=useState(true);const[BoolActualizando,establecerActualizando]=useState(false);const[StrError,establecerError]=useState<string|null>(null);const[StrExito,establecerExito]=useState<string|null>(null);const[StrOperacion,establecerOperacion]=useState<string|null>(null);
const Proveedores_cargar=useCallback(async(IntPaginaSolicitada=IntPagina)=>{establecerError(null);if(BoolCargaInicial)establecerCargaInicial(true);else establecerActualizando(true);try{const ObjRespuesta=await ObjServicio.Proveedores_listar({pagina:IntPaginaSolicitada,limite:IntLimiteProveedores,...ObjFiltros});const IntUltima=Math.max(1,Math.ceil(ObjRespuesta.paginacion.total/IntLimiteProveedores));if(IntPaginaSolicitada>IntUltima){establecerPagina(IntUltima);return;}establecerProveedores(ObjRespuesta.datos);establecerTotal(ObjRespuesta.paginacion.total);}catch(ObjError){if(!Autenticacion_manejarErrorProtegido(ObjError))establecerError(Proveedores_mensajeError(ObjError));}finally{establecerCargaInicial(false);establecerActualizando(false);}},[IntPagina,ObjFiltros,BoolCargaInicial,Autenticacion_manejarErrorProtegido]);useEffect(()=>{void Proveedores_cargar(IntPagina);},[IntPagina,ObjFiltros]);useEffect(()=>{void ObjServicio.Proveedores_obtenerTipos().then((ObjRespuesta)=>establecerTipos(ObjRespuesta.datos)).catch((ObjError)=>{if(!Autenticacion_manejarErrorProtegido(ObjError))establecerError(Proveedores_mensajeError(ObjError));});},[Autenticacion_manejarErrorProtegido]);
const Proveedores_ejecutar=useCallback(async<T,>(StrClave:string,ObjAccion:()=>Promise<T>,Proveedores_mensaje:(ObjResultado:T)=>string)=>{establecerOperacion(StrClave);establecerError(null);establecerExito(null);try{const ObjResultado=await ObjAccion();establecerExito(Proveedores_mensaje(ObjResultado));await Proveedores_cargar(IntPagina);return ObjResultado;}catch(ObjError){if(!Autenticacion_manejarErrorProtegido(ObjError))establecerError(Proveedores_mensajeError(ObjError));throw ObjError;}finally{establecerOperacion(null);}},[Autenticacion_manejarErrorProtegido,Proveedores_cargar,IntPagina]);return{ArrProveedores,ArrTipos,ArrTiposActivos:ArrTipos.filter((ObjTipo)=>ObjTipo.activo),IntTotal,IntPagina,IntLimite:IntLimiteProveedores,BoolCargaInicial,BoolActualizando,StrError,StrExito,StrOperacion,establecerPagina,Proveedores_aplicarFiltros:(ObjNuevos:Omit<ConsultaProveedores,"pagina"|"limite">)=>{establecerPagina(1);establecerFiltros(ObjNuevos);},Proveedores_crear:(ObjDatos:DatosProveedor)=>Proveedores_ejecutar("crear",()=>ObjServicio.Proveedores_crear(ObjDatos),(ObjRespuesta)=>`Proveedor ${ObjRespuesta.datos.codigo} creado correctamente.`),Proveedores_editar:(IntId:number,ObjDatos:CambiosProveedor)=>Proveedores_ejecutar(`editar-${IntId}`,()=>ObjServicio.Proveedores_editar(IntId,ObjDatos),()=>"Proveedor actualizado correctamente."),Proveedores_cambiarEstado:(IntId:number,BoolActivo:boolean)=>Proveedores_ejecutar(`estado-${IntId}`,()=>ObjServicio.Proveedores_cambiarEstado(IntId,BoolActivo),()=>"Estado del proveedor actualizado correctamente.")};}
