import { Prisma } from "../../../generated/prisma/client.js";
import { Fecha_convertirAlmacenamientoGuatemalaAInstante, Fecha_formatearInstanteGuatemala } from "../../datetime/fecha.js";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import { Proveedores_canonicalizarIdentificacion } from "./proveedores.constants.js";
import * as ObjRepositorio from "./proveedores.repository.js";

function Proveedores_formatear<T extends { fechaCreacion: Date; fechaActualizacion: Date }>(ObjProveedor: T) { return { ...ObjProveedor, fechaCreacion: Fecha_formatearInstanteGuatemala(Fecha_convertirAlmacenamientoGuatemalaAInstante(ObjProveedor.fechaCreacion)), fechaActualizacion: Fecha_formatearInstanteGuatemala(Fecha_convertirAlmacenamientoGuatemalaAInstante(ObjProveedor.fechaActualizacion)) }; }
function Proveedores_lanzarErrorPersistencia(ObjError: unknown): never { if (ObjError instanceof Prisma.PrismaClientKnownRequestError && ObjError.code === "P2002") { const StrDetalle = JSON.stringify(ObjError.meta ?? {}).toLowerCase() + ObjError.message.toLowerCase(); if (StrDetalle.includes("nit")) throw new ErrorAplicacion(409, "NIT_DUPLICADO", "El NIT ya esta registrado."); if (StrDetalle.includes("documento")) throw new ErrorAplicacion(409, "DOCUMENTO_DUPLICADO", "El documento ya esta registrado."); if (StrDetalle.includes("codigo")) throw new ErrorAplicacion(409, "CODIGO_DUPLICADO", "No fue posible asignar un codigo unico."); } throw ObjError; }
async function Proveedores_validarTipo(IntTipoProveedorId: number): Promise<void> { const ObjTipo = await ObjRepositorio.Proveedores_obtenerTipo(IntTipoProveedorId); if (ObjTipo === null) throw new ErrorAplicacion(404, "TIPO_PROVEEDOR_NO_ENCONTRADO", "El tipo de proveedor no existe."); if (!ObjTipo.activo) throw new ErrorAplicacion(409, "TIPO_PROVEEDOR_INACTIVO", "El tipo de proveedor esta inactivo."); }
export function Proveedores_validarCf(StrNit: string | null, StrDocumento: string | null): void { if (StrNit === "CF") throw new ErrorAplicacion(400, "VALIDACION_INVALIDA", "CF no es un NIT valido para proveedores."); if (StrDocumento === "CF") throw new ErrorAplicacion(400, "VALIDACION_INVALIDA", "CF no es un documento valido."); }
export async function Proveedores_listar(ObjConsulta: { IntPagina: number; IntLimite: number; StrBusqueda?: string | undefined; StrEstado?: "ACTIVO" | "INACTIVO" | undefined; IntTipoProveedorId?: number | undefined }) { const ObjResultado = await ObjRepositorio.Proveedores_listarRegistros({ IntPagina: ObjConsulta.IntPagina, IntLimite: ObjConsulta.IntLimite, StrBusqueda: ObjConsulta.StrBusqueda, BoolActivo: ObjConsulta.StrEstado === undefined ? undefined : ObjConsulta.StrEstado === "ACTIVO", IntTipoProveedorId: ObjConsulta.IntTipoProveedorId }); return { ArrProveedores: ObjResultado.ArrProveedores.map(Proveedores_formatear), IntTotal: ObjResultado.IntTotal }; }
export async function Proveedores_obtenerPorId(IntProveedorId: number) { const ObjProveedor = await ObjRepositorio.Proveedores_obtenerRegistro(IntProveedorId); if (ObjProveedor === null) throw new ErrorAplicacion(404, "PROVEEDOR_NO_ENCONTRADO", "El proveedor no existe."); return Proveedores_formatear(ObjProveedor); }
export function Proveedores_obtenerTipos() { return ObjRepositorio.Proveedores_listarTipos(); }
export async function Proveedores_crear(ObjDatos: { IntTipoProveedorId: number; StrNombre: string; StrNombreComercial?: string | null | undefined; StrNumeroDocumento?: string | null | undefined; StrNit?: string | null | undefined; StrTelefono?: string | null | undefined; StrCorreo?: string | null | undefined; StrDireccion?: string | null | undefined; StrObservaciones?: string | null | undefined; IntUsuarioActorId: number; StrDireccionIp?: string | undefined }) { await Proveedores_validarTipo(ObjDatos.IntTipoProveedorId); const StrNit = Proveedores_canonicalizarIdentificacion(ObjDatos.StrNit); const StrDocumento = Proveedores_canonicalizarIdentificacion(ObjDatos.StrNumeroDocumento); Proveedores_validarCf(StrNit, StrDocumento); try { return Proveedores_formatear(await ObjRepositorio.Proveedores_crearRegistro({ tipoProveedorId: ObjDatos.IntTipoProveedorId, nombre: ObjDatos.StrNombre, nombreComercial: ObjDatos.StrNombreComercial?.trim() || null, numeroDocumento: StrDocumento, nit: StrNit, telefono: ObjDatos.StrTelefono?.trim() || null, correo: ObjDatos.StrCorreo?.trim() || null, direccion: ObjDatos.StrDireccion?.trim() || null, observaciones: ObjDatos.StrObservaciones?.trim() || null, IntUsuarioActorId: ObjDatos.IntUsuarioActorId, StrDireccionIp: ObjDatos.StrDireccionIp })); } catch (ObjError) { Proveedores_lanzarErrorPersistencia(ObjError); } }
export async function Proveedores_editar(ObjDatos: { IntProveedorId: number; IntTipoProveedorId?: number | undefined; StrNombre?: string | undefined; StrNombreComercial?: string | null | undefined; StrNumeroDocumento?: string | null | undefined; StrNit?: string | null | undefined; StrTelefono?: string | null | undefined; StrCorreo?: string | null | undefined; StrDireccion?: string | null | undefined; StrObservaciones?: string | null | undefined; IntUsuarioActorId: number; StrDireccionIp?: string | undefined }) { await Proveedores_obtenerPorId(ObjDatos.IntProveedorId); if (ObjDatos.IntTipoProveedorId !== undefined) await Proveedores_validarTipo(ObjDatos.IntTipoProveedorId); const ObjActualizacion: Prisma.ProveedorRegistroUncheckedUpdateInput = {}; if (ObjDatos.IntTipoProveedorId !== undefined) ObjActualizacion.tipoProveedorId = ObjDatos.IntTipoProveedorId; if (ObjDatos.StrNombre !== undefined) ObjActualizacion.nombre = ObjDatos.StrNombre; if (ObjDatos.StrNombreComercial !== undefined) ObjActualizacion.nombreComercial = ObjDatos.StrNombreComercial?.trim() || null; if (ObjDatos.StrNumeroDocumento !== undefined) ObjActualizacion.numeroDocumento = Proveedores_canonicalizarIdentificacion(ObjDatos.StrNumeroDocumento); if (ObjDatos.StrNit !== undefined) ObjActualizacion.nit = Proveedores_canonicalizarIdentificacion(ObjDatos.StrNit); if (ObjDatos.StrTelefono !== undefined) ObjActualizacion.telefono = ObjDatos.StrTelefono?.trim() || null; if (ObjDatos.StrCorreo !== undefined) ObjActualizacion.correo = ObjDatos.StrCorreo?.trim() || null; if (ObjDatos.StrDireccion !== undefined) ObjActualizacion.direccion = ObjDatos.StrDireccion?.trim() || null; if (ObjDatos.StrObservaciones !== undefined) ObjActualizacion.observaciones = ObjDatos.StrObservaciones?.trim() || null; Proveedores_validarCf(typeof ObjActualizacion.nit === "string" ? ObjActualizacion.nit : null, typeof ObjActualizacion.numeroDocumento === "string" ? ObjActualizacion.numeroDocumento : null); try { return Proveedores_formatear(await ObjRepositorio.Proveedores_editarRegistro(ObjDatos.IntProveedorId, ObjActualizacion, ObjDatos.IntUsuarioActorId, ObjDatos.StrDireccionIp)); } catch (ObjError) { Proveedores_lanzarErrorPersistencia(ObjError); } }
export async function Proveedores_cambiarEstado(IntProveedorId: number, BoolActivo: boolean, IntUsuarioActorId: number, StrDireccionIp?: string) { await Proveedores_obtenerPorId(IntProveedorId); return Proveedores_formatear(await ObjRepositorio.Proveedores_cambiarEstadoRegistro(IntProveedorId, BoolActivo, IntUsuarioActorId, StrDireccionIp)); }
