import type { Prisma } from "../../../generated/prisma/client.js";
import { BaseDatos_obtenerCliente } from "../../database/prisma.js";
import { Fecha_obtenerAhoraGuatemala } from "../../datetime/fecha.js";

const ObjSeleccionProveedor = { proveedorId: true, tipoProveedorId: true, codigo: true, nombre: true, nombreComercial: true, numeroDocumento: true, nit: true, telefono: true, correo: true, direccion: true, observaciones: true, activo: true, fechaCreacion: true, fechaActualizacion: true, tipo: { select: { tipoProveedorId: true, codigo: true, nombre: true, activo: true } } } satisfies Prisma.ProveedorRegistroSelect;

export function Proveedores_listarRegistros(ObjConsulta: { IntPagina: number; IntLimite: number; StrBusqueda?: string | undefined; BoolActivo?: boolean | undefined; IntTipoProveedorId?: number | undefined }) {
  const ObjWhere: Prisma.ProveedorRegistroWhereInput = { ...(ObjConsulta.BoolActivo === undefined ? {} : { activo: ObjConsulta.BoolActivo }), ...(ObjConsulta.IntTipoProveedorId === undefined ? {} : { tipoProveedorId: ObjConsulta.IntTipoProveedorId }), ...(ObjConsulta.StrBusqueda === undefined || ObjConsulta.StrBusqueda.length === 0 ? {} : { OR: [{ codigo: { contains: ObjConsulta.StrBusqueda } }, { nombre: { contains: ObjConsulta.StrBusqueda } }, { nombreComercial: { contains: ObjConsulta.StrBusqueda } }, { nit: { contains: ObjConsulta.StrBusqueda } }, { numeroDocumento: { contains: ObjConsulta.StrBusqueda } }, { correo: { contains: ObjConsulta.StrBusqueda } }] }) };
  const ObjPrisma = BaseDatos_obtenerCliente();
  return ObjPrisma.$transaction(async (ObjTx) => ({ ArrProveedores: await ObjTx.proveedorRegistro.findMany({ where: ObjWhere, select: ObjSeleccionProveedor, orderBy: { proveedorId: "asc" }, skip: (ObjConsulta.IntPagina - 1) * ObjConsulta.IntLimite, take: ObjConsulta.IntLimite }), IntTotal: await ObjTx.proveedorRegistro.count({ where: ObjWhere }) }));
}
export function Proveedores_obtenerRegistro(IntProveedorId: number) { return BaseDatos_obtenerCliente().proveedorRegistro.findUnique({ where: { proveedorId: IntProveedorId }, select: ObjSeleccionProveedor }); }
export function Proveedores_obtenerTipo(IntTipoProveedorId: number) { return BaseDatos_obtenerCliente().proveedorTipo.findUnique({ where: { tipoProveedorId: IntTipoProveedorId } }); }
export function Proveedores_listarTipos() { return BaseDatos_obtenerCliente().proveedorTipo.findMany({ select: { tipoProveedorId: true, codigo: true, nombre: true, descripcion: true, activo: true }, orderBy: { tipoProveedorId: "asc" } }); }
async function Proveedores_registrarBitacora(ObjTx: Prisma.TransactionClient, IntActorId: number, StrAccion: string, IntProveedorId: number, StrCodigo: string, StrDireccionIp?: string): Promise<void> { await ObjTx.usuarioBitacora.create({ data: { usuarioId: IntActorId, modulo: "PROVEEDORES", accion: StrAccion, descripcion: `Proveedor ${IntProveedorId}; codigo ${StrCodigo}.`, resultado: "EXITO", direccionIp: StrDireccionIp ?? null } }); }
export function Proveedores_crearRegistro(ObjDatos: Prisma.ProveedorRegistroUncheckedCreateInput & { IntUsuarioActorId: number; StrDireccionIp?: string | undefined }) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjProveedor = await ObjTx.proveedorRegistro.create({ data: { tipoProveedorId: ObjDatos.tipoProveedorId, nombre: ObjDatos.nombre, nombreComercial: ObjDatos.nombreComercial ?? null, numeroDocumento: ObjDatos.numeroDocumento ?? null, nit: ObjDatos.nit ?? null, telefono: ObjDatos.telefono ?? null, correo: ObjDatos.correo ?? null, direccion: ObjDatos.direccion ?? null, observaciones: ObjDatos.observaciones ?? null }, select: ObjSeleccionProveedor }); await Proveedores_registrarBitacora(ObjTx, ObjDatos.IntUsuarioActorId, "PROVEEDOR_CREADO", ObjProveedor.proveedorId, ObjProveedor.codigo, ObjDatos.StrDireccionIp); return ObjProveedor; }); }
export function Proveedores_editarRegistro(IntProveedorId: number, ObjActualizacion: Prisma.ProveedorRegistroUncheckedUpdateInput, IntUsuarioActorId: number, StrDireccionIp?: string) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjProveedor = await ObjTx.proveedorRegistro.update({ where: { proveedorId: IntProveedorId }, data: { ...ObjActualizacion, fechaActualizacion: Fecha_obtenerAhoraGuatemala() }, select: ObjSeleccionProveedor }); await Proveedores_registrarBitacora(ObjTx, IntUsuarioActorId, "PROVEEDOR_EDITADO", ObjProveedor.proveedorId, ObjProveedor.codigo, StrDireccionIp); return ObjProveedor; }); }
export function Proveedores_cambiarEstadoRegistro(IntProveedorId: number, BoolActivo: boolean, IntUsuarioActorId: number, StrDireccionIp?: string) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjProveedor = await ObjTx.proveedorRegistro.update({ where: { proveedorId: IntProveedorId }, data: { activo: BoolActivo, fechaActualizacion: Fecha_obtenerAhoraGuatemala() }, select: ObjSeleccionProveedor }); await Proveedores_registrarBitacora(ObjTx, IntUsuarioActorId, "PROVEEDOR_ESTADO_CAMBIADO", ObjProveedor.proveedorId, ObjProveedor.codigo, StrDireccionIp); return ObjProveedor; }); }
