import type { Request, Response } from "express";
import type { ZodType } from "zod";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import * as ObjEsquemas from "./proveedores.schemas.js";
import * as ObjServicio from "./proveedores.service.js";
function Proveedores_validarEntrada<T>(ObjEsquema: ZodType<T>, ObjValor: unknown): T { const ObjResultado = ObjEsquema.safeParse(ObjValor); if (!ObjResultado.success) throw new ErrorAplicacion(400, "VALIDACION_INVALIDA", "Los datos proporcionados no son validos."); return ObjResultado.data; }
function Proveedores_obtenerActor(ObjSolicitud: Request) { if (ObjSolicitud.ObjAutenticacion === undefined) throw new ErrorAplicacion(401, "NO_AUTENTICADO", "Debe iniciar sesion."); return ObjSolicitud.ObjAutenticacion; }
export async function Proveedores_listar(ObjSolicitud: Request, ObjRespuesta: Response): Promise<void> { const ObjConsulta = Proveedores_validarEntrada(ObjEsquemas.ObjConsultaProveedores, ObjSolicitud.query); const ObjResultado = await ObjServicio.Proveedores_listar({ IntPagina: ObjConsulta.pagina, IntLimite: ObjConsulta.limite, StrBusqueda: ObjConsulta.busqueda, StrEstado: ObjConsulta.estado, IntTipoProveedorId: ObjConsulta.tipoProveedorId }); ObjRespuesta.json({ datos: ObjResultado.ArrProveedores, paginacion: { pagina: ObjConsulta.pagina, limite: ObjConsulta.limite, total: ObjResultado.IntTotal } }); }
export async function Proveedores_obtenerTipos(_ObjSolicitud: Request, ObjRespuesta: Response): Promise<void> { ObjRespuesta.json({ datos: await ObjServicio.Proveedores_obtenerTipos() }); }
export async function Proveedores_obtenerPorId(ObjSolicitud: Request, ObjRespuesta: Response): Promise<void> { const ObjParametro = Proveedores_validarEntrada(ObjEsquemas.ObjParametroProveedor, ObjSolicitud.params); ObjRespuesta.json({ datos: await ObjServicio.Proveedores_obtenerPorId(ObjParametro.proveedorId) }); }
export async function Proveedores_crear(ObjSolicitud: Request, ObjRespuesta: Response): Promise<void> { const ObjDatos = Proveedores_validarEntrada(ObjEsquemas.ObjCrearProveedor, ObjSolicitud.body); const ObjActor = Proveedores_obtenerActor(ObjSolicitud); ObjRespuesta.status(201).json({ datos: await ObjServicio.Proveedores_crear({ IntTipoProveedorId: ObjDatos.tipoProveedorId, StrNombre: ObjDatos.nombre, StrNombreComercial: ObjDatos.nombreComercial, StrNumeroDocumento: ObjDatos.numeroDocumento, StrNit: ObjDatos.nit, StrTelefono: ObjDatos.telefono, StrCorreo: ObjDatos.correo, StrDireccion: ObjDatos.direccion, StrObservaciones: ObjDatos.observaciones, IntUsuarioActorId: ObjActor.IntUsuarioId, StrDireccionIp: ObjSolicitud.ip }) }); }
export async function Proveedores_editar(ObjSolicitud: Request, ObjRespuesta: Response): Promise<void> { const ObjParametro = Proveedores_validarEntrada(ObjEsquemas.ObjParametroProveedor, ObjSolicitud.params); const ObjDatos = Proveedores_validarEntrada(ObjEsquemas.ObjEditarProveedor, ObjSolicitud.body); const ObjActor = Proveedores_obtenerActor(ObjSolicitud); ObjRespuesta.json({ datos: await ObjServicio.Proveedores_editar({ IntProveedorId: ObjParametro.proveedorId, IntTipoProveedorId: ObjDatos.tipoProveedorId, StrNombre: ObjDatos.nombre, StrNombreComercial: ObjDatos.nombreComercial, StrNumeroDocumento: ObjDatos.numeroDocumento, StrNit: ObjDatos.nit, StrTelefono: ObjDatos.telefono, StrCorreo: ObjDatos.correo, StrDireccion: ObjDatos.direccion, StrObservaciones: ObjDatos.observaciones, IntUsuarioActorId: ObjActor.IntUsuarioId, StrDireccionIp: ObjSolicitud.ip }) }); }
export async function Proveedores_cambiarEstado(ObjSolicitud: Request, ObjRespuesta: Response): Promise<void> { const ObjParametro = Proveedores_validarEntrada(ObjEsquemas.ObjParametroProveedor, ObjSolicitud.params); const ObjDatos = Proveedores_validarEntrada(ObjEsquemas.ObjCambiarEstadoProveedor, ObjSolicitud.body); const ObjActor = Proveedores_obtenerActor(ObjSolicitud); ObjRespuesta.json({ datos: await ObjServicio.Proveedores_cambiarEstado(ObjParametro.proveedorId, ObjDatos.activo, ObjActor.IntUsuarioId, ObjSolicitud.ip) }); }
