import { afterEach,describe,expect,it,vi } from "vitest";import * as S from "./produccion.service";
const respuesta=(Obj:unknown)=>new Response(JSON.stringify(Obj),{status:200,headers:{"content-type":"application/json"}});
afterEach(()=>vi.unstubAllGlobals());
describe("servicio Produccion",()=>{
it("usa filtros y endpoints canónicos reales",async()=>{const F=vi.fn().mockResolvedValue(respuesta({datos:[],paginacion:{pagina:1,limite:20,total:0}}));vi.stubGlobal("fetch",F);await S.Produccion_listarAnimales({pagina:1,limite:20,estado:"ACTIVO",loteProduccionId:3,sexo:"HEMBRA"});expect(F.mock.calls[0]?.[0]).toBe("/api/produccion/animales?pagina=1&limite=20&estado=ACTIVO&loteProduccionId=3&sexo=HEMBRA");expect((F.mock.calls[0]?.[1]as RequestInit).credentials).toBe("include")});
it("consulta el lookup reducido de proveedores por texto",async()=>{const F=vi.fn().mockResolvedValue(respuesta({datos:[],paginacion:{pagina:1,limite:10,total:0}}));vi.stubGlobal("fetch",F);await S.Produccion_listarProveedores({pagina:1,limite:10,busqueda:"PRO000001"});expect(F.mock.calls[0]?.[0]).toBe("/api/produccion/proveedores?pagina=1&limite=10&busqueda=PRO000001")});
it("separa ingreso inicial, nacimiento y compra",async()=>{const F=vi.fn().mockImplementation(()=>Promise.resolve(respuesta({datos:{}})));vi.stubGlobal("fetch",F);await S.Produccion_registrarInicial({loteDestinoId:1,animales:[]});await S.Produccion_registrarNacimiento({loteDestinoId:1,animales:[]});await S.Produccion_registrarCompra({proveedorId:2,loteDestinoId:1,animales:[]});expect(F.mock.calls.map(C=>C[0])).toEqual(["/api/produccion/ingresos/iniciales","/api/produccion/nacimientos","/api/produccion/compras"])});
it("preserva costo y medidas como strings sin enviar peso estimado",async()=>{const F=vi.fn().mockImplementation(()=>Promise.resolve(respuesta({datos:{}})));vi.stubGlobal("fetch",F);await S.Produccion_registrarCompra({proveedorId:1,loteDestinoId:2,animales:[{identificacion:"A1",tipoAnimalId:1,sexo:"MACHO",costoAdquisicion:"4750.25"}]});await S.Produccion_registrarMedicion({animalId:1,metodoObtencion:"ESTIMACION_SCHAEFFER",perimetroToracicoCm:"177.0000",longitudCorporalCm:"198.0000"});const C1=JSON.parse(String((F.mock.calls[0]?.[1]as RequestInit).body)),C2=JSON.parse(String((F.mock.calls[1]?.[1]as RequestInit).body));expect(C1.animales[0].costoAdquisicion).toBe("4750.25");expect(C2.perimetroToracicoCm).toBe("177.0000");expect(C2).not.toHaveProperty("pesoKg");expect(C2).not.toHaveProperty("valor")});
it("consulta ficha y fotografía mediante endpoints separados",async()=>{const F=vi.fn().mockResolvedValueOnce(respuesta({datos:{animalId:7,tieneFoto:true}})).mockResolvedValueOnce(new Response(new Blob(["foto"],{type:"image/webp"}),{status:200}));vi.stubGlobal("fetch",F);await S.Produccion_obtenerFichaTecnica(7);await S.Produccion_obtenerFoto(7);expect(F.mock.calls[0]?.[0]).toBe("/api/produccion/animales/7/ficha-tecnica");expect(F.mock.calls[1]?.[0]).toBe("/api/produccion/animales/7/foto");expect((F.mock.calls[1]?.[1]as RequestInit).credentials).toBe("include")});
it("interpreta foto 404 como ausencia y conserva POST multipart",async()=>{const F=vi.fn().mockResolvedValueOnce(new Response(null,{status:404})).mockResolvedValueOnce(new Response(null,{status:201}));vi.stubGlobal("fetch",F);expect(await S.Produccion_obtenerFoto(3)).toBeNull();await S.Produccion_reemplazarFoto(3,new File(["imagen"],"animal.png",{type:"image/png"}));expect(F.mock.calls[1]?.[0]).toBe("/api/produccion/animales/3/foto");const ObjOpciones=F.mock.calls[1]?.[1]as RequestInit;expect(ObjOpciones.method).toBe("POST");expect(ObjOpciones.body).toBeInstanceOf(FormData)});
it("no expone ningún método DELETE",()=>{expect(Object.keys(S).some(K=>K.toLowerCase().includes("eliminar"))).toBe(false)});
});
