export type DecimalProduccion = string;
export type SexoAnimal = "MACHO" | "HEMBRA" | "NO_DETERMINADO";
export type EstadoAnimal = "ACTIVO" | "VENDIDO" | "FALLECIDO" | "RETIRADO";
export interface RespuestaDato<T> { datos: T }
export interface RespuestaLista<T> { datos: T[]; paginacion: { pagina: number; limite: number; total: number } }
export interface ConsultaBase { pagina: number; limite: number; busqueda?: string; estado?: string }
export interface TipoAnimal { tipoAnimalId: number; nombre: string; descripcion: string | null; activo: boolean }
export interface RazaAnimal { razaId: number; tipoAnimalId: number; nombre: string; descripcion: string | null; activo: boolean; tipoAnimal?: { nombre: string } }
export interface ProveedorProduccion { proveedorId: number; codigo: string; nombre: string; nombreComercial: string | null; activo: boolean }
export interface LoteProduccion { loteProduccionId: number; tipoAnimalId: number; codigo: string; nombre: string; descripcion: string | null; fechaInicio: string; fechaCierre: string | null; estado: "ACTIVO" | "CERRADO"; tipoAnimal: { tipoAnimalId: number; nombre: string; activo: boolean }; _count?: { asignaciones: number }; asignaciones?: AsignacionLote[]; produccionTransacciones?: TransaccionProduccion[] }
export interface AsignacionLote { asignacionLoteId: number; animalId: number; loteProduccionId?: number; estado: "VIGENTE" | "FINALIZADA"; fechaInicio: string; fechaFin: string | null; animal?: { identificacion: string; sexo: SexoAnimal; estadoActual: EstadoAnimal }; lote?: { codigo: string; nombre: string; estado: string } }
export interface AnimalProduccion { animalId: number; tipoAnimalId: number; razaId: number | null; madreAnimalId: number | null; identificacion: string; sexo: SexoAnimal; fechaNacimiento: string | null; fechaIngreso: string; estadoActual: EstadoAnimal; observaciones: string | null; tipoAnimal: { tipoAnimalId: number; nombre: string; activo: boolean }; raza: { razaId: number; nombre: string; activo: boolean } | null; madre: { animalId: number; identificacion: string } | null; asignaciones: AsignacionLote[]; historialEstados?: HistorialEstado[]; mediciones?: MedicionProduccion[] }
export interface HistorialEstado { historialEstadoId: number; estadoAnterior: string | null; estadoNuevo: string; motivo: string | null; fechaCambio: string }
export interface MedicionProduccion { medicionId: number; animalId: number | null; tipoMedicion: "PESO"; valor: DecimalProduccion; unidadMedida: "KG"; fechaMedicion: string; observaciones: string | null; animal?: { identificacion: string } }
export interface AnimalIngreso { identificacion: string; tipoAnimalId: number; razaId?: number | null; sexo: SexoAnimal; fechaNacimiento?: string | null; madreAnimalId?: number | null; observaciones?: string | null }
export interface AnimalCompra extends AnimalIngreso { costoAdquisicion: DecimalProduccion }
export interface OperacionProduccion { operacionProduccionId: number; tipoOperacion: string; subtipoOperacion: string; loteProduccionId: number | null; operacionRevertidaId: number | null; documentoReferencia: string | null; motivo: string | null; observaciones: string | null; fechaOperacion: string; lote: { codigo: string; nombre: string } | null; proveedor: { codigo: string; nombre: string; nombreComercial: string | null } | null; usuario: { usuarioId: number; nombreCompleto: string }; animales: Array<{ animalId: number; costoAdquisicion: DecimalProduccion | null; animal: { animalId: number; identificacion: string } }>; transacciones: TransaccionProduccion[]; reversion: { operacionProduccionId: number } | null }
export interface TransaccionProduccion { transaccionProduccionId: number; operacionProduccionId: number; loteProduccionId: number; tipoTransaccion: string; cantidad: number; documentoReferencia: string | null; motivo: string | null; observaciones: string | null; fechaTransaccion: string; lote?: { codigo: string; nombre: string }; usuario?: { usuarioId: number; nombreCompleto: string }; operacion?: { tipoOperacion: string; subtipoOperacion: string } }
export interface DiagnosticoProduccion { consistente: boolean; lotesRevisados: number; totalDiferencias: number; activosSinAsignacion: number; terminalesConAsignacion: number; diferenciasLotes: Array<{ loteProduccionId: number; saldo: number; vigentes: number }> }
export interface FichaAsignacionLote { asignacionLoteId:number; fechaInicio:string; fechaFin:string|null; estado:"VIGENTE"|"FINALIZADA"; motivoCambio:string|null; lote:{loteProduccionId:number;codigo:string;nombre:string;estado:string} }
export interface FichaMedicion { medicionId:number; tipoMedicion:string; valor:DecimalProduccion; unidadMedida:string; fechaMedicion:string; observaciones:string|null }
export interface FichaDetalleSanidad { producto:string; via:string; dosisClinica?:DecimalProduccion; dosisIndicadaPorAnimal?:DecimalProduccion; unidadClinica?:string }
export interface FichaAplicacionSanidad { aplicacionSanitariaId:number; alcance:"ANIMAL"|"LOTE"; etiquetaAlcance:string; fecha:string; tipo:string; motivo:string; diagnostico:string|null; observaciones:string|null; lote:{codigo:string;nombre:string}|null; detalles:FichaDetalleSanidad[] }
export interface FichaHistorialEstado { historialEstadoId:number; estadoAnterior:string|null; estadoNuevo:string; motivo:string|null; fechaCambio:string }
export interface FichaEventoTrazabilidad { tipo:string; fecha:string; descripcion:string }
export interface FichaTecnicaAnimal { animalId:number; identificacion:string; tipo:string; raza:string|null; sexo:SexoAnimal; fechaNacimiento:string|null; fechaIngreso:string; estadoActual:EstadoAnimal; observaciones:string|null; madre:string|null; tieneFoto:boolean; origen:{tipo:"INICIAL"|"NACIMIENTO"|"COMPRA";fecha:string}|null; loteActual:{loteProduccionId:number;codigo:string;nombre:string;estado:string}|null; asignaciones:FichaAsignacionLote[]; mediciones:FichaMedicion[]; sanidad:FichaAplicacionSanidad[]; historialEstados:FichaHistorialEstado[]; salida:{estado:"VENDIDO"|"FALLECIDO"|"RETIRADO";fecha:string}|null; trazabilidad:FichaEventoTrazabilidad[] }
