export type DecimalSanidad=string;
export interface RespuestaDato<T>{ok:boolean;datos:T}
export interface RespuestaLista<T>{ok:boolean;datos:T[];paginacion:{pagina:number;limite:number;total:number}}
export interface CatalogoSanidad{tipoAplicacionId?:number;viaAdministracionId?:number;unidadDosisId?:number;codigo:string;nombre:string;descripcion:string|null;activo:boolean}
export interface ProductoSanidad{productoId:number;codigo:string;nombre:string;unidadMedida:string;manejaLotes:boolean;activo:boolean;habilitacionSanidad:{activo:boolean}|null}
export interface DestinoAnimalSanidad{animalId:number;identificacion:string;sexo:string;tipoAnimal:{tipoAnimalId:number;nombre:string};asignaciones:Array<{lote:{loteProduccionId:number;codigo:string;nombre:string}}>;}
export interface DestinoLoteSanidad{loteProduccionId:number;codigo:string;nombre:string;tipoAnimal:{tipoAnimalId:number;nombre:string};_count:{asignaciones:number}}
export interface AlmacenSanidad{inventarioId:number;codigo:string;nombre:string}
export interface ExistenciaSanidad{inventarioId:number;productoId:number;existenciaActual:DecimalSanidad;producto:{unidadMedida:string};almacen:{codigo:string;nombre:string}}
export interface LoteFuenteSanidad{loteInventarioId:number;existenciaActual:DecimalSanidad;lote:{codigoLote:string;fechaVencimiento:string|null;costoUnitario:DecimalSanidad|null;activo:boolean}}
export interface FuenteSanidad{fuenteSanidadId:number;cantidadConsumida:DecimalSanidad;existencia:{almacen:AlmacenSanidad}|null;existenciaLote:{lote:{codigoLote:string;fechaVencimiento:string|null;costoUnitario:DecimalSanidad|null};existencia:{almacen:AlmacenSanidad}}|null;inventarioTransacciones:Array<{costoUnitario:DecimalSanidad|null}>}
export interface DetalleSanidad{detalleSanidadId:number;dosisClinica:DecimalSanidad;alcanceDosis:"INDIVIDUAL"|"POR_ANIMAL"|"TOTAL_LOTE";unidadInventario:string;producto:ProductoSanidad;unidadDosis:CatalogoSanidad;viaAdministracion:CatalogoSanidad;fuentes:FuenteSanidad[]}
export interface AplicacionSanidad{aplicacionSanitariaId:number;fechaAplicacion:string;proximaAplicacion:string|null;motivo:string;diagnostico:string|null;observaciones:string|null;estado:"CONFIRMADA"|"REVERTIDA";animal:{animalId:number;identificacion:string}|null;lote:{loteProduccionId:number;codigo:string;nombre:string}|null;tipoAplicacion:CatalogoSanidad;usuario:{usuarioId:number;nombreCompleto:string};detalles:DetalleSanidad[]}
export interface ConsultaSanidad{pagina:number;limite:number;busqueda?:string;estado?:"CONFIRMADA"|"REVERTIDA";destino?:"ANIMAL"|"LOTE";tipoAplicacionId?:number;fechaDesde?:string;fechaHasta?:string}
export interface FuenteRegistroSanidad{inventarioId:number;loteInventarioId:number;cantidad:string}
export interface DetalleRegistroSanidad{productoId:number;dosisClinica:string;unidadDosisId:number;viaAdministracionId:number;alcanceDosis:"INDIVIDUAL"|"POR_ANIMAL"|"TOTAL_LOTE";fuentes:FuenteRegistroSanidad[]}
export interface DatosRegistroSanidad{tipoAplicacionId:number;fechaAplicacion:string;proximaAplicacion?:string|null;destino:{tipo:"ANIMAL";animalId:number}|{tipo:"LOTE";loteProduccionId:number};motivo:string;diagnostico?:string|null;observaciones?:string|null;detalles:DetalleRegistroSanidad[]}
export interface DiagnosticoSanidad{consistente:boolean;fuentesRevisadas:number;movimientosRevisados:number;diferencias:Array<{tipo:string;esperado:number;actual:number}>}
