import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Autocomplete } from "../../components/ui/Autocomplete";
import { DialogoConfirmacion } from "../../components/ui/DialogoConfirmacion";
import { InsigniaEstado } from "../../components/ui/InsigniaEstado";
import { useSesion } from "../../hooks/useSesion";
import { Usuarios_actualizarAccesos, Usuarios_listarAccesos, Usuarios_obtenerAccesos, Usuarios_obtenerRoles } from "../../services/usuarios.service";
import { ErrorApi } from "../../types/api.types";
import type { DetalleAccesos, EstadoAcceso, PermisoAcceso, RolAdministrativo, UsuarioAccesoResumen } from "../../types/usuarios.types";

const ObjModulos: Record<string, string> = { USUARIOS: "Usuarios", CLIENTES: "Clientes", PROVEEDORES: "Proveedores", INVENTARIO: "Inventario", PRODUCCION: "Producción", ALIMENTACION: "Alimentación", SANIDAD: "Sanidad", VENTAS: "Ventas", REPORTES: "Reportes" };
const ObjEstados: Record<EstadoAcceso, string> = { HEREDAR: "Según el rol", PERMITIR: "Permitir", DENEGAR: "Denegar" };
const ObjOrigenes: Record<string, [string, string, string]> = { HEREDADO_DEL_ROL: ["Permitido", "Por el rol", "permitido"], PERMITIDO_DIRECTAMENTE: ["Permitido", "Directamente", "permitido"], DENEGADO_DIRECTAMENTE: ["Denegado", "Directamente", "denegado"], SIN_ACCESO: ["Sin acceso", "Según el rol", "sin-acceso"], PERMISO_INACTIVO: ["Inactivo", "Permiso inactivo", "inactivo"] };
function Accesos_modulo(StrModulo: string) { return ObjModulos[StrModulo] ?? StrModulo.charAt(0) + StrModulo.slice(1).toLowerCase(); }
function Accesos_origen(ObjPermiso: PermisoAcceso): [string, string, string] { return ObjOrigenes[ObjPermiso.origen] ?? [ObjPermiso.permitido ? "Permitido" : "Sin acceso", "Acceso efectivo", ObjPermiso.permitido ? "permitido" : "sin-acceso"]; }

export function PaginaAccesos() {
  const { ObjUsuario, Autenticacion_refrescarSesionSilenciosa } = useSesion();
  const navegar = useNavigate();
  const [ArrUsuarios, establecerUsuarios] = useState<UsuarioAccesoResumen[]>([]); const [ArrRoles, establecerRoles] = useState<RolAdministrativo[]>([]); const [ObjSeleccion, establecerSeleccion] = useState<UsuarioAccesoResumen | null>(null); const [ObjDetalle, establecerDetalle] = useState<DetalleAccesos | null>(null); const [IntRolId, establecerRolId] = useState(0); const [ObjSelecciones, establecerSelecciones] = useState<Record<number, EstadoAcceso>>({}); const [StrMensaje, establecerMensaje] = useState(""); const [BoolConfirmar, establecerConfirmar] = useState(false); const [BoolGuardando, establecerGuardando] = useState(false);
  useEffect(() => { void Promise.all([Usuarios_listarAccesos(), Usuarios_obtenerRoles()]).then(([U, R]) => { establecerUsuarios(U.datos); establecerRoles(R.datos); }).catch(() => establecerMensaje("No fue posible cargar la administración de accesos.")); }, []);
  async function Accesos_seleccionar(ObjItem: UsuarioAccesoResumen | null) { establecerSeleccion(ObjItem); establecerDetalle(null); establecerMensaje(""); if (!ObjItem) return; try { const R = await Usuarios_obtenerAccesos(ObjItem.usuarioId); establecerDetalle(R.datos); establecerRolId(R.datos.rol.rolId); establecerSelecciones(Object.fromEntries(R.datos.permisos.map(P => [P.permisoId, P.estado]))); } catch { establecerMensaje("No fue posible consultar los accesos del usuario."); } }
  const ArrCambios = useMemo(() => ObjDetalle?.permisos.filter(P => ObjSelecciones[P.permisoId] !== P.estado) ?? [], [ObjDetalle, ObjSelecciones]); const BoolRol = ObjDetalle !== null && IntRolId !== ObjDetalle.rol.rolId; const BoolCambios = BoolRol || ArrCambios.length > 0; const ObjRolNuevo = ArrRoles.find(R => R.rolId === IntRolId); const ArrModulos = useMemo(() => [...new Set(ObjDetalle?.permisos.map(P => P.modulo) ?? [])], [ObjDetalle]);
  function Accesos_cancelar() { if (!ObjDetalle) return; establecerRolId(ObjDetalle.rol.rolId); establecerSelecciones(Object.fromEntries(ObjDetalle.permisos.map(P => [P.permisoId, P.estado]))); establecerMensaje(""); }
  async function Accesos_guardar() { if (!ObjDetalle || ObjDetalle.usuario.esProtegida || !BoolCambios) return; establecerGuardando(true); try { const R = await Usuarios_actualizarAccesos(ObjDetalle.usuario.usuarioId, { versionAccesos: ObjDetalle.versionAccesos, rolId: IntRolId, cambios: ArrCambios.map(P => ({ permisoId: P.permisoId, estado: ObjSelecciones[P.permisoId] ?? P.estado })) }); establecerDetalle(R.datos); establecerRolId(R.datos.rol.rolId); establecerSelecciones(Object.fromEntries(R.datos.permisos.map(P => [P.permisoId, P.estado]))); establecerMensaje("Accesos actualizados correctamente."); establecerConfirmar(false); if (ObjUsuario?.usuarioId === R.datos.usuario.usuarioId) { const ObjSesion = await Autenticacion_refrescarSesionSilenciosa(); if (ObjSesion && !ObjSesion.permisos.includes("USUARIOS_ASIGNAR_ROL")) navegar("/inicio", { replace: true }); } } catch (E) { establecerConfirmar(false); establecerMensaje(E instanceof ErrorApi && E.IntEstadoHttp === 409 ? "Los accesos cambiaron en otra sesión. Recargue el usuario antes de guardar." : "No fue posible guardar los accesos."); } finally { establecerGuardando(false); } }
  return <section className="pagina-usuarios pagina-accesos"><header className="usuarios-encabezado"><div><p className="etiqueta">Usuarios</p><h1>Administración de accesos</h1><p>Administre el rol y los permisos individuales de cada usuario.</p></div></header>
    <div className="accesos-buscador"><Autocomplete StrEtiqueta="Buscar usuario" StrPlaceholder="Buscar por nombre o usuario..." ObjSeleccion={ObjSeleccion} Autocomplete_buscar={async B => { const N = B.toLowerCase(); const L = ArrUsuarios.filter(U => `${U.nombreCompleto} ${U.nombreUsuario}`.toLowerCase().includes(N)); return L.length ? L : (await Usuarios_listarAccesos(B)).datos; }} Autocomplete_etiqueta={U => U.nombreCompleto} Autocomplete_clave={U => U.usuarioId} Autocomplete_seleccionar={U => void Accesos_seleccionar(U)} Autocomplete_renderizarOpcion={U => <span className="accesos-opcion-usuario"><strong>{U.nombreCompleto}</strong><small>{U.nombreUsuario} · {U.rol.nombre}</small></span>} /></div>
    {StrMensaje && <p className={StrMensaje.includes("correctamente") ? "mensaje-exito" : "mensaje-error"} role="status">{StrMensaje}</p>}
    {ObjDetalle && <><article className="accesos-usuario-tarjeta"><div className="accesos-usuario-identidad"><div><span className="etiqueta">Usuario seleccionado</span><h2>{ObjDetalle.usuario.nombreCompleto}</h2><p><span>Usuario</span><strong>{ObjDetalle.usuario.nombreUsuario}</strong></p></div><div className="accesos-usuario-badges"><InsigniaEstado StrEstado={ObjDetalle.usuario.estado} />{ObjDetalle.usuario.esProtegida && <span className="accesos-badge-protegida">Cuenta protegida</span>}</div></div><div className="campo-formulario accesos-campo-rol"><label htmlFor="accesos-rol">Rol del usuario</label><select id="accesos-rol" disabled={ObjDetalle.usuario.esProtegida} value={IntRolId} onChange={E => establecerRolId(Number(E.target.value))}>{ArrRoles.filter(R => R.activo && !R.esReservado).map(R => <option key={R.rolId} value={R.rolId}>{Accesos_modulo(R.nombre)}</option>)}</select></div></article>
      {ObjDetalle.usuario.esProtegida && <aside className="accesos-aviso-protegida"><strong>Cuenta protegida</strong><p>Esta cuenta es estructuralmente protegida y sus accesos solo pueden consultarse.</p></aside>}
      {BoolCambios && <section className="accesos-cambios"><div><span className="etiqueta">Revisión</span><h2>Cambios pendientes</h2></div><ul>{BoolRol && <li><span>Rol</span><strong>{ObjDetalle.rol.nombre} → {ObjRolNuevo?.nombre ?? "—"}</strong></li>}{ArrCambios.map(P => <li key={P.permisoId}><span>{Accesos_modulo(P.modulo)} · {P.nombre}</span><strong>{ObjEstados[P.estado]} → {ObjEstados[ObjSelecciones[P.permisoId] ?? P.estado]}</strong></li>)}</ul></section>}
      <div className="accesos-matriz-encabezado"><span className="etiqueta">Matriz efectiva</span><h2>Permisos por módulo</h2><p>El resultado efectivo combina el rol con las excepciones individuales.</p></div>
      <div className="accesos-modulos">{ArrModulos.map(M => <section className="accesos-modulo" key={M}><header><div><h3>{Accesos_modulo(M)}</h3><p>Administración del módulo {Accesos_modulo(M)}.</p></div><span>{ObjDetalle.permisos.filter(P => P.modulo === M).length} permisos</span></header><div>{ObjDetalle.permisos.filter(P => P.modulo === M).map(P => { const [Resultado, Detalle, Clase] = Accesos_origen(P); return <div className="accesos-permiso" key={P.permisoId}><div className="accesos-permiso-info"><strong>{P.nombre}</strong><code>{P.codigo}</code><div className="accesos-resultado"><span className={`accesos-badge accesos-badge--${Clase}`}>{Resultado}</span><small>{Detalle}</small></div></div><label className="accesos-selector"><span>Asignación individual</span><select disabled={ObjDetalle.usuario.esProtegida || !P.activo} value={ObjSelecciones[P.permisoId] ?? P.estado} onChange={E => establecerSelecciones(A => ({ ...A, [P.permisoId]: E.target.value as EstadoAcceso }))}><option value="HEREDAR">Según el rol</option><option value="PERMITIR">Permitir</option><option value="DENEGAR">Denegar</option></select></label></div>; })}</div></section>)}</div>
      <div className="accesos-acciones"><button type="button" className="boton-secundario" disabled={!BoolCambios || ObjDetalle.usuario.esProtegida || BoolGuardando} onClick={Accesos_cancelar}>Cancelar cambios</button><button type="button" className="boton-primario" disabled={!BoolCambios || ObjDetalle.usuario.esProtegida || BoolGuardando} onClick={() => establecerConfirmar(true)}>Guardar cambios</button></div></>}
    <DialogoConfirmacion BoolAbierto={BoolConfirmar} StrTitulo="Guardar cambios de acceso" StrMensaje={`Se actualizarán ${ArrCambios.length + (BoolRol ? 1 : 0)} cambios para ${ObjDetalle?.usuario.nombreCompleto ?? "el usuario"}.`} StrConfirmar="Guardar cambios" StrClaseConfirmar="boton-primario" BoolProcesando={BoolGuardando} Autenticacion_cancelar={() => establecerConfirmar(false)} Autenticacion_confirmar={() => void Accesos_guardar()} />
  </section>;
}
