import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { IndicadorCarga } from "../../components/ui/IndicadorCarga";
import { MensajeError } from "../../components/ui/MensajeError";
import { Paginacion } from "../../components/ui/Paginacion";
import { Reportes_consultar, Reportes_descargarCsv } from "../../services/reportes.service";

function Reportes_mesActual(){const F=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Guatemala",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());return[`${F.slice(0,7)}-01`,F]}
function Reportes_valor(V:unknown):string{if(V===null||V===undefined||V==="")return"—";if(typeof V==="object")return Array.isArray(V)?`${V.length} registro(s)`:Object.values(V as Record<string,unknown>).map(Reportes_valor).filter(X=>X!=="—").join(" · ")||"—";return String(V)}
function Reportes_columnas(D:Record<string,unknown>[],StrRuta:string){if(StrRuta==="produccion/mediciones")return["fechaMedicion","animalIdentificacion","valor","pesoLb","metodoEtiqueta","perimetroToracicoCm","longitudCorporalCm","observaciones"];return[...new Set(D.flatMap(O=>Object.keys(O)))].filter(K=>!Array.isArray(D[0]?.[K])).slice(0,10)}

export function PaginaReporte({StrRuta,StrTitulo,BoolPeriodo=true}:{StrRuta:string;StrTitulo:string;BoolPeriodo?:boolean}){
 const[Q,setQ]=useSearchParams();const[Datos,setDatos]=useState<Record<string,unknown>[]>([]),[Total,setTotal]=useState(0),[Cargando,setCargando]=useState(true),[StrError,setError]=useState<string|null>(null);const[Desde,Hasta]=Reportes_mesActual();
 useEffect(()=>{const N=new URLSearchParams(Q);if(BoolPeriodo&&!N.has("fechaDesde")){N.set("fechaDesde",Desde);N.set("fechaHasta",Hasta);setQ(N,{replace:true});return}N.set("limite","20");setCargando(true);setError(null);Reportes_consultar(StrRuta,N).then(R=>{setDatos(R.datos);setTotal(R.paginacion.total)}).catch(E=>setError(E instanceof Error?E.message:"No fue posible consultar el reporte.")).finally(()=>setCargando(false))},[StrRuta,Q,setQ,BoolPeriodo,Desde,Hasta]);
 const Cols=useMemo(()=>Reportes_columnas(Datos,StrRuta),[Datos,StrRuta]);function Cambiar(K:string,V:string){const N=new URLSearchParams(Q);V?N.set(K,V):N.delete(K);N.set("pagina","1");setQ(N)}
 return <article className="reportes-panel"><header><div><h2>{StrTitulo}</h2><p>Los totales y costos provienen del backend; la interfaz no recalcula valores económicos.</p></div><button className="boton-secundario" onClick={()=>void Reportes_descargarCsv(StrRuta,Q)}>Exportar CSV</button></header><div className="reportes-filtros">{BoolPeriodo&&<><label>Desde<input type="date" value={Q.get("fechaDesde")??""} onChange={E=>Cambiar("fechaDesde",E.target.value)}/></label><label>Hasta<input type="date" value={Q.get("fechaHasta")??""} onChange={E=>Cambiar("fechaHasta",E.target.value)}/></label></>}<label>Estado<select value={Q.get("estado")??""} onChange={E=>Cambiar("estado",E.target.value)}><option value="">Todos</option><option>CONFIRMADA</option><option>REVERTIDA</option><option>ANULADA</option></select></label></div>{StrError&&<MensajeError StrMensaje={StrError}/>} {Cargando?<IndicadorCarga StrMensaje="Consultando reporte…"/>:Datos.length===0?<p className="reportes-vacio">Sin registros para los filtros seleccionados.</p>:<div className="reportes-tabla"><table><thead><tr>{Cols.map(C=><th key={C}>{C.replaceAll(/([A-Z])/g," $1").replaceAll("Id","").trim()}</th>)}</tr></thead><tbody>{Datos.map((D,I)=><tr key={String(D.id??D.ventaId??D.medicionId??I)}>{Cols.map(C=><td key={C}>{Reportes_valor(D[C])}</td>)}</tr>)}</tbody></table></div>}<Paginacion IntPagina={Number(Q.get("pagina")??1)} IntTotalPaginas={Math.max(1,Math.ceil(Total/20))} Usuarios_cambiarPagina={P=>{const N=new URLSearchParams(Q);N.set("pagina",String(P));setQ(N)}}/></article>
}
