import { randomBytes } from "node:crypto";
import type { AddressInfo } from "node:net";
import dotenv from "dotenv";
import { PrismaMssql } from "@prisma/adapter-mssql";
import { PrismaClient } from "../../generated/prisma/client.js";
import { Autenticacion_hashearTokenSesion } from "../auth/autenticacion.js";
import { BaseDatos_desconectar, BaseDatos_obtenerCliente } from "../database/prisma.js";
import { Fecha_obtenerAhoraGuatemala } from "../datetime/fecha.js";
import * as Repo from "../modules/usuarios/usuarios.repository.js";

dotenv.config({ path: "../.env" });
if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL_REQUERIDA");
const StrUrlOriginal = process.env.DATABASE_URL;
const cambiarBase=(U:string,B:string)=>U.replace(/(^|;)database=[^;]+/i,`$1database=${B}`);
const StrNombre=`granja_test_accesos_copia_${process.pid}_${Date.now()}_${randomBytes(4).toString("hex")}`;
if(!/^granja_test_[a-z0-9_]+$/.test(StrNombre)) throw new Error("NOMBRE_TEMPORAL_INVALIDO");
const Admin=new PrismaClient({adapter:new PrismaMssql(cambiarBase(StrUrlOriginal,"master"))});
let StrBackup=""; let BoolRestaurada=false;
const serializar=(_K:string,V:unknown)=>typeof V==="bigint"?V.toString():V;
try {
  const [Rutas]=await Admin.$queryRawUnsafe<Array<{backup:string;datos:string;log:string}>>(`SELECT CAST(SERVERPROPERTY('InstanceDefaultBackupPath') AS nvarchar(4000)) AS [backup],CAST(SERVERPROPERTY('InstanceDefaultDataPath') AS nvarchar(4000)) AS [datos],CAST(SERVERPROPERTY('InstanceDefaultLogPath') AS nvarchar(4000)) AS [log]`);
  if(!Rutas?.backup||!Rutas.datos||!Rutas.log) throw new Error("RUTAS_SQL_NO_DISPONIBLES");
  StrBackup=`${Rutas.backup}${Rutas.backup.endsWith("\\")?"":"\\"}${StrNombre}.bak`;
  await Admin.$executeRawUnsafe(`BACKUP DATABASE [granja_el_chiflon] TO DISK=N'${StrBackup.replaceAll("'","''")}' WITH COPY_ONLY,INIT,CHECKSUM`);
  const Archivos=await Admin.$queryRawUnsafe<Array<{LogicalName:string;Type:string}>>(`RESTORE FILELISTONLY FROM DISK=N'${StrBackup.replaceAll("'","''")}'`);
  const Datos=Archivos.find(A=>A.Type==="D"),Log=Archivos.find(A=>A.Type==="L"); if(!Datos||!Log) throw new Error("BACKUP_SIN_ARCHIVOS_LOGICOS");
  const Fmdf=`${Rutas.datos}${Rutas.datos.endsWith("\\")?"":"\\"}${StrNombre}.mdf`,Fldf=`${Rutas.log}${Rutas.log.endsWith("\\")?"":"\\"}${StrNombre}_log.ldf`;
  await Admin.$executeRawUnsafe(`RESTORE DATABASE [${StrNombre}] FROM DISK=N'${StrBackup.replaceAll("'","''")}' WITH MOVE N'${Datos.LogicalName.replaceAll("'","''")}' TO N'${Fmdf.replaceAll("'","''")}',MOVE N'${Log.LogicalName.replaceAll("'","''")}' TO N'${Fldf.replaceAll("'","''")}',RECOVERY`); BoolRestaurada=true;
  const CopiaPre=new PrismaClient({adapter:new PrismaMssql(cambiarBase(StrUrlOriginal,StrNombre))});
  const conteosPre=(await CopiaPre.$queryRawUnsafe<Record<string,bigint>[]>(`SELECT (SELECT COUNT_BIG(*) FROM usuarios_cuentas) usuarios,(SELECT COUNT_BIG(*) FROM usuarios_roles) roles,(SELECT COUNT_BIG(*) FROM usuarios_permisos) permisos,(SELECT COUNT_BIG(*) FROM usuarios_roles_permisos) asignaciones,(SELECT COUNT_BIG(*) FROM usuarios_sesiones) sesiones`))[0];
  const webmasterPre=(await CopiaPre.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT C.*,R.nombre rol_nombre FROM usuarios_cuentas C JOIN usuarios_roles R ON R.rol_id=C.rol_id WHERE R.nombre=N'WEBMASTER'`))[0];
  await CopiaPre.$disconnect();
  process.env.DATABASE_URL=cambiarBase(StrUrlOriginal,StrNombre); process.env.BASE_DATOS_ESPERADA=StrNombre;
  const {execFile}=await import("node:child_process"); const {promisify}=await import("node:util"); const path=await import("node:path");
  await promisify(execFile)(process.execPath,[path.default.join(process.cwd(),"node_modules","prisma","build","index.js"),"migrate","deploy"],{cwd:process.cwd(),env:{...process.env}});
  const Db=BaseDatos_obtenerCliente();
  const conteosPost=(await Db.$queryRawUnsafe<Record<string,bigint>[]>(`SELECT (SELECT COUNT_BIG(*) FROM usuarios_cuentas) usuarios,(SELECT COUNT_BIG(*) FROM usuarios_roles) roles,(SELECT COUNT_BIG(*) FROM usuarios_permisos) permisos,(SELECT COUNT_BIG(*) FROM usuarios_roles_permisos) asignaciones,(SELECT COUNT_BIG(*) FROM usuarios_sesiones) sesiones,(SELECT COUNT_BIG(*) FROM usuarios_permisos_directos) overrides,(SELECT COUNT_BIG(*) FROM usuarios_accesos_eventos) eventos`))[0];
  const webmasterPost=(await Db.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT C.*,R.nombre rol_nombre,R.es_reservado FROM usuarios_cuentas C JOIN usuarios_roles R ON R.rol_id=C.rol_id WHERE R.nombre=N'WEBMASTER'`))[0];
  const BoolWebmasterSinCambio=!!webmasterPre&&!!webmasterPost&&Object.entries(webmasterPre).every(([K,V])=>webmasterPost[K] instanceof Date&&V instanceof Date?(webmasterPost[K] as Date).getTime()===V.getTime():webmasterPost[K]===V);
  const marcadores=await Db.$queryRawUnsafe(`SELECT R.nombre,R.es_reservado,C.nombre_usuario,C.es_protegida,C.version_accesos FROM usuarios_roles R LEFT JOIN usuarios_cuentas C ON C.rol_id=R.rol_id ORDER BY R.rol_id`);
  const [AdminUser]=await Db.$queryRawUnsafe<Array<{usuario_id:number}>>(`SELECT TOP 1 C.usuario_id FROM usuarios_cuentas C JOIN usuarios_roles R ON R.rol_id=C.rol_id WHERE R.nombre=N'ADMINISTRADOR' ORDER BY C.usuario_id`);
  const [WebUser]=await Db.$queryRawUnsafe<Array<{usuario_id:number}>>(`SELECT TOP 1 C.usuario_id FROM usuarios_cuentas C JOIN usuarios_roles R ON R.rol_id=C.rol_id WHERE R.nombre=N'WEBMASTER' ORDER BY C.usuario_id`);
  const [PAdmin]=await Db.$queryRawUnsafe<Array<{permiso_id:number}>>(`SELECT permiso_id FROM usuarios_permisos WHERE codigo=N'USUARIOS_ASIGNAR_ROL'`);
  const [PCliente]=await Db.$queryRawUnsafe<Array<{permiso_id:number}>>(`SELECT permiso_id FROM usuarios_permisos WHERE codigo=N'CLIENTES_CONSULTAR'`);
  const [PExtra]=await Db.$queryRawUnsafe<Array<{permiso_id:number}>>(`SELECT permiso_id FROM usuarios_permisos WHERE codigo=N'USUARIOS_CONSULTAR_CATALOGOS'`);
  const [RolAdmin]=await Db.$queryRawUnsafe<Array<{rol_id:number}>>(`SELECT rol_id FROM usuarios_roles WHERE nombre=N'ADMINISTRADOR'`);
  const [RolWeb]=await Db.$queryRawUnsafe<Array<{rol_id:number}>>(`SELECT rol_id FROM usuarios_roles WHERE nombre=N'WEBMASTER'`);
  const [RolOperador]=await Db.$queryRawUnsafe<Array<{rol_id:number}>>(`SELECT rol_id FROM usuarios_roles WHERE nombre=N'OPERADOR'`);
  if(!AdminUser||!WebUser||!PAdmin||!PCliente||!PExtra||!RolAdmin||!RolWeb||!RolOperador) throw new Error("DATOS_PRUEBA_NO_DISPONIBLES");
  const Token=`temporal_${randomBytes(24).toString("hex")}`; const Ahora=Fecha_obtenerAhoraGuatemala(); const Expira=new Date(Ahora.getTime()+3600000);
  await Db.usuarioSesion.create({data:{usuarioId:AdminUser.usuario_id,token:Autenticacion_hashearTokenSesion(Token),fechaInicio:Ahora,fechaExpiracion:Expira,direccionIp:"127.0.0.1"}});
  const {default:App}=await import("../app.js"); const Server=App.listen(0,"127.0.0.1"); await new Promise<void>((ok,fail)=>{Server.once("listening",()=>ok());Server.once("error",fail)}); const Url=`http://127.0.0.1:${(Server.address() as AddressInfo).port}`;
  const api=(Ruta:string,Init:RequestInit={})=>fetch(`${Url}${Ruta}`,{...Init,headers:{cookie:`id=${Token}`,"content-type":"application/json",...(Init.headers??{})}});
  const resultados:Record<string,unknown>={};
  try {
    resultados.heredadoInicial=(await api("/api/usuarios/accesos?pagina=1&limite=10")).status;
    resultados.otroEndpointInicial=(await api("/api/clientes?pagina=1&limite=1")).status;
    const DetHttp=await (await api(`/api/usuarios/${AdminUser.usuario_id}/accesos`)).json() as {datos:{versionAccesos:number;rol:{rolId:number}}};
    resultados.denyPatch=(await api(`/api/usuarios/${AdminUser.usuario_id}/accesos`,{method:"PATCH",body:JSON.stringify({versionAccesos:DetHttp.datos.versionAccesos,rolId:DetHttp.datos.rol.rolId,cambios:[{permisoId:PAdmin.permiso_id,estado:"DENEGAR"}]})})).status;
    resultados.denySiguiente=(await api("/api/usuarios/accesos?pagina=1&limite=10")).status;
    resultados.sesionTrasDeny=(await api("/api/usuarios/sesion")).status;
    resultados.otroEndpointTrasDeny=(await api("/api/clientes?pagina=1&limite=1")).status;
    const DetAllow=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>;
    await Repo.Usuarios_actualizarAccesos({IntUsuarioId:AdminUser.usuario_id,IntVersionAccesos:DetAllow.versionAccesos,IntRolId:DetAllow.rolId,ArrCambios:[{IntPermisoId:PAdmin.permiso_id,StrEstado:"PERMITIR"}],IntUsuarioActorId:WebUser.usuario_id,StrDireccionIp:"127.0.0.1"});
    resultados.allowSiguiente=(await api("/api/usuarios/accesos?pagina=1&limite=10")).status;
    const SesAllow=await (await api("/api/usuarios/sesion")).json() as {datos:{usuario:{permisos:string[]}}}; resultados.sesionIncluyeAllow=SesAllow.datos.usuario.permisos.includes("USUARIOS_ASIGNAR_ROL");
    const DetHeredar=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>;
    await Repo.Usuarios_actualizarAccesos({IntUsuarioId:AdminUser.usuario_id,IntVersionAccesos:DetHeredar.versionAccesos,IntRolId:DetHeredar.rolId,ArrCambios:[{IntPermisoId:PAdmin.permiso_id,StrEstado:"HEREDAR"}],IntUsuarioActorId:WebUser.usuario_id});
    resultados.heredarRecupera=(await api("/api/usuarios/accesos?pagina=1&limite=10")).status;
    const DetAuto=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>;
    const RespAuto=await api(`/api/usuarios/${AdminUser.usuario_id}/accesos`,{method:"PATCH",body:JSON.stringify({versionAccesos:DetAuto.versionAccesos,rolId:DetAuto.rolId,cambios:[{permisoId:PCliente.permiso_id,estado:"PERMITIR"},{permisoId:PAdmin.permiso_id,estado:"DENEGAR"}]})}); resultados.autogestionPatch=RespAuto.status;
    resultados.autogestionAccesosPosterior=(await api("/api/usuarios/accesos?pagina=1&limite=10")).status; resultados.autogestionSesion=(await api("/api/usuarios/sesion")).status; resultados.autogestionOtroModulo=(await api("/api/clientes?pagina=1&limite=1")).status;
    const DetRestaurar=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; await Repo.Usuarios_actualizarAccesos({IntUsuarioId:AdminUser.usuario_id,IntVersionAccesos:DetRestaurar.versionAccesos,IntRolId:DetRestaurar.rolId,ArrCambios:[{IntPermisoId:PAdmin.permiso_id,StrEstado:"PERMITIR"}],IntUsuarioActorId:WebUser.usuario_id});
    const DetConcurrente=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; const VersionConcurrente=DetConcurrente.versionAccesos;
    const C1=await api(`/api/usuarios/${AdminUser.usuario_id}/accesos`,{method:"PATCH",body:JSON.stringify({versionAccesos:VersionConcurrente,rolId:DetConcurrente.rolId,cambios:[{permisoId:PCliente.permiso_id,estado:"DENEGAR"}]})}); const C2=await api(`/api/usuarios/${AdminUser.usuario_id}/accesos`,{method:"PATCH",body:JSON.stringify({versionAccesos:VersionConcurrente,rolId:DetConcurrente.rolId,cambios:[{permisoId:PCliente.permiso_id,estado:"HEREDAR"}]})}); resultados.concurrencia=[C1.status,C2.status];
    const AntesAtomico=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; const EventosAntes=await Db.usuarioAccesoEvento.count(); let falloAtomico=false; try{await Repo.Usuarios_actualizarAccesos({IntUsuarioId:AdminUser.usuario_id,IntVersionAccesos:AntesAtomico.versionAccesos,IntRolId:AntesAtomico.rolId,ArrCambios:[{IntPermisoId:PCliente.permiso_id,StrEstado:"PERMITIR"},{IntPermisoId:999999999,StrEstado:"DENEGAR"}],IntUsuarioActorId:WebUser.usuario_id})}catch{falloAtomico=true} const DespuesAtomico=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; resultados.rollbackAtomico={fallo:falloAtomico,versionIgual:AntesAtomico.versionAccesos===DespuesAtomico.versionAccesos,rolIgual:AntesAtomico.rolId===DespuesAtomico.rolId,eventosIguales:EventosAntes===await Db.usuarioAccesoEvento.count()};
    const WebDet=await Repo.Usuarios_obtenerDetalleAccesos(WebUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; resultados.webmasterProtegido=(await api(`/api/usuarios/${WebUser.usuario_id}/accesos`,{method:"PATCH",body:JSON.stringify({versionAccesos:WebDet.versionAccesos,rolId:RolAdmin.rol_id,cambios:[{permisoId:PAdmin.permiso_id,estado:"DENEGAR"}]})})).status;
    const AdminDet=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; resultados.rolReservado=(await api(`/api/usuarios/${AdminUser.usuario_id}/accesos`,{method:"PATCH",body:JSON.stringify({versionAccesos:AdminDet.versionAccesos,rolId:RolWeb.rol_id,cambios:[]})})).status;
    await Db.usuarioPermiso.update({where:{permisoId:PCliente.permiso_id},data:{activo:false}}); const SesInactivo=await (await api("/api/usuarios/sesion")).json() as {datos:{usuario:{permisos:string[]}}}; resultados.permisoInactivoDenegado=!SesInactivo.datos.usuario.permisos.includes("CLIENTES_CONSULTAR"); await Db.usuarioPermiso.update({where:{permisoId:PCliente.permiso_id},data:{activo:true}});
    await Db.usuarioCuenta.update({where:{usuarioId:AdminUser.usuario_id},data:{estado:"INACTIVO"}}); resultados.usuarioInactivo=(await api("/api/usuarios/sesion")).status; await Db.usuarioCuenta.update({where:{usuarioId:AdminUser.usuario_id},data:{estado:"ACTIVO"}}); await Db.usuarioRol.update({where:{rolId:RolAdmin.rol_id},data:{activo:false}}); resultados.rolInactivo=(await api("/api/usuarios/sesion")).status; await Db.usuarioRol.update({where:{rolId:RolAdmin.rol_id},data:{activo:true}});
    const AntesCommit=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; const EventosCommitAntes=await Db.usuarioAccesoEvento.count();
    await Repo.Usuarios_actualizarAccesos({IntUsuarioId:AdminUser.usuario_id,IntVersionAccesos:AntesCommit.versionAccesos,IntRolId:RolOperador.rol_id,ArrCambios:[{IntPermisoId:PExtra.permiso_id,StrEstado:"PERMITIR"},{IntPermisoId:PAdmin.permiso_id,StrEstado:"DENEGAR"}],IntUsuarioActorId:WebUser.usuario_id,StrDireccionIp:"127.0.0.1"});
    const DespuesCommit=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; const SesCommit=await (await api("/api/usuarios/sesion")).json() as {datos:{usuario:{permisos:string[]}}}; resultados.commitAtomico={rolCambiado:DespuesCommit.rolId===RolOperador.rol_id,versionIncrementada:DespuesCommit.versionAccesos===AntesCommit.versionAccesos+1,eventosCreados:(await Db.usuarioAccesoEvento.count())-EventosCommitAntes,allowAusenteRol:SesCommit.datos.usuario.permisos.includes("USUARIOS_CONSULTAR_CATALOGOS"),denyAplicado:false===SesCommit.datos.usuario.permisos.includes("USUARIOS_ASIGNAR_ROL")};
    const EventosNoop=await Db.usuarioAccesoEvento.count(); await Repo.Usuarios_actualizarAccesos({IntUsuarioId:AdminUser.usuario_id,IntVersionAccesos:DespuesCommit.versionAccesos,IntRolId:DespuesCommit.rolId,ArrCambios:[{IntPermisoId:PExtra.permiso_id,StrEstado:"PERMITIR"}],IntUsuarioActorId:WebUser.usuario_id}); const DespuesNoop=await Repo.Usuarios_obtenerDetalleAccesos(AdminUser.usuario_id) as NonNullable<Awaited<ReturnType<typeof Repo.Usuarios_obtenerDetalleAccesos>>>; resultados.sinCambiosSinAuditoria={eventosIguales:EventosNoop===await Db.usuarioAccesoEvento.count(),versionIgual:DespuesNoop.versionAccesos===DespuesCommit.versionAccesos};
  } finally { await new Promise<void>((ok,fail)=>Server.close(E=>E?fail(E):ok())); }
  const auditoria=await Db.$queryRawUnsafe(`SELECT tipo,COUNT_BIG(*) cantidad,SUM(CASE WHEN usuario_id IS NOT NULL AND actor_usuario_id IS NOT NULL AND fecha IS NOT NULL THEN 1 ELSE 0 END) completos,SUM(CASE WHEN tipo='CAMBIO_OVERRIDE' AND permiso_id IS NOT NULL AND estado_anterior IS NOT NULL AND estado_nuevo IS NOT NULL THEN 1 WHEN tipo='CAMBIO_ROL' AND rol_anterior_id IS NOT NULL AND rol_nuevo_id IS NOT NULL THEN 1 ELSE 0 END) coherentes FROM usuarios_accesos_eventos GROUP BY tipo`);
  const dbcc=await Db.$queryRawUnsafe(`DBCC CHECKCONSTRAINTS WITH ALL_CONSTRAINTS`);
  const migrateStatus=await promisify(execFile)(process.execPath,[path.default.join(process.cwd(),"node_modules","prisma","build","index.js"),"migrate","status"],{cwd:process.cwd(),env:{...process.env}});
  console.log(JSON.stringify({base:StrNombre,conteosPre,conteosPost,webmasterSinCambio:BoolWebmasterSinCambio,webmasterProtegido:webmasterPost?.es_protegida===true,rolWebmasterReservado:webmasterPost?.es_reservado===true,marcadores,resultados,auditoria,dbccProblemas:(dbcc as unknown[]).length,migrateStatus:migrateStatus.stdout.trim()},serializar,2));
} finally {
  await BaseDatos_desconectar(); process.env.DATABASE_URL=StrUrlOriginal;
  if(BoolRestaurada) await Admin.$executeRawUnsafe(`IF DB_ID(N'${StrNombre}') IS NOT NULL BEGIN ALTER DATABASE [${StrNombre}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [${StrNombre}]; END`);
  if(StrBackup) { try { await Admin.$executeRawUnsafe(`EXEC master.dbo.xp_delete_file 0,N'${StrBackup.replaceAll("'","''")}',N'bak'`) } catch { console.warn("BACKUP_TEMPORAL_REQUIERE_LIMPIEZA_MANUAL") } }
  await Admin.$disconnect(); console.log("CLEANUP_COPIA_OK");
}
