import { Router } from "express";
import { Middleware_requerirAutenticacion,Middleware_requerirPermiso } from "../../middleware/autenticacion.middleware.js";
import * as C from "./produccion.controller.js";
import { Produccion_formatearRespuesta } from "./produccion.service.js";
export function Produccion_crearRouter():Router{const R=Router();R.use(Middleware_requerirAutenticacion);R.use((_Req,Res,Next)=>{const original=Res.json.bind(Res);Res.json=((cuerpo:unknown)=>original(Produccion_formatearRespuesta(cuerpo))) as typeof Res.json;Next();});
R.get("/proveedores",Middleware_requerirPermiso("PRODUCCION_COMPRAS_CREAR"),C.Produccion_listarProveedores);
R.get("/tipos-animales",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_listarTipos);R.post("/tipos-animales",Middleware_requerirPermiso("PRODUCCION_TIPOS_CREAR"),C.Produccion_crearTipo);R.patch("/tipos-animales/:tipoAnimalId",Middleware_requerirPermiso("PRODUCCION_TIPOS_EDITAR"),C.Produccion_editarTipo);R.patch("/tipos-animales/:tipoAnimalId/estado",Middleware_requerirPermiso("PRODUCCION_TIPOS_CAMBIAR_ESTADO"),C.Produccion_estadoTipo);
R.get("/razas",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_listarRazas);R.post("/razas",Middleware_requerirPermiso("PRODUCCION_RAZAS_CREAR"),C.Produccion_crearRaza);R.patch("/razas/:razaId",Middleware_requerirPermiso("PRODUCCION_RAZAS_EDITAR"),C.Produccion_editarRaza);R.patch("/razas/:razaId/estado",Middleware_requerirPermiso("PRODUCCION_RAZAS_CAMBIAR_ESTADO"),C.Produccion_estadoRaza);
R.get("/lotes",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_listarLotes);R.post("/lotes",Middleware_requerirPermiso("PRODUCCION_LOTES_CREAR"),C.Produccion_crearLote);R.get("/lotes/:loteProduccionId",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_obtenerLote);R.patch("/lotes/:loteProduccionId",Middleware_requerirPermiso("PRODUCCION_LOTES_EDITAR"),C.Produccion_editarLote);R.patch("/lotes/:loteProduccionId/estado",Middleware_requerirPermiso("PRODUCCION_LOTES_CAMBIAR_ESTADO"),C.Produccion_estadoLote);
R.get("/animales",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_listarAnimales);R.get("/animales/:animalId/foto",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_descargarFoto);R.post("/animales/:animalId/foto",Middleware_requerirPermiso("PRODUCCION_ANIMALES_EDITAR"),C.Produccion_recibirFoto,C.Produccion_reemplazarFoto);R.get("/animales/:animalId",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_obtenerAnimal);R.patch("/animales/:animalId",Middleware_requerirPermiso("PRODUCCION_ANIMALES_EDITAR"),C.Produccion_editarAnimal);R.patch("/animales/:animalId/estado",Middleware_requerirPermiso("PRODUCCION_ESTADOS_TERMINALES_REGISTRAR"),C.Produccion_estadoAnimal);
R.post("/ingresos/iniciales",Middleware_requerirPermiso("PRODUCCION_INGRESOS_INICIALES_CREAR"),C.Produccion_inicial);R.post("/nacimientos",Middleware_requerirPermiso("PRODUCCION_NACIMIENTOS_CREAR"),C.Produccion_nacimiento);R.post("/compras",Middleware_requerirPermiso("PRODUCCION_COMPRAS_CREAR"),C.Produccion_compra);R.post("/traslados",Middleware_requerirPermiso("PRODUCCION_TRASLADOS_CREAR"),C.Produccion_traslado);
R.get("/mediciones",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_listarMediciones);R.post("/mediciones",Middleware_requerirPermiso("PRODUCCION_MEDICIONES_CREAR"),C.Produccion_medicion);R.get("/operaciones",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_listarOperaciones);R.get("/transacciones",Middleware_requerirPermiso("PRODUCCION_CONSULTAR"),C.Produccion_listarTransacciones);R.post("/operaciones/:operacionProduccionId/revertir",Middleware_requerirPermiso("PRODUCCION_OPERACIONES_REVERTIR"),C.Produccion_revertir);R.post("/diagnosticos/reconciliacion",Middleware_requerirPermiso("PRODUCCION_RECONCILIACION_EJECUTAR"),C.Produccion_diagnostico);return R;}
