import { Prisma } from "../../../generated/prisma/client.js";
import { Fecha_convertirAlmacenamientoGuatemalaAInstante, Fecha_formatearFechaCivil, Fecha_formatearInstanteGuatemala, Fecha_parsearFechaCivil } from "../../datetime/fecha.js";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import { Produccion_canonicalizarCodigo } from "./produccion.constants.js";
import * as R from "./produccion.repository.js";

export function Produccion_formatearRespuesta<T>(ObjValor:T,StrClave=""):T { if(ObjValor instanceof Date)return(StrClave==="fechaNacimiento"?Fecha_formatearFechaCivil(ObjValor):Fecha_formatearInstanteGuatemala(Fecha_convertirAlmacenamientoGuatemalaAInstante(ObjValor))) as T;if(Array.isArray(ObjValor))return ObjValor.map(x=>Produccion_formatearRespuesta(x)) as T;if(ObjValor!==null&&typeof ObjValor==="object"&&!(ObjValor instanceof Prisma.Decimal))return Object.fromEntries(Object.entries(ObjValor).map(([k,v])=>[k,Produccion_formatearRespuesta(v,k)])) as T;return ObjValor; }
const ObjErrores:Record<string,[number,string]>={LOTE_NO_ENCONTRADO:[404,"El lote no existe."],LOTE_CERRADO:[409,"El lote esta cerrado."],LOTE_NO_ESTA_VACIO:[409,"El lote contiene animales vigentes."],TIPO_LOTE_INCOMPATIBLE:[409,"El tipo del animal no corresponde al lote."],ANIMAL_NO_ENCONTRADO:[404,"El animal no existe."],ANIMAL_NO_ACTIVO:[409,"El animal no esta activo."],ANIMAL_SIN_ASIGNACION_VIGENTE:[409,"El animal no tiene asignacion vigente."],ANIMAL_NO_PERTENECE_LOTE:[409,"El animal no pertenece al lote origen."],TRASLADO_INVALIDO:[400,"Los lotes de origen y destino deben ser diferentes."],CONFLICTO_CONCURRENCIA:[409,"El animal fue modificado por otra operacion."],OPERACION_NO_ENCONTRADA:[404,"La operacion no existe."],OPERACION_YA_REVERTIDA:[409,"La operacion ya fue revertida."],REVERSION_NO_PERMITIDA:[409,"La operacion no puede revertirse en su estado actual."],OPERACION_INCONSISTENTE:[409,"La operacion no contiene un historial consistente."]};
function Produccion_mapearError(ObjError:unknown):never { if(ObjError instanceof Error&&ObjErrores[ObjError.message]){const[IntEstado,StrMensaje]=ObjErrores[ObjError.message]!;throw new ErrorAplicacion(IntEstado,ObjError.message,StrMensaje);}if(ObjError instanceof Prisma.PrismaClientKnownRequestError){if(ObjError.code==="P2002")throw new ErrorAplicacion(409,"REGISTRO_DUPLICADO","Ya existe un registro con esos datos.");if(ObjError.code==="P2025")throw new ErrorAplicacion(404,"REGISTRO_NO_ENCONTRADO","El registro no existe.");}throw ObjError;}
async function Produccion_validarTipo(IntTipoId:number,BoolActivo=true){const dato=await R.Produccion_obtenerTipo(IntTipoId);if(!dato)throw new ErrorAplicacion(404,"TIPO_ANIMAL_NO_ENCONTRADO","El tipo de animal no existe.");if(BoolActivo&&!dato.activo)throw new ErrorAplicacion(409,"TIPO_ANIMAL_INACTIVO","El tipo de animal esta inactivo.");return dato;}
async function Produccion_validarRaza(IntRazaId:number|undefined|null,IntTipoId:number){if(IntRazaId==null)return;const dato=await R.Produccion_obtenerRaza(IntRazaId);if(!dato)throw new ErrorAplicacion(404,"RAZA_NO_ENCONTRADA","La raza no existe.");if(!dato.activo)throw new ErrorAplicacion(409,"RAZA_INACTIVA","La raza esta inactiva.");if(dato.tipoAnimalId!==IntTipoId)throw new ErrorAplicacion(409,"RAZA_NO_CORRESPONDE_TIPO","La raza no corresponde al tipo animal.");}
async function Produccion_validarMadre(IntMadreId:number|undefined|null,IntTipoId:number,DtNacimiento?:Date|null){if(IntMadreId==null)return;const madre=await R.Produccion_obtenerAnimal(IntMadreId);if(!madre||madre.sexo!=="HEMBRA"||madre.tipoAnimalId!==IntTipoId)throw new ErrorAplicacion(409,"MADRE_INVALIDA","La madre indicada no es valida.");if(DtNacimiento&&madre.fechaNacimiento&&madre.fechaNacimiento>=DtNacimiento)throw new ErrorAplicacion(409,"MADRE_INVALIDA","La cronologia de la madre no es valida.");}
async function Produccion_prepararAnimales<T extends {identificacion:string;tipoAnimalId:number;razaId?:number|null;madreAnimalId?:number|null;fechaNacimiento?:string|null}>(ArrAnimales:T[]){const ArrIds=new Set<string>();return Promise.all(ArrAnimales.map(async a=>{const identificacion=Produccion_canonicalizarCodigo(a.identificacion);if(ArrIds.has(identificacion))throw new ErrorAplicacion(409,"IDENTIFICACION_ANIMAL_DUPLICADA","La identificacion esta repetida en la solicitud.");ArrIds.add(identificacion);await Produccion_validarTipo(a.tipoAnimalId);await Produccion_validarRaza(a.razaId,a.tipoAnimalId);const fechaNacimiento=a.fechaNacimiento==null?a.fechaNacimiento:Fecha_parsearFechaCivil(a.fechaNacimiento);await Produccion_validarMadre(a.madreAnimalId,a.tipoAnimalId,fechaNacimiento);return{...a,identificacion,fechaNacimiento};}));}

export const Produccion_listarTipos=R.Produccion_listarTipos;export const Produccion_listarRazas=R.Produccion_listarRazas;export const Produccion_listarLotes=R.Produccion_listarLotes;export const Produccion_obtenerLote=R.Produccion_obtenerLote;export const Produccion_listarAnimales=R.Produccion_listarAnimales;export const Produccion_obtenerAnimal=R.Produccion_obtenerAnimal;export const Produccion_listarOperaciones=R.Produccion_listarOperaciones;export const Produccion_listarTransacciones=R.Produccion_listarTransacciones;export const Produccion_listarProveedores=R.Produccion_listarProveedores;
export async function Produccion_crearTipo(ObjDatos:Parameters<typeof R.Produccion_crearTipo>[0]){try{return await R.Produccion_crearTipo(ObjDatos);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_editarTipo(IntId:number,ObjDatos:Prisma.ProduccionTipoAnimalUpdateInput,IntUsuarioId:number,StrIp?:string){await Produccion_validarTipo(IntId,false);try{return await R.Produccion_editarTipo(IntId,ObjDatos,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_crearRaza(ObjDatos:Parameters<typeof R.Produccion_crearRaza>[0]){await Produccion_validarTipo(ObjDatos.tipoAnimalId);try{return await R.Produccion_crearRaza(ObjDatos);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_editarRaza(IntId:number,ObjDatos:{tipoAnimalId?:number;nombre?:string;descripcion?:string|null},IntUsuarioId:number,StrIp?:string){const actual=await R.Produccion_obtenerRaza(IntId);if(!actual)throw new ErrorAplicacion(404,"RAZA_NO_ENCONTRADA","La raza no existe.");if(ObjDatos.tipoAnimalId)await Produccion_validarTipo(ObjDatos.tipoAnimalId);try{return await R.Produccion_editarRaza(IntId,ObjDatos,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_cambiarActivo(StrEntidad:"tipo"|"raza",IntId:number,BoolActivo:boolean,IntUsuarioId:number,StrIp?:string){try{return await R.Produccion_cambiarActivo(StrEntidad,IntId,BoolActivo,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_crearLote(ObjDatos:Parameters<typeof R.Produccion_crearLote>[0]){await Produccion_validarTipo(ObjDatos.tipoAnimalId);ObjDatos.codigo=Produccion_canonicalizarCodigo(ObjDatos.codigo);try{return await R.Produccion_crearLote(ObjDatos);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_editarLote(IntId:number,ObjDatos:Prisma.ProduccionLoteUpdateInput,IntUsuarioId:number,StrIp?:string){if(!await R.Produccion_obtenerLote(IntId))throw new ErrorAplicacion(404,"LOTE_NO_ENCONTRADO","El lote no existe.");try{return await R.Produccion_editarLote(IntId,ObjDatos,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_cambiarEstadoLote(IntId:number,StrEstado:"ACTIVO"|"CERRADO",IntUsuarioId:number,StrIp?:string){try{return await R.Produccion_cambiarEstadoLote(IntId,StrEstado,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_editarAnimal(IntId:number,ObjDatos:{razaId?:number|null;sexo?:"MACHO"|"HEMBRA"|"NO_DETERMINADO";fechaNacimiento?:string|null;madreAnimalId?:number|null;observaciones?:string|null},IntUsuarioId:number,StrIp?:string){const actual=await R.Produccion_obtenerAnimal(IntId);if(!actual)throw new ErrorAplicacion(404,"ANIMAL_NO_ENCONTRADO","El animal no existe.");await Produccion_validarRaza(ObjDatos.razaId,actual.tipoAnimalId);const fecha=ObjDatos.fechaNacimiento===undefined?undefined:ObjDatos.fechaNacimiento===null?null:Fecha_parsearFechaCivil(ObjDatos.fechaNacimiento);await Produccion_validarMadre(ObjDatos.madreAnimalId,actual.tipoAnimalId,fecha);try{return await R.Produccion_editarAnimal(IntId,{...ObjDatos,...(fecha===undefined?{}:{fechaNacimiento:fecha})},IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
async function Produccion_ingresar(ObjDatos:{subtipo:"INICIAL"|"NACIMIENTO"|"COMPRA";loteDestinoId:number;proveedorId?:number;documentoReferencia?:string|null;motivo?:string|null;observaciones?:string|null;animales:Array<{identificacion:string;tipoAnimalId:number;razaId?:number|null;sexo:"MACHO"|"HEMBRA"|"NO_DETERMINADO";fechaNacimiento?:string|null;madreAnimalId?:number|null;observaciones?:string|null;costoAdquisicion?:string}>;IntUsuarioId:number;StrIp?:string}){const lote=await R.Produccion_obtenerLote(ObjDatos.loteDestinoId);if(!lote)throw new ErrorAplicacion(404,"LOTE_NO_ENCONTRADO","El lote no existe.");if(lote.estado!=="ACTIVO")throw new ErrorAplicacion(409,"LOTE_CERRADO","El lote esta cerrado.");if(ObjDatos.subtipo==="COMPRA"){const proveedor=await R.Produccion_obtenerProveedor(ObjDatos.proveedorId!);if(!proveedor)throw new ErrorAplicacion(404,"PROVEEDOR_NO_ENCONTRADO","El proveedor no existe.");if(!proveedor.activo)throw new ErrorAplicacion(409,"PROVEEDOR_INACTIVO","El proveedor esta inactivo.");}const animales=await Produccion_prepararAnimales(ObjDatos.animales);if(animales.some(a=>a.tipoAnimalId!==lote.tipoAnimalId))throw new ErrorAplicacion(409,"TIPO_LOTE_INCOMPATIBLE","El tipo del animal no corresponde al lote.");try{return await R.Produccion_registrarIngreso({...ObjDatos,animales:animales.map(a=>({...a,costoAdquisicion:a.costoAdquisicion===undefined?null:new Prisma.Decimal(a.costoAdquisicion)})) as unknown as R.ProduccionAnimalIngreso[]});}catch(e){Produccion_mapearError(e);}}
export const Produccion_registrarInicial=(ObjDatos:Omit<Parameters<typeof Produccion_ingresar>[0],"subtipo">)=>Produccion_ingresar({...ObjDatos,subtipo:"INICIAL"});
export const Produccion_registrarNacimiento=(ObjDatos:Omit<Parameters<typeof Produccion_ingresar>[0],"subtipo">)=>Produccion_ingresar({...ObjDatos,subtipo:"NACIMIENTO"});
export const Produccion_registrarCompra=(ObjDatos:Omit<Parameters<typeof Produccion_ingresar>[0],"subtipo">)=>Produccion_ingresar({...ObjDatos,subtipo:"COMPRA"});
export async function Produccion_registrarTraslado(ObjDatos:Parameters<typeof R.Produccion_registrarTraslado>[0]){try{return await R.Produccion_registrarTraslado(ObjDatos);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_registrarEstadoTerminal(IntAnimalId:number,StrEstado:"FALLECIDO"|"RETIRADO",StrMotivo:string,StrObservaciones:string|null|undefined,IntUsuarioId:number,StrIp?:string){try{return await R.Produccion_registrarEstadoTerminal(IntAnimalId,StrEstado,StrMotivo,StrObservaciones,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export async function Produccion_registrarMedicion(IntAnimalId:number,StrValor:string,StrObservaciones:string|null|undefined,IntUsuarioId:number,StrIp?:string){try{return await R.Produccion_registrarMedicion(IntAnimalId,new Prisma.Decimal(StrValor),StrObservaciones,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export function Produccion_listarMediciones(ObjDatos:{IntPagina:number;IntLimite:number;IntAnimalId?:number;StrDesde?:string;StrHasta?:string}){return R.Produccion_listarMediciones({IntPagina:ObjDatos.IntPagina,IntLimite:ObjDatos.IntLimite,...(ObjDatos.IntAnimalId===undefined?{}:{IntAnimalId:ObjDatos.IntAnimalId}),...(ObjDatos.StrDesde===undefined?{}:{DtDesde:Fecha_parsearFechaCivil(ObjDatos.StrDesde)}),...(ObjDatos.StrHasta===undefined?{}:{DtHasta:Fecha_parsearFechaCivil(ObjDatos.StrHasta)})});}
export async function Produccion_revertirOperacion(IntId:number,IntUsuarioId:number,StrIp?:string){try{return await R.Produccion_revertirOperacion(IntId,IntUsuarioId,StrIp);}catch(e){Produccion_mapearError(e);}}
export const Produccion_diagnosticar=R.Produccion_diagnosticar;
