import type { Request,Response } from "express";
import { z } from "zod";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import * as E from "./produccion.schemas.js";
import * as S from "./produccion.service.js";
function Produccion_validar<T>(ObjEsquema:z.ZodType<T>,ObjValor:unknown):T{const r=ObjEsquema.safeParse(ObjValor);if(!r.success)throw new ErrorAplicacion(400,"VALIDACION_INVALIDA","Los datos proporcionados no son validos.");return r.data;}
function Produccion_entradaServicio<T>(ObjValor:unknown):T{return ObjValor as T;}
function Produccion_actor(Req:Request){if(!Req.ObjAutenticacion)throw new ErrorAplicacion(401,"NO_AUTENTICADO","Debe iniciar sesion.");return{IntUsuarioId:Req.ObjAutenticacion.IntUsuarioId,StrIp:Req.ip};}
const Produccion_pag=(q:{pagina:number;limite:number},r:{datos:unknown;total:number})=>({datos:r.datos,paginacion:{pagina:q.pagina,limite:q.limite,total:r.total}});
export async function Produccion_listarProveedores(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaProduccion,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarProveedores(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,StrBusqueda:q.busqueda}))));}
export async function Produccion_listarTipos(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaProduccion,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarTipos(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,StrBusqueda:q.busqueda,BoolActivo:q.estado===undefined?undefined:q.estado==="ACTIVO"}))));}
export async function Produccion_crearTipo(Req:Request,Res:Response){const b=Produccion_validar(E.ObjCrearTipo,Req.body);Res.status(201).json({datos:await S.Produccion_crearTipo(Produccion_entradaServicio({...b,...Produccion_actor(Req)}))});}
export async function Produccion_editarTipo(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroTipo,Req.params),b=Produccion_validar(E.ObjEditarTipo,Req.body);Res.json({datos:await S.Produccion_editarTipo(p.tipoAnimalId,Produccion_entradaServicio(b),Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_estadoTipo(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroTipo,Req.params),b=Produccion_validar(E.ObjEstadoActivo,Req.body);Res.json({datos:await S.Produccion_cambiarActivo("tipo",p.tipoAnimalId,b.activo,Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_listarRazas(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaRazas,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarRazas(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,StrBusqueda:q.busqueda,BoolActivo:q.estado===undefined?undefined:q.estado==="ACTIVO",IntTipoAnimalId:q.tipoAnimalId}))));}
export async function Produccion_crearRaza(Req:Request,Res:Response){const b=Produccion_validar(E.ObjCrearRaza,Req.body);Res.status(201).json({datos:await S.Produccion_crearRaza(Produccion_entradaServicio({...b,...Produccion_actor(Req)}))});}
export async function Produccion_editarRaza(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroRaza,Req.params),b=Produccion_validar(E.ObjEditarRaza,Req.body);Res.json({datos:await S.Produccion_editarRaza(p.razaId,Produccion_entradaServicio(b),Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_estadoRaza(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroRaza,Req.params),b=Produccion_validar(E.ObjEstadoActivo,Req.body);Res.json({datos:await S.Produccion_cambiarActivo("raza",p.razaId,b.activo,Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_listarLotes(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaLotes,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarLotes(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,StrBusqueda:q.busqueda,StrEstado:q.estado,IntTipoAnimalId:q.tipoAnimalId}))));}
export async function Produccion_obtenerLote(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroLote,Req.params),dato=await S.Produccion_obtenerLote(p.loteProduccionId);if(!dato)throw new ErrorAplicacion(404,"LOTE_NO_ENCONTRADO","El lote no existe.");Res.json({datos:dato});}
export async function Produccion_crearLote(Req:Request,Res:Response){const b=Produccion_validar(E.ObjCrearLote,Req.body);Res.status(201).json({datos:await S.Produccion_crearLote(Produccion_entradaServicio({...b,...Produccion_actor(Req)}))});}
export async function Produccion_editarLote(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroLote,Req.params),b=Produccion_validar(E.ObjEditarLote,Req.body);Res.json({datos:await S.Produccion_editarLote(p.loteProduccionId,Produccion_entradaServicio(b),Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_estadoLote(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroLote,Req.params),b=Produccion_validar(E.ObjEstadoLote,Req.body);Res.json({datos:await S.Produccion_cambiarEstadoLote(p.loteProduccionId,b.estado,Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_listarAnimales(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaAnimales,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarAnimales(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,StrBusqueda:q.busqueda,StrEstado:q.estado,IntTipoAnimalId:q.tipoAnimalId,IntRazaId:q.razaId,IntLoteId:q.loteProduccionId,StrSexo:q.sexo}))));}
export async function Produccion_obtenerAnimal(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroAnimal,Req.params),dato=await S.Produccion_obtenerAnimal(p.animalId);if(!dato)throw new ErrorAplicacion(404,"ANIMAL_NO_ENCONTRADO","El animal no existe.");Res.json({datos:dato});}
export async function Produccion_editarAnimal(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroAnimal,Req.params),b=Produccion_validar(E.ObjEditarAnimal,Req.body);Res.json({datos:await S.Produccion_editarAnimal(p.animalId,Produccion_entradaServicio(b),Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_inicial(Req:Request,Res:Response){const b=Produccion_validar(E.ObjIngresoInicial,Req.body);Res.status(201).json({datos:await S.Produccion_registrarInicial(Produccion_entradaServicio({...b,...Produccion_actor(Req)}))});}
export async function Produccion_nacimiento(Req:Request,Res:Response){const b=Produccion_validar(E.ObjNacimiento,Req.body);Res.status(201).json({datos:await S.Produccion_registrarNacimiento(Produccion_entradaServicio({...b,...Produccion_actor(Req)}))});}
export async function Produccion_compra(Req:Request,Res:Response){const b=Produccion_validar(E.ObjCompra,Req.body);Res.status(201).json({datos:await S.Produccion_registrarCompra(Produccion_entradaServicio({...b,...Produccion_actor(Req)}))});}
export async function Produccion_traslado(Req:Request,Res:Response){const b=Produccion_validar(E.ObjTraslado,Req.body);Res.status(201).json({datos:await S.Produccion_registrarTraslado(Produccion_entradaServicio({...b,...Produccion_actor(Req)}))});}
export async function Produccion_estadoAnimal(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroAnimal,Req.params),b=Produccion_validar(E.ObjEstadoTerminal,Req.body);Res.status(201).json({datos:await S.Produccion_registrarEstadoTerminal(p.animalId,b.estado,b.motivo,b.observaciones,Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_listarMediciones(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaMediciones,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarMediciones(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,IntAnimalId:q.animalId,StrDesde:q.fechaDesde,StrHasta:q.fechaHasta}))));}
export async function Produccion_medicion(Req:Request,Res:Response){const b=Produccion_validar(E.ObjCrearMedicion,Req.body);Res.status(201).json({datos:await S.Produccion_registrarMedicion(b.animalId,b.valor,b.observaciones,Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_listarOperaciones(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaOperaciones,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarOperaciones(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,StrTipo:q.tipo,StrSubtipo:q.subtipo,IntLoteId:q.loteProduccionId,IntAnimalId:q.animalId}))));}
export async function Produccion_listarTransacciones(Req:Request,Res:Response){const q=Produccion_validar(E.ObjConsultaOperaciones,Req.query);Res.json(Produccion_pag(q,await S.Produccion_listarTransacciones(Produccion_entradaServicio({IntPagina:q.pagina,IntLimite:q.limite,StrTipo:q.tipo,IntLoteId:q.loteProduccionId}))));}
export async function Produccion_revertir(Req:Request,Res:Response){const p=Produccion_validar(E.ObjParametroOperacion,Req.params);Produccion_validar(E.ObjCuerpoVacio,Req.body??{});Res.status(201).json({datos:await S.Produccion_revertirOperacion(p.operacionProduccionId,Produccion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Produccion_diagnostico(Req:Request,Res:Response){Produccion_validar(E.ObjCuerpoVacio,Req.body??{});Res.json({datos:await S.Produccion_diagnosticar(Produccion_actor(Req).IntUsuarioId,Req.ip)});}
