import { Prisma } from "../../../generated/prisma/client.js";
import { BaseDatos_obtenerCliente } from "../../database/prisma.js";
import { Fecha_formatearFechaCivil, Fecha_obtenerAhoraGuatemala } from "../../datetime/fecha.js";
import { Inventario_aplicarMovimientoConTx,Inventario_revertirMovimientoConTx } from "../inventario/inventario.repository.js";

export type AlimentacionDetalleEntrada={productoId:number;inventarioId:number;loteInventarioId?:number|null;cantidad:Prisma.Decimal};
export type AlimentacionRegistroEntrada={formulaId?:number|null|undefined;fechaEfectiva:Date;animalId?:number|null|undefined;loteProduccionId?:number|null|undefined;observaciones?:string|null|undefined;detalles:AlimentacionDetalleEntrada[];IntUsuarioId:number;StrIp?:string|undefined};
const ObjDetalleInclude={producto:true,existencia:{include:{almacen:true}},existenciaLote:{include:{lote:true,existencia:{include:{almacen:true}}}},inventarioTransacciones:true} satisfies Prisma.AlimentacionDetalleInclude;

export async function Alimentacion_listar(Obj:{IntPagina:number;IntLimite:number;StrBusqueda?:string;StrEstado?:string;StrDestino?:string;IntAnimalId?:number;IntLoteId?:number;IntFormulaId?:number;DtDesde?:Date;DtHasta?:Date}){
 const ObjPrisma=BaseDatos_obtenerCliente();let ArrIds:number[]|undefined;
 if(Obj.StrBusqueda){const Arr=await ObjPrisma.$queryRaw<Array<{alimentacionId:number}>>`SELECT DISTINCT r.alimentacion_id alimentacionId FROM dbo.alimentacion_registros r LEFT JOIN dbo.produccion_asignaciones_lotes al ON al.lote_produccion_id=r.lote_produccion_id AND al.fecha_inicio<=r.fecha_alimentacion AND (al.fecha_fin IS NULL OR r.fecha_alimentacion<al.fecha_fin) LEFT JOIN dbo.produccion_animales a ON a.animal_id=COALESCE(r.animal_id,al.animal_id) LEFT JOIN dbo.produccion_lotes l ON l.lote_produccion_id=r.lote_produccion_id WHERE a.identificacion LIKE ${`%${Obj.StrBusqueda}%`} OR l.codigo LIKE ${`%${Obj.StrBusqueda}%`}`;ArrIds=Arr.map(x=>x.alimentacionId);}
 const where:Prisma.AlimentacionRegistroWhereInput={...(ArrIds?{alimentacionId:{in:ArrIds}}:{}),...(Obj.StrEstado?{estado:Obj.StrEstado}:{}),...(Obj.StrDestino==="ANIMAL"?{animalId:{not:null}}:Obj.StrDestino==="LOTE"?{loteProduccionId:{not:null}}:{}),...(Obj.IntAnimalId?{animalId:Obj.IntAnimalId}:{}),...(Obj.IntLoteId?{loteProduccionId:Obj.IntLoteId}:{}),...(Obj.IntFormulaId?{formulaId:Obj.IntFormulaId}:{}),...((Obj.DtDesde||Obj.DtHasta)?{fechaAlimentacion:{...(Obj.DtDesde?{gte:Obj.DtDesde}:{}),...(Obj.DtHasta?{lte:Obj.DtHasta}:{})}}:{})};
 const include={animal:{select:{animalId:true,identificacion:true}},lote:{select:{loteProduccionId:true,codigo:true,nombre:true}},formula:{select:{formulaId:true,nombre:true}},usuario:{select:{usuarioId:true,nombreCompleto:true}},detalles:{include:ObjDetalleInclude}} satisfies Prisma.AlimentacionRegistroInclude;
 const [datos,total]=await ObjPrisma.$transaction([ObjPrisma.alimentacionRegistro.findMany({where,include,orderBy:{alimentacionId:"desc"},skip:(Obj.IntPagina-1)*Obj.IntLimite,take:Obj.IntLimite}),ObjPrisma.alimentacionRegistro.count({where})]);return{datos,total};
}
export const Alimentacion_obtener=(IntId:number)=>BaseDatos_obtenerCliente().alimentacionRegistro.findUnique({where:{alimentacionId:IntId},include:{animal:true,lote:true,formula:true,usuario:true,usuarioReversion:true,detalles:{include:ObjDetalleInclude},eventos:true}});
export async function Alimentacion_registrar(Obj:AlimentacionRegistroEntrada){return BaseDatos_obtenerCliente().$transaction(async ObjTx=>{
 const ObjRegistro=await ObjTx.alimentacionRegistro.create({data:{formulaId:Obj.formulaId??null,animalId:Obj.animalId??null,loteProduccionId:Obj.loteProduccionId??null,usuarioId:Obj.IntUsuarioId,fechaAlimentacion:Obj.fechaEfectiva,observaciones:Obj.observaciones??null}});
 for(const ObjLinea of Obj.detalles){const ObjProducto=await ObjTx.inventarioProducto.findUnique({where:{productoId:ObjLinea.productoId},include:{habilitacionAlimentacion:true}});if(!ObjProducto||!ObjProducto.activo)throw new Error("PRODUCTO_INACTIVO");if(!ObjProducto.habilitacionAlimentacion?.activo)throw new Error("PRODUCTO_NO_HABILITADO");let IntExistenciaLoteId:number|undefined;
  if(ObjProducto.manejaLotes){if(!ObjLinea.loteInventarioId)throw new Error("PRODUCTO_REQUIERE_LOTE");const ObjFuente=await ObjTx.inventarioExistenciaLote.findFirst({where:{loteInventarioId:ObjLinea.loteInventarioId,productoId:ObjLinea.productoId,existencia:{inventarioId:ObjLinea.inventarioId}},include:{lote:true}});if(!ObjFuente)throw new Error("FUENTE_INVENTARIO_INCONSISTENTE");if(!ObjFuente.lote.activo)throw new Error("LOTE_INACTIVO");const StrFecha=Fecha_formatearFechaCivil(Obj.fechaEfectiva);if(ObjFuente.lote.fechaVencimiento&&Fecha_formatearFechaCivil(ObjFuente.lote.fechaVencimiento)<StrFecha)throw new Error("LOTE_VENCIDO");IntExistenciaLoteId=ObjFuente.existenciaLoteId;}else if(ObjLinea.loteInventarioId)throw new Error("PRODUCTO_NO_MANEJA_LOTES");
  const ObjDetalle=await ObjTx.alimentacionDetalle.create({data:{alimentacionId:ObjRegistro.alimentacionId,productoId:ObjLinea.productoId,inventarioId:ObjProducto.manejaLotes?null:ObjLinea.inventarioId,existenciaLoteId:IntExistenciaLoteId??null,cantidadConsumida:ObjLinea.cantidad,unidadMedida:ObjProducto.unidadMedida}});
  await Inventario_aplicarMovimientoConTx(ObjTx,{tipo:"SALIDA",subtipo:"ALIMENTACION",productoId:ObjLinea.productoId,inventarioId:ObjLinea.inventarioId,loteInventarioId:ObjLinea.loteInventarioId??undefined,cantidad:ObjLinea.cantidad.negated(),IntUsuarioId:Obj.IntUsuarioId,animalId:Obj.animalId??null,loteProduccionId:Obj.loteProduccionId??null,alimentacionDetalleId:ObjDetalle.detalleAlimentacionId,StrIp:Obj.StrIp});}
 await ObjTx.produccionEvento.create({data:{animalId:Obj.animalId??null,loteProduccionId:Obj.loteProduccionId??null,usuarioId:Obj.IntUsuarioId,alimentacionId:ObjRegistro.alimentacionId,tipoEvento:"ALIMENTACION",fechaEvento:Obj.fechaEfectiva,descripcion:`Alimentacion ${ObjRegistro.alimentacionId}.`}});await ObjTx.usuarioBitacora.create({data:{usuarioId:Obj.IntUsuarioId,modulo:"ALIMENTACION",accion:"ALIMENTACION_REGISTRADA",descripcion:`Alimentacion ${ObjRegistro.alimentacionId}; destino ${Obj.animalId?`animal ${Obj.animalId}`:`lote ${Obj.loteProduccionId}`}.`,resultado:"EXITO",direccionIp:Obj.StrIp??null}});return ObjRegistro;
 },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function Alimentacion_revertir(IntId:number,StrMotivo:string,IntUsuarioId:number,StrIp?:string){return BaseDatos_obtenerCliente().$transaction(async ObjTx=>{const ObjRegistro=await ObjTx.alimentacionRegistro.findUnique({where:{alimentacionId:IntId},include:{detalles:{include:{inventarioTransacciones:{include:{reversion:true}}}}}});if(!ObjRegistro)throw new Error("ALIMENTACION_NO_ENCONTRADA");if(ObjRegistro.estado==="REVERTIDA")throw new Error("ALIMENTACION_YA_REVERTIDA");const DtAhora=Fecha_obtenerAhoraGuatemala();for(const ObjDetalle of ObjRegistro.detalles){const ObjMovimiento=ObjDetalle.inventarioTransacciones.find(x=>x.subtipoTransaccion==="ALIMENTACION"&&x.transaccionRevertidaId===null);if(!ObjMovimiento||ObjMovimiento.reversion)throw new Error("ALIMENTACION_INCONSISTENTE");await Inventario_revertirMovimientoConTx(ObjTx,ObjMovimiento,IntUsuarioId,DtAhora);}await ObjTx.alimentacionRegistro.update({where:{alimentacionId:IntId},data:{estado:"REVERTIDA",usuarioReversionId:IntUsuarioId,fechaReversion:DtAhora,motivoReversion:StrMotivo}});await ObjTx.usuarioBitacora.create({data:{usuarioId:IntUsuarioId,modulo:"ALIMENTACION",accion:"ALIMENTACION_REVERTIDA",descripcion:`Alimentacion ${IntId}.`,resultado:"EXITO",direccionIp:StrIp??null}});return{alimentacionId:IntId,estado:"REVERTIDA",fechaReversion:DtAhora};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function Alimentacion_gestionarProducto(IntProductoId:number,BoolActivo:boolean){return BaseDatos_obtenerCliente().alimentacionProductoHabilitado.upsert({where:{productoId:IntProductoId},create:{productoId:IntProductoId,activo:BoolActivo},update:{activo:BoolActivo,fechaActualizacion:Fecha_obtenerAhoraGuatemala()}});}
export const Alimentacion_listarProductos=()=>BaseDatos_obtenerCliente().inventarioProducto.findMany({include:{habilitacionAlimentacion:true},orderBy:{productoId:"asc"}});
export const Alimentacion_listarFormulas=()=>BaseDatos_obtenerCliente().alimentacionFormula.findMany({include:{detalles:{include:{producto:true}}},orderBy:{formulaId:"asc"}});
export async function Alimentacion_buscarDestinosAnimales(Obj:{StrBusqueda?:string;IntPagina:number;IntLimite:number}){const P=BaseDatos_obtenerCliente();const where:Prisma.ProduccionAnimalWhereInput={estadoActual:"ACTIVO",...(Obj.StrBusqueda?{identificacion:{contains:Obj.StrBusqueda}}:{}),asignaciones:{some:{estado:"VIGENTE",lote:{estado:"ACTIVO"}}}};const select={animalId:true,identificacion:true,sexo:true,tipoAnimal:{select:{tipoAnimalId:true,nombre:true}},asignaciones:{where:{estado:"VIGENTE",lote:{estado:"ACTIVO"}},take:1,select:{lote:{select:{loteProduccionId:true,codigo:true,nombre:true}}}}} satisfies Prisma.ProduccionAnimalSelect;const[datos,total]=await P.$transaction([P.produccionAnimal.findMany({where,select,orderBy:{identificacion:"asc"},skip:(Obj.IntPagina-1)*Obj.IntLimite,take:Obj.IntLimite}),P.produccionAnimal.count({where})]);return{datos:datos.map(({asignaciones,...a})=>({...a,loteVigente:asignaciones[0]!.lote})),total};}
export async function Alimentacion_buscarDestinosLotes(Obj:{StrBusqueda?:string;IntPagina:number;IntLimite:number}){const P=BaseDatos_obtenerCliente();const where:Prisma.ProduccionLoteWhereInput={estado:"ACTIVO",...(Obj.StrBusqueda?{OR:[{codigo:{contains:Obj.StrBusqueda}},{nombre:{contains:Obj.StrBusqueda}}]}:{}),asignaciones:{some:{estado:"VIGENTE",animal:{estadoActual:"ACTIVO"}}}};const select={loteProduccionId:true,codigo:true,nombre:true,tipoAnimal:{select:{tipoAnimalId:true,nombre:true}},_count:{select:{asignaciones:{where:{estado:"VIGENTE",animal:{estadoActual:"ACTIVO"}}}}}} satisfies Prisma.ProduccionLoteSelect;const[datos,total]=await P.$transaction([P.produccionLote.findMany({where,select,orderBy:{codigo:"asc"},skip:(Obj.IntPagina-1)*Obj.IntLimite,take:Obj.IntLimite}),P.produccionLote.count({where})]);return{datos:datos.map(({_count,...l})=>({...l,cantidadAnimalesVigentes:_count.asignaciones})),total};}
export function Alimentacion_buscarAlmacenes(StrBusqueda?:string){return BaseDatos_obtenerCliente().inventarioAlmacen.findMany({where:{activo:true,...(StrBusqueda?{OR:[{codigo:{contains:StrBusqueda}},{nombre:{contains:StrBusqueda}}]}:{})},select:{inventarioId:true,codigo:true,nombre:true},orderBy:{codigo:"asc"}});}
export function Alimentacion_buscarExistencias(IntProductoId:number,IntInventarioId?:number){return BaseDatos_obtenerCliente().inventarioExistencia.findMany({where:{productoId:IntProductoId,...(IntInventarioId?{inventarioId:IntInventarioId}:{}),activo:true,almacen:{activo:true},producto:{activo:true,habilitacionAlimentacion:{activo:true}}},select:{inventarioId:true,productoId:true,existenciaActual:true,costoPromedioActual:true,almacen:{select:{codigo:true,nombre:true}},producto:{select:{manejaLotes:true,unidadMedida:true}}},orderBy:{inventarioId:"asc"}});}
export function Alimentacion_buscarLotesInventario(IntProductoId:number,IntInventarioId:number,DtFecha?:Date){return BaseDatos_obtenerCliente().inventarioExistenciaLote.findMany({where:{productoId:IntProductoId,existenciaActual:{gt:0},existencia:{inventarioId:IntInventarioId,activo:true,almacen:{activo:true},producto:{activo:true,manejaLotes:true,habilitacionAlimentacion:{activo:true}}},lote:{activo:true,...(DtFecha?{OR:[{fechaVencimiento:null},{fechaVencimiento:{gte:DtFecha}}]}:{})}},select:{loteInventarioId:true,existenciaActual:true,lote:{select:{codigoLote:true,fechaVencimiento:true,costoUnitario:true,activo:true}}},orderBy:{lote:{codigoLote:"asc"}}});}
export async function Alimentacion_guardarFormula(IntId:number|null,Obj:{nombre:string;descripcion?:string|null;cantidadBase:Prisma.Decimal;unidadBase:string;detalles:Array<{productoId:number;cantidad:Prisma.Decimal}>}){return BaseDatos_obtenerCliente().$transaction(async Tx=>{for(const d of Obj.detalles){const h=await Tx.alimentacionProductoHabilitado.findUnique({where:{productoId:d.productoId}});if(!h?.activo)throw new Error("PRODUCTO_NO_HABILITADO");}const f=IntId===null?await Tx.alimentacionFormula.create({data:{nombre:Obj.nombre,descripcion:Obj.descripcion??null,cantidadBase:Obj.cantidadBase,unidadBase:Obj.unidadBase}}):await Tx.alimentacionFormula.update({where:{formulaId:IntId},data:{nombre:Obj.nombre,descripcion:Obj.descripcion??null,cantidadBase:Obj.cantidadBase,unidadBase:Obj.unidadBase,fechaActualizacion:Fecha_obtenerAhoraGuatemala()}});await Tx.alimentacionFormulaDetalle.updateMany({where:{formulaId:f.formulaId},data:{activo:false,fechaActualizacion:Fecha_obtenerAhoraGuatemala()}});for(const d of Obj.detalles)await Tx.alimentacionFormulaDetalle.upsert({where:{formulaId_productoId:{formulaId:f.formulaId,productoId:d.productoId}},create:{formulaId:f.formulaId,productoId:d.productoId,cantidad:d.cantidad,unidadMedida:(await Tx.inventarioProducto.findUniqueOrThrow({where:{productoId:d.productoId}})).unidadMedida},update:{cantidad:d.cantidad,activo:true,fechaActualizacion:Fecha_obtenerAhoraGuatemala()}});return f;});}
export const Alimentacion_estadoFormula=(IntId:number,BoolActivo:boolean)=>BaseDatos_obtenerCliente().alimentacionFormula.update({where:{formulaId:IntId},data:{activo:BoolActivo,fechaActualizacion:Fecha_obtenerAhoraGuatemala()}});
export async function Alimentacion_diagnosticar(IntUsuarioId:number){const P=BaseDatos_obtenerCliente();const [sinMovimiento,movimientoHuerfano,eventosFaltantes]=await Promise.all([P.alimentacionDetalle.count({where:{inventarioTransacciones:{none:{subtipoTransaccion:"ALIMENTACION"}}}}),P.inventarioTransaccion.count({where:{subtipoTransaccion:"ALIMENTACION",alimentacionDetalleId:null}}),P.alimentacionRegistro.count({where:{eventos:{none:{tipoEvento:"ALIMENTACION"}}}})]);return{fechaDiagnostico:Fecha_obtenerAhoraGuatemala(),consistente:sinMovimiento+movimientoHuerfano+eventosFaltantes===0,diferencias:{detallesSinMovimiento:sinMovimiento,movimientosHuerfanos:movimientoHuerfano,registrosSinEvento:eventosFaltantes},usuarioId:IntUsuarioId};}
