import type { Request, Response } from "express";
import { z } from "zod";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import * as E from "./alimentacion.schemas.js";
import * as S from "./alimentacion.service.js";
function Alimentacion_validar<T>(ObjEsquema:z.ZodType<T>,ObjValor:unknown):T{const ObjResultado=ObjEsquema.safeParse(ObjValor);if(!ObjResultado.success)throw new ErrorAplicacion(400,"VALIDACION_INVALIDA","Los datos proporcionados no son válidos.");return ObjResultado.data;}
function Alimentacion_actor(Req:Request){if(!Req.ObjAutenticacion)throw new ErrorAplicacion(401,"NO_AUTENTICADO","Debe iniciar sesión.");return{IntUsuarioId:Req.ObjAutenticacion.IntUsuarioId,StrIp:Req.ip};}
export async function Alimentacion_listar(Req:Request,Res:Response){const q=Alimentacion_validar(E.ObjConsulta,Req.query);const ObjEntrada={IntPagina:q.pagina,IntLimite:q.limite,...(q.busqueda===undefined?{}:{StrBusqueda:q.busqueda}),...(q.estado===undefined?{}:{StrEstado:q.estado}),...(q.destino===undefined?{}:{StrDestino:q.destino}),...(q.animalId===undefined?{}:{IntAnimalId:q.animalId}),...(q.loteProduccionId===undefined?{}:{IntLoteId:q.loteProduccionId}),...(q.formulaId===undefined?{}:{IntFormulaId:q.formulaId}),...(q.fechaDesde===undefined?{}:{StrDesde:q.fechaDesde}),...(q.fechaHasta===undefined?{}:{StrHasta:q.fechaHasta})};const x=await S.Alimentacion_listar(ObjEntrada);Res.json({datos:x.datos,paginacion:{pagina:q.pagina,limite:q.limite,total:x.total}});}
export async function Alimentacion_obtener(Req:Request,Res:Response){const p=Alimentacion_validar(E.ObjParametroAlimentacion,Req.params),d=await S.Alimentacion_obtener(p.alimentacionId);if(!d)throw new ErrorAplicacion(404,"ALIMENTACION_NO_ENCONTRADA","La alimentación no existe.");Res.json({datos:d});}
export async function Alimentacion_registrar(Req:Request,Res:Response){const b=Alimentacion_validar(E.ObjRegistrar,Req.body);const ObjEntrada={...b,...Alimentacion_actor(Req)} as Parameters<typeof S.Alimentacion_registrar>[0];Res.status(201).json({datos:await S.Alimentacion_registrar(ObjEntrada)});}
export async function Alimentacion_revertir(Req:Request,Res:Response){const p=Alimentacion_validar(E.ObjParametroAlimentacion,Req.params),b=Alimentacion_validar(E.ObjRevertir,Req.body);Res.status(201).json({datos:await S.Alimentacion_revertir(p.alimentacionId,b.motivo,Alimentacion_actor(Req).IntUsuarioId,Req.ip)});}
export async function Alimentacion_productos(_Req:Request,Res:Response){Res.json({datos:await S.Alimentacion_listarProductos()});}
export async function Alimentacion_habilitar(Req:Request,Res:Response){const p=Alimentacion_validar(E.ObjParametroProducto,Req.params),b=Alimentacion_validar(E.ObjEstado,Req.body);Res.json({datos:await S.Alimentacion_gestionarProducto(p.productoId,b.activo)});}
export async function Alimentacion_formulas(_Req:Request,Res:Response){Res.json({datos:await S.Alimentacion_listarFormulas()});}
export async function Alimentacion_crearFormula(Req:Request,Res:Response){const b=Alimentacion_validar(E.ObjFormula,Req.body);Res.status(201).json({datos:await S.Alimentacion_guardarFormula(null,b as Parameters<typeof S.Alimentacion_guardarFormula>[1])});}
export async function Alimentacion_editarFormula(Req:Request,Res:Response){const p=Alimentacion_validar(E.ObjParametroFormula,Req.params),b=Alimentacion_validar(E.ObjFormulaEditar,Req.body);Res.json({datos:await S.Alimentacion_guardarFormula(p.formulaId,b as never)});}
export async function Alimentacion_estadoFormula(Req:Request,Res:Response){const p=Alimentacion_validar(E.ObjParametroFormula,Req.params),b=Alimentacion_validar(E.ObjEstado,Req.body);Res.json({datos:await S.Alimentacion_estadoFormula(p.formulaId,b.activo)});}
export async function Alimentacion_diagnostico(Req:Request,Res:Response){Alimentacion_validar(E.ObjCuerpoVacio,Req.body??{});Res.json({datos:await S.Alimentacion_diagnosticar(Alimentacion_actor(Req).IntUsuarioId)});}
