import { Prisma } from "../../../generated/prisma/client.js";
import { Fecha_convertirAlmacenamientoGuatemalaAInstante,Fecha_formatearInstanteGuatemala,Fecha_parsearFechaCivil,Fecha_parsearFechaHoraGuatemala } from "../../datetime/fecha.js";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import * as R from "./alimentacion.repository.js";
const ObjErrores:Record<string,[number,string]>={ALIMENTACION_NO_ENCONTRADA:[404,"La alimentación no existe."],ALIMENTACION_YA_REVERTIDA:[409,"La alimentación ya fue revertida."],ALIMENTACION_INCONSISTENTE:[409,"La alimentación no conserva referencias consistentes."],PRODUCTO_NO_HABILITADO:[409,"El producto no está habilitado para alimentación."],PRODUCTO_INACTIVO:[409,"El producto está inactivo."],PRODUCTO_REQUIERE_LOTE:[409,"Debe seleccionar un lote de inventario."],PRODUCTO_NO_MANEJA_LOTES:[409,"El producto no maneja lotes."],FUENTE_INVENTARIO_INCONSISTENTE:[409,"La fuente física seleccionada no es coherente."],LOTE_INACTIVO:[409,"El lote de inventario está inactivo."],LOTE_VENCIDO:[409,"El lote estaba vencido en la fecha efectiva."],STOCK_INSUFICIENTE:[409,"No existe stock suficiente."],COSTO_PROMEDIO_NO_DISPONIBLE:[409,"La existencia no tiene costo promedio disponible."]};
function Alimentacion_error(ObjError:unknown):never{if(ObjError instanceof Error&&ObjErrores[ObjError.message]){const[IntEstado,StrMensaje]=ObjErrores[ObjError.message]!;throw new ErrorAplicacion(IntEstado,ObjError.message,StrMensaje);}if(ObjError instanceof Prisma.PrismaClientKnownRequestError&&ObjError.code==="P2002")throw new ErrorAplicacion(409,"REGISTRO_DUPLICADO","Ya existe un registro con esos datos.");throw ObjError;}
export function Alimentacion_formatearRespuesta<T>(Obj:T):T{if(Obj instanceof Date)return Fecha_formatearInstanteGuatemala(Fecha_convertirAlmacenamientoGuatemalaAInstante(Obj)) as T;if(Array.isArray(Obj))return Obj.map(Alimentacion_formatearRespuesta) as T;if(Obj&&typeof Obj==="object"&&!(Obj instanceof Prisma.Decimal))return Object.fromEntries(Object.entries(Obj).map(([k,v])=>[k,Alimentacion_formatearRespuesta(v)])) as T;return Obj;}
export function Alimentacion_listar(Obj:{IntPagina:number;IntLimite:number;StrBusqueda?:string;StrEstado?:string;StrDestino?:string;IntAnimalId?:number;IntLoteId?:number;IntFormulaId?:number;StrDesde?:string;StrHasta?:string}){return R.Alimentacion_listar({...Obj,...(Obj.StrDesde?{DtDesde:Fecha_parsearFechaCivil(Obj.StrDesde)}:{}),...(Obj.StrHasta?{DtHasta:Fecha_parsearFechaCivil(Obj.StrHasta)}:{})});}
export const Alimentacion_obtener=R.Alimentacion_obtener;
export async function Alimentacion_registrar(Obj:{formulaId?:number|null;fechaEfectiva:string;destino:{tipo:"ANIMAL";animalId:number}|{tipo:"LOTE";loteProduccionId:number};observaciones?:string|null;detalles:Array<{productoId:number;inventarioId:number;loteInventarioId?:number|null;cantidad:string}>;IntUsuarioId:number;StrIp?:string}){const DtFecha=Fecha_parsearFechaHoraGuatemala(Obj.fechaEfectiva);const P=(await import("../../database/prisma.js")).BaseDatos_obtenerCliente();if(Obj.destino.tipo==="ANIMAL"){const a=await P.produccionAnimal.findUnique({where:{animalId:Obj.destino.animalId},include:{asignaciones:{where:{estado:"VIGENTE"}}}});if(!a||a.estadoActual!=="ACTIVO"||a.asignaciones.length!==1)throw new ErrorAplicacion(409,"DESTINO_ANIMAL_INVALIDO","El animal no está activo con asignación vigente.");}else{const l=await P.produccionLote.findUnique({where:{loteProduccionId:Obj.destino.loteProduccionId},include:{asignaciones:{where:{estado:"VIGENTE"}}}});if(!l||l.estado!=="ACTIVO"||l.asignaciones.length===0)throw new ErrorAplicacion(409,"DESTINO_LOTE_INVALIDO","El lote no está activo o no tiene animales vigentes.");}try{return await R.Alimentacion_registrar({formulaId:Obj.formulaId,fechaEfectiva:DtFecha,...(Obj.destino.tipo==="ANIMAL"?{animalId:Obj.destino.animalId}:{loteProduccionId:Obj.destino.loteProduccionId}),observaciones:Obj.observaciones,detalles:Obj.detalles.map(d=>({...d,cantidad:new Prisma.Decimal(d.cantidad)})),IntUsuarioId:Obj.IntUsuarioId,StrIp:Obj.StrIp});}catch(e){Alimentacion_error(e);}}
export async function Alimentacion_revertir(...Arr:Parameters<typeof R.Alimentacion_revertir>){try{return await R.Alimentacion_revertir(...Arr);}catch(e){Alimentacion_error(e);}}
export const Alimentacion_listarProductos=R.Alimentacion_listarProductos;export const Alimentacion_gestionarProducto=R.Alimentacion_gestionarProducto;export const Alimentacion_listarFormulas=R.Alimentacion_listarFormulas;export const Alimentacion_estadoFormula=R.Alimentacion_estadoFormula;export const Alimentacion_diagnosticar=R.Alimentacion_diagnosticar;
export function Alimentacion_guardarFormula(IntId:number|null,Obj:{nombre:string;descripcion?:string|null;cantidadBase?:string;unidadBase?:string;detalles?:Array<{productoId:number;cantidad:string}>}){if(!Obj.cantidadBase||!Obj.unidadBase||!Obj.detalles)throw new ErrorAplicacion(400,"VALIDACION_INVALIDA","La fórmula debe enviarse completa.");return R.Alimentacion_guardarFormula(IntId,{nombre:Obj.nombre,...(Obj.descripcion===undefined?{}:{descripcion:Obj.descripcion}),cantidadBase:new Prisma.Decimal(Obj.cantidadBase),unidadBase:Obj.unidadBase,detalles:Obj.detalles.map(d=>({...d,cantidad:new Prisma.Decimal(d.cantidad)}))});}
