import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { IndicadorCarga } from "../../components/ui/IndicadorCarga";
import { MensajeError } from "../../components/ui/MensajeError";
import { Modal } from "../../components/ui/Modal";
import { useSesion } from "../../hooks/useSesion";
import * as S from "../../services/produccion.service";
import type { FichaTecnicaAnimal } from "../../types/produccion.types";
import { ErrorApi } from "../../types/api.types";
import { Produccion_crearModeloFicha, Produccion_generarFichaPdf } from "../../utils/produccion-ficha";

type EstadoFoto="cargando"|"visible"|"sin"|"error";

export function PaginaFichaTecnicaAnimal(){
  const {animalId}=useParams();const IntAnimalId=Number(animalId);const{Autenticacion_tienePermiso}=useSesion();
  const[ObjFicha,establecerFicha]=useState<FichaTecnicaAnimal|null>(null),[StrError,establecerError]=useState<string|null>(null),[BoolCargando,establecerCargando]=useState(true);
  const[StrFotoUrl,establecerFotoUrl]=useState<string|null>(null),[ObjFoto,establecerFoto]=useState<Blob|null>(null),[StrEstadoFoto,establecerEstadoFoto]=useState<EstadoFoto>("sin"),[StrErrorFoto,establecerErrorFoto]=useState<string|null>(null),[BoolGuardandoFoto,establecerGuardandoFoto]=useState(false),[BoolGenerandoPdf,establecerGenerandoPdf]=useState(false),[BoolFotoAmpliada,establecerFotoAmpliada]=useState(false);const RefFotoUrl=useRef<string|null>(null);
  const Produccion_cargarFoto=useCallback(async()=>{establecerEstadoFoto("cargando");establecerErrorFoto(null);try{const ObjBlob=await S.Produccion_obtenerFoto(IntAnimalId);if(!ObjBlob){establecerFoto(null);establecerFotoUrl(null);establecerFicha(ObjActual=>ObjActual?{...ObjActual,tieneFoto:false}:ObjActual);establecerEstadoFoto("sin");return;}const StrUrl=URL.createObjectURL(ObjBlob);if(RefFotoUrl.current)URL.revokeObjectURL(RefFotoUrl.current);RefFotoUrl.current=StrUrl;establecerFoto(ObjBlob);establecerFotoUrl(StrUrl);establecerEstadoFoto("visible");}catch(ObjError){establecerFoto(null);establecerFotoUrl(null);establecerEstadoFoto("error");establecerErrorFoto(ObjError instanceof ErrorApi&&ObjError.IntEstadoHttp===503?"Fotografía no disponible":"No fue posible cargar la fotografía.");}},[IntAnimalId]);
  useEffect(()=>{if(!Number.isInteger(IntAnimalId)||IntAnimalId<=0){establecerError("El animal solicitado no es válido.");establecerCargando(false);return;}void S.Produccion_obtenerFichaTecnica(IntAnimalId).then(Obj=>{establecerFicha(Obj.datos);if(Obj.datos.tieneFoto)void Produccion_cargarFoto();else establecerEstadoFoto("sin");}).catch(ObjError=>establecerError(ObjError instanceof Error?ObjError.message:"No fue posible cargar la ficha técnica.")).finally(()=>establecerCargando(false));return()=>{if(RefFotoUrl.current)URL.revokeObjectURL(RefFotoUrl.current);};},[IntAnimalId,Produccion_cargarFoto]);
  const ObjModelo=useMemo(()=>ObjFicha?Produccion_crearModeloFicha(ObjFicha):null,[ObjFicha]);
  async function Produccion_cambiarFoto(ObjArchivo:File|undefined){if(!ObjArchivo)return;establecerGuardandoFoto(true);establecerErrorFoto(null);try{await S.Produccion_reemplazarFoto(IntAnimalId,ObjArchivo);establecerFicha(ObjActual=>ObjActual?{...ObjActual,tieneFoto:true}:ObjActual);await Produccion_cargarFoto();}catch(ObjError){establecerErrorFoto(ObjError instanceof Error?ObjError.message:"No fue posible guardar la fotografía.");}finally{establecerGuardandoFoto(false);}}
  async function Produccion_descargarPdf(){if(!ObjFicha)return;establecerGenerandoPdf(true);try{let ObjFotoPdf=ObjFoto;if(ObjFicha.tieneFoto&&!ObjFotoPdf){try{ObjFotoPdf=await S.Produccion_obtenerFoto(IntAnimalId);}catch{ObjFotoPdf=null;}}await Produccion_generarFichaPdf(ObjFicha,ObjFotoPdf);}finally{establecerGenerandoPdf(false);}}
  if(BoolCargando)return <IndicadorCarga StrMensaje="Cargando ficha técnica…"/>;if(StrError||!ObjFicha||!ObjModelo)return <div className="produccion-contenido"><MensajeError StrMensaje={StrError??"No fue posible cargar la ficha técnica."}/><Link to="/produccion/animales">Volver a animales</Link></div>;
  return <article className="produccion-ficha">
    <div className="produccion-ficha-acciones no-imprimir"><Link className="enlace-boton" to="/produccion/animales">Volver</Link><button onClick={()=>window.print()}>Imprimir</button><button className="boton-primario" disabled={BoolGenerandoPdf} onClick={()=>void Produccion_descargarPdf()}>{BoolGenerandoPdf?"Generando…":"Descargar PDF"}</button></div>
    <div className="produccion-ficha-encabezado-impresion" aria-hidden="true"><strong>GRANJA EL CHIFLÓN</strong><span>FICHA TÉCNICA DEL ANIMAL</span></div>
    <header className="produccion-ficha-cabecera"><div className="produccion-ficha-foto">{StrFotoUrl&&StrEstadoFoto==="visible"?<button type="button" className="produccion-ficha-foto-accion no-boton" aria-label={`Ver fotografía ampliada de ${ObjFicha.identificacion}`} onClick={()=>establecerFotoAmpliada(true)}><img src={StrFotoUrl} alt={`Fotografía de ${ObjFicha.identificacion}`}/><span className="no-imprimir">Ver fotografía</span></button>:<div className="produccion-ficha-foto-placeholder">{StrEstadoFoto==="cargando"?"Cargando fotografía…":StrEstadoFoto==="error"?"Fotografía no disponible":"Sin fotografía"}</div>}{Autenticacion_tienePermiso("PRODUCCION_ANIMALES_EDITAR")&&<label className="boton-secundario no-imprimir">{BoolGuardandoFoto?"Guardando…":ObjFicha.tieneFoto?"Cambiar fotografía":"Agregar fotografía"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={BoolGuardandoFoto} onChange={E=>void Produccion_cambiarFoto(E.target.files?.[0])}/></label>}{StrErrorFoto&&<small role="alert">{StrErrorFoto}</small>}</div><div><p className="etiqueta">Ficha técnica del animal</p><h2>{ObjModelo.identificacion}</h2><strong className="produccion-ficha-estado">{ObjModelo.estado}</strong><p>{ObjModelo.tipo} · {ObjModelo.raza} · {ObjModelo.sexo}</p><p><b>Lote actual:</b> {ObjModelo.loteActual}</p>{ObjModelo.salida&&<p><b>Salida:</b> {ObjModelo.salida}</p>}</div></header>
    <Seccion StrTitulo="1. Información general"><dl className="produccion-ficha-datos"><Dato T="Identificación" V={ObjModelo.identificacion}/><Dato T="Tipo" V={ObjModelo.tipo}/><Dato T="Raza" V={ObjModelo.raza}/><Dato T="Sexo" V={ObjModelo.sexo}/><Dato T="Nacimiento" V={ObjModelo.nacimiento}/><Dato T="Ingreso" V={ObjModelo.ingreso}/><Dato T="Madre" V={ObjModelo.madre}/><Dato T="Estado" V={ObjModelo.estado}/></dl></Seccion>
    <Seccion StrTitulo="2. Origen"><p><b>{ObjModelo.origen}</b>{ObjModelo.fechaOrigen!=="—"&&<> · {ObjModelo.fechaOrigen}</>}</p></Seccion>
    <Seccion StrTitulo="3. Ubicación e historial de lotes"><Tabla Cab={["Lote","Inicio","Fin","Motivo"]} Fil={ObjModelo.asignaciones.map(Obj=>[Obj.lote,Obj.inicio,Obj.fin,Obj.motivo])}/></Seccion>
    <Seccion StrTitulo="4. Pesos y mediciones"><Tabla Cab={["Fecha","Peso/medición","Método y medidas","Observación"]} Fil={ObjModelo.mediciones.map(Obj=>[Obj.fecha,Obj.medicion,`${Obj.metodo} · ${Obj.medidas}`,Obj.observacion])}/></Seccion>
    <Seccion StrTitulo="5. Historial sanitario">{ObjModelo.sanidad.length?ObjModelo.sanidad.map((Obj,IntIndice)=><article className={`produccion-ficha-sanidad ${Obj.alcance.includes("lote")?"es-lote":""}`} key={`${Obj.fecha}-${IntIndice}`}><strong>{Obj.alcance}</strong><time>{Obj.fecha}</time><h4>{Obj.tipo}</h4>{Obj.lote!=="—"&&<p><b>Lote:</b> {Obj.lote}</p>}<p><b>Motivo:</b> {Obj.motivo}</p>{Obj.diagnostico!=="—"&&<p><b>Diagnóstico:</b> {Obj.diagnostico}</p>}<ul>{Obj.detalles.map((Det,IntDetalle)=><li key={IntDetalle}>{Det.producto} · Vía: {Det.via}{Det.dosis!=="—"&&<> · {Det.dosis}</>}</li>)}</ul>{Obj.observaciones!=="—"&&<p><b>Observaciones:</b> {Obj.observaciones}</p>}</article>):<p>Sin antecedentes sanitarios registrados.</p>}</Seccion>
    <Seccion StrTitulo="6. Historial de estados"><Tabla Cab={["Fecha","Cambio","Motivo"]} Fil={ObjModelo.estados.map(Obj=>[Obj.fecha,Obj.cambio,Obj.motivo])}/></Seccion>
    <Seccion StrTitulo="7. Observaciones"><p>{ObjModelo.observaciones}</p></Seccion>
    <Seccion StrTitulo="8. Trazabilidad"><ol className="produccion-ficha-linea-tiempo">{ObjModelo.trazabilidad.map((Obj,IntIndice)=><li key={`${Obj.fecha}-${IntIndice}`}><time>{Obj.fecha}</time><span>{Obj.descripcion}</span></li>)}</ol></Seccion>
    <Modal BoolAbierto={BoolFotoAmpliada&&StrFotoUrl!==null} StrTitulo={`Fotografía de ${ObjFicha.identificacion}`} Autenticacion_cerrar={()=>establecerFotoAmpliada(false)}><div className="produccion-foto-ampliada">{StrFotoUrl&&<img src={StrFotoUrl} alt={`Fotografía ampliada de ${ObjFicha.identificacion}`}/>}</div></Modal>
  </article>;
}
function Seccion({StrTitulo,children}:{StrTitulo:string;children:React.ReactNode}){return <section className="produccion-ficha-seccion"><h3>{StrTitulo}</h3>{children}</section>}
function Dato({T,V}:{T:string;V:string}){return <div><dt>{T}</dt><dd>{V}</dd></div>}
function Tabla({Cab,Fil}:{Cab:string[];Fil:string[][]}){return Fil.length?<div className="produccion-ficha-tabla"><table><thead><tr>{Cab.map(Str=><th key={Str}>{Str}</th>)}</tr></thead><tbody>{Fil.map((Arr,Int)=><tr key={Int}>{Arr.map((Str,IntCelda)=><td key={IntCelda}>{Str}</td>)}</tr>)}</tbody></table></div>:<p>Sin registros.</p>}
