import { useState } from "react";
import { Modal } from "../../components/ui/Modal";
import { useSesion } from "../../hooks/useSesion";
import { Produccion_mensajeError, useProduccionLista } from "../../hooks/useProduccionLista";
import * as S from "../../services/produccion.service";
import type { RazaAnimal, TipoAnimal } from "../../types/produccion.types";

const Produccion_solicitarTipos = (Obj: { pagina: number; limite: number; busqueda?: string; estado?: string }) => S.Produccion_listarTipos(Obj);
const Produccion_solicitarRazas = (Obj: { pagina: number; limite: number; busqueda?: string; estado?: string; tipoAnimalId?: number }) => S.Produccion_listarRazas(Obj);
type CatalogoEditable = { StrEntidad: "TIPO"; ObjDato: TipoAnimal } | { StrEntidad: "RAZA"; ObjDato: RazaAnimal };

export function PaginaCatalogosProduccion() {
  const { Autenticacion_tienePermiso } = useSesion();
  const ObjTipos = useProduccionLista<TipoAnimal, object>(Produccion_solicitarTipos, {});
  const ObjRazas = useProduccionLista<RazaAnimal, object>(Produccion_solicitarRazas, {});
  const [StrPestana, establecerPestana] = useState<"TIPOS" | "RAZAS">("TIPOS");
  const [BoolCrear, establecerCrear] = useState(false);
  const [ObjEditar, establecerEditar] = useState<CatalogoEditable | null>(null);
  const [StrError, establecerError] = useState<string | null>(null);
  const BoolPuedeCrear = StrPestana === "TIPOS" ? Autenticacion_tienePermiso("PRODUCCION_TIPOS_CREAR") : Autenticacion_tienePermiso("PRODUCCION_RAZAS_CREAR");
  async function Produccion_refrescar() { await Promise.all([ObjTipos.Produccion_recargar(), ObjRazas.Produccion_recargar()]); }
  async function Produccion_estado(ObjDato: TipoAnimal | RazaAnimal) { try { if ("razaId" in ObjDato) await S.Produccion_estadoRaza(ObjDato.razaId, !ObjDato.activo); else await S.Produccion_estadoTipo(ObjDato.tipoAnimalId, !ObjDato.activo); await Produccion_refrescar(); } catch (ObjError) { establecerError(Produccion_mensajeError(ObjError)); } }
  return <div className="produccion-contenido produccion-catalogos">
    <header className="produccion-seccion-encabezado"><div><h2>Catálogos</h2><p>Los registros inactivos conservan su historial y no se ofrecen en operaciones nuevas.</p></div>{BoolPuedeCrear && <button className="boton-primario" onClick={() => establecerCrear(true)}>Nuevo registro</button>}</header>
    <div className="produccion-pestanas"><button aria-pressed={StrPestana === "TIPOS"} onClick={() => establecerPestana("TIPOS")}>Tipos de animales</button><button aria-pressed={StrPestana === "RAZAS"} onClick={() => establecerPestana("RAZAS")}>Razas</button></div>
    {StrError && <p role="alert">{StrError}</p>}
    <div className="produccion-tabla">{StrPestana === "TIPOS" ? <table><thead><tr><th>Nombre</th><th>Descripción</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{ObjTipos.ArrDatos.map(ObjTipo => <tr key={ObjTipo.tipoAnimalId}><td>{ObjTipo.nombre}</td><td>{ObjTipo.descripcion ?? "—"}</td><td>{ObjTipo.activo ? "Activo" : "Inactivo"}</td><td>{Autenticacion_tienePermiso("PRODUCCION_TIPOS_EDITAR") && <button onClick={() => establecerEditar({ StrEntidad: "TIPO", ObjDato: ObjTipo })}>Editar</button>}{Autenticacion_tienePermiso("PRODUCCION_TIPOS_CAMBIAR_ESTADO") && <button onClick={() => void Produccion_estado(ObjTipo)}>{ObjTipo.activo ? "Inactivar" : "Activar"}</button>}</td></tr>)}</tbody></table> : <table><thead><tr><th>Nombre</th><th>Tipo de animal</th><th>Descripción</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{ObjRazas.ArrDatos.map(ObjRaza => <tr key={ObjRaza.razaId}><td>{ObjRaza.nombre}</td><td>{ObjRaza.tipoAnimal?.nombre ?? "—"}</td><td>{ObjRaza.descripcion ?? "—"}</td><td>{ObjRaza.activo ? "Activo" : "Inactivo"}</td><td>{Autenticacion_tienePermiso("PRODUCCION_RAZAS_EDITAR") && <button onClick={() => establecerEditar({ StrEntidad: "RAZA", ObjDato: ObjRaza })}>Editar</button>}{Autenticacion_tienePermiso("PRODUCCION_RAZAS_CAMBIAR_ESTADO") && <button onClick={() => void Produccion_estado(ObjRaza)}>{ObjRaza.activo ? "Inactivar" : "Activar"}</button>}</td></tr>)}</tbody></table>}</div>
    <div className="produccion-tarjetas produccion-catalogos-tarjetas" aria-label={StrPestana === "TIPOS" ? "Listado móvil de tipos de animales" : "Listado móvil de razas"}>{StrPestana === "TIPOS" ? ObjTipos.ArrDatos.map(ObjTipo => <article key={ObjTipo.tipoAnimalId}><h3>{ObjTipo.nombre}</h3><dl><div><dt>Descripción</dt><dd>{ObjTipo.descripcion ?? "—"}</dd></div><div><dt>Estado</dt><dd>{ObjTipo.activo ? "Activo" : "Inactivo"}</dd></div></dl><div className="produccion-catalogo-acciones">{Autenticacion_tienePermiso("PRODUCCION_TIPOS_EDITAR") && <button onClick={() => establecerEditar({ StrEntidad: "TIPO", ObjDato: ObjTipo })}>Editar {ObjTipo.nombre}</button>}{Autenticacion_tienePermiso("PRODUCCION_TIPOS_CAMBIAR_ESTADO") && <button onClick={() => void Produccion_estado(ObjTipo)}>{ObjTipo.activo ? "Inactivar" : "Activar"} {ObjTipo.nombre}</button>}</div></article>) : ObjRazas.ArrDatos.map(ObjRaza => <article key={ObjRaza.razaId}><h3>{ObjRaza.nombre}</h3><dl><div><dt>Tipo de animal</dt><dd>{ObjRaza.tipoAnimal?.nombre ?? "—"}</dd></div><div><dt>Descripción</dt><dd>{ObjRaza.descripcion ?? "—"}</dd></div><div><dt>Estado</dt><dd>{ObjRaza.activo ? "Activo" : "Inactivo"}</dd></div></dl><div className="produccion-catalogo-acciones">{Autenticacion_tienePermiso("PRODUCCION_RAZAS_EDITAR") && <button onClick={() => establecerEditar({ StrEntidad: "RAZA", ObjDato: ObjRaza })}>Editar {ObjRaza.nombre}</button>}{Autenticacion_tienePermiso("PRODUCCION_RAZAS_CAMBIAR_ESTADO") && <button onClick={() => void Produccion_estado(ObjRaza)}>{ObjRaza.activo ? "Inactivar" : "Activar"} {ObjRaza.nombre}</button>}</div></article>)}</div>
    {(StrPestana === "TIPOS" ? ObjTipos.ArrDatos.length === 0 : ObjRazas.ArrDatos.length === 0) && <p className="produccion-vacio">No existen registros en este catálogo.</p>}
    <Modal BoolAbierto={BoolCrear || ObjEditar !== null} StrTitulo={ObjEditar ? "Editar catálogo" : "Nuevo catálogo"} Autenticacion_cerrar={() => { establecerCrear(false); establecerEditar(null); }}><FormularioCatalogo key={ObjEditar ? `${ObjEditar.StrEntidad}-${"razaId" in ObjEditar.ObjDato ? ObjEditar.ObjDato.razaId : ObjEditar.ObjDato.tipoAnimalId}` : `NUEVO-${StrPestana}`} StrEntidad={ObjEditar?.StrEntidad ?? (StrPestana === "TIPOS" ? "TIPO" : "RAZA")} ObjDato={ObjEditar?.ObjDato ?? null} ArrTipos={ObjTipos.ArrDatos} Produccion_guardar={async (ObjDatos) => { try { if (ObjEditar?.StrEntidad === "TIPO") await S.Produccion_editarTipo(ObjEditar.ObjDato.tipoAnimalId, ObjDatos); else if (ObjEditar?.StrEntidad === "RAZA") await S.Produccion_editarRaza(ObjEditar.ObjDato.razaId, ObjDatos as { tipoAnimalId?: number; nombre?: string; descripcion?: string | null }); else if (StrPestana === "TIPOS") await S.Produccion_crearTipo(ObjDatos as { nombre: string; descripcion?: string | null }); else await S.Produccion_crearRaza(ObjDatos as { tipoAnimalId: number; nombre: string; descripcion?: string | null }); establecerCrear(false); establecerEditar(null); await Produccion_refrescar(); } catch (ObjError) { establecerError(Produccion_mensajeError(ObjError)); } }} /></Modal>
  </div>;
}

function FormularioCatalogo({ StrEntidad, ObjDato, ArrTipos, Produccion_guardar }: { StrEntidad: "TIPO" | "RAZA"; ObjDato: TipoAnimal | RazaAnimal | null; ArrTipos: TipoAnimal[]; Produccion_guardar: (Obj: { tipoAnimalId?: number; nombre: string; descripcion: string | null }) => Promise<void> }) { const [StrTipo, establecerTipo] = useState(ObjDato && "razaId" in ObjDato ? String(ObjDato.tipoAnimalId) : ""), [StrNombre, establecerNombre] = useState(ObjDato?.nombre ?? ""), [StrDescripcion, establecerDescripcion] = useState(ObjDato?.descripcion ?? ""); return <form className="produccion-formulario" onSubmit={(E) => { E.preventDefault(); void Produccion_guardar({ ...(StrEntidad === "RAZA" ? { tipoAnimalId: Number(StrTipo) } : {}), nombre: StrNombre, descripcion: StrDescripcion || null }); }}>{StrEntidad === "RAZA" && <label>Tipo animal<select required value={StrTipo} onChange={(E) => establecerTipo(E.target.value)}><option value="">Seleccione</option>{ArrTipos.filter(ObjTipo => ObjTipo.activo || ObjTipo.tipoAnimalId === Number(StrTipo)).map(ObjTipo => <option key={ObjTipo.tipoAnimalId} value={String(ObjTipo.tipoAnimalId)}>{ObjTipo.nombre}</option>)}</select></label>}<label>Nombre<input required value={StrNombre} onChange={(E) => establecerNombre(E.target.value)} /></label><label>Descripción<textarea value={StrDescripcion} onChange={(E) => establecerDescripcion(E.target.value)} /></label><button>Guardar</button></form>; }
