import assert from "node:assert/strict";
import test from "node:test";
import { Prisma } from "../../../generated/prisma/client.js";
import { ArrCatalogoPermisosInventario, ArrPermisosInventarioOperador, Inventario_canonicalizarCodigo, ObjSubtiposInventario } from "./inventario.constants.js";
import { ObjConsultaExistencias, ObjConsultaProductos, ObjConsultaTransferencias, ObjCrearAjuste, ObjCrearAlmacen, ObjCrearEntrada, ObjCrearProducto, ObjCrearSalida, ObjCrearTransferencia, ObjEditarLote, ObjEditarMinimo } from "./inventario.schemas.js";
import { Inventario_calcularConversion, Inventario_validarProveedorLote, Inventario_validarProveedorOperacion } from "./inventario.service.js";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";

test("Inventario canonicaliza códigos manuales", () => assert.equal(Inventario_canonicalizarCodigo(" alm 01 "), "ALM01"));
test("Inventario define permisos únicos", () => assert.equal(new Set(ArrCatalogoPermisosInventario.map((Obj) => Obj.StrCodigo)).size, 21));
test("Operador solo recibe cuatro permisos operativos", () => assert.deepEqual([...ArrPermisosInventarioOperador], ["INVENTARIO_CONSULTAR", "INVENTARIO_ENTRADAS_CREAR", "INVENTARIO_SALIDAS_CREAR", "INVENTARIO_TRANSFERENCIAS_CREAR"]));
test("No existen subtipos de venta, devolución de cliente o producción", () => { const Arr = Object.values(ObjSubtiposInventario); assert.equal(Arr.includes("VENTA" as never), false); assert.equal(Arr.includes("DEVOLUCION_CLIENTE" as never), false); assert.equal(Arr.includes("PRODUCCION" as never), false); });
test("Entrada solo acepta realidad comercial y no acepta lote ni costo calculado por cliente", () => { const Base = { productoId: 1, inventarioId: 1, cantidadComercial: "1", unidadComercial: "t", precioTotalIngreso: "1500" }; assert.equal(ObjCrearEntrada.safeParse({ ...Base, proveedorId: 1, subtipo: "COMPRA" }).success, true); assert.equal(ObjCrearEntrada.safeParse({ ...Base, subtipo: "PRODUCCION" }).success, false); assert.equal(ObjCrearEntrada.safeParse({ ...Base, proveedorId: 1, subtipo: "COMPRA", codigoLote: "MANUAL" }).success, false); assert.equal(ObjCrearEntrada.safeParse({ ...Base, proveedorId: 1, subtipo: "COMPRA", costoUnitario: "1" }).success, false); });
test("COMPRA exige proveedor y saldo inicial lo permite opcional", () => { const Base = { productoId: 1, inventarioId: 1, cantidadComercial: "1", unidadComercial: "kg", precioTotalIngreso: "10" }; assert.equal(ObjCrearEntrada.safeParse({ ...Base, subtipo: "COMPRA" }).success, false); assert.equal(ObjCrearEntrada.safeParse({ ...Base, subtipo: "INVENTARIO_INICIAL" }).success, true); });
test("Conversión t a lb usa snapshots y ROUND_HALF_UP determinista", () => { const Obj = Inventario_calcularConversion(new Prisma.Decimal(1), new Prisma.Decimal(1000000), new Prisma.Decimal("453.59237"), new Prisma.Decimal(1500)); assert.equal(Obj.DecFactorConversion.toFixed(15), "2204.622621848776000"); assert.equal(Obj.DecCantidadBase.toFixed(6), "2204.622622"); assert.equal(Obj.DecCostoUnitario.toFixed(18), "0.680388554953329332"); });
test("Compra, saldo inicial y devolución validan proveedor directo sin relación producto-proveedor", () => {
  assert.doesNotThrow(() => Inventario_validarProveedorOperacion({ activo: true }, true, true));
  assert.doesNotThrow(() => Inventario_validarProveedorOperacion(null, false, false));
  assert.throws(() => Inventario_validarProveedorOperacion(null, true, false), (ObjError) => ObjError instanceof ErrorAplicacion && ObjError.IntEstadoHttp === 400 && ObjError.StrCodigo === "PROVEEDOR_REQUERIDO");
  assert.throws(() => Inventario_validarProveedorOperacion(null, false, true), (ObjError) => ObjError instanceof ErrorAplicacion && ObjError.IntEstadoHttp === 404 && ObjError.StrCodigo === "PROVEEDOR_NO_ENCONTRADO");
  assert.throws(() => Inventario_validarProveedorOperacion({ activo: false }, false, true), (ObjError) => ObjError instanceof ErrorAplicacion && ObjError.IntEstadoHttp === 409 && ObjError.StrCodigo === "PROVEEDOR_INACTIVO");
});
test("Proveedor recibido debe coincidir con el proveedor histórico del lote", () => {
  assert.doesNotThrow(() => Inventario_validarProveedorLote(8, 8)); assert.doesNotThrow(() => Inventario_validarProveedorLote(null, 8)); assert.doesNotThrow(() => Inventario_validarProveedorLote(8));
  assert.throws(() => Inventario_validarProveedorLote(8, 9), (ObjError) => ObjError instanceof ErrorAplicacion && ObjError.StrCodigo === "PROVEEDOR_LOTE_NO_COINCIDE");
});
test("Salida manual rechaza ALIMENTACION y SANIDAD", () => { const Base = { productoId: 1, inventarioId: 1, loteInventarioId:1, cantidad: "1" }; assert.equal(ObjCrearSalida.safeParse({ ...Base, subtipo: "ALIMENTACION" }).success, false); assert.equal(ObjCrearSalida.safeParse({ ...Base, subtipo: "SANIDAD" }).success, false); });
test("Salida manual exige lote y acepta devolución, merma y disposición", () => { const Base = { productoId: 1, inventarioId: 1, loteInventarioId:1, cantidad: "1" }; for (const subtipo of ["DEVOLUCION_PROVEEDOR", "MERMA", "DISPOSICION"]) assert.equal(ObjCrearSalida.safeParse({ ...Base, subtipo }).success, true); assert.equal(ObjCrearSalida.safeParse({productoId:1,inventarioId:1,cantidad:"1",subtipo:"MERMA"}).success,false); });
test("Ajuste no acepta cantidad cero", () => assert.equal(ObjCrearAjuste.safeParse({ productoId: 1, inventarioId: 1, loteInventarioId:1, cantidad: "0", motivo: "Conteo", subtipo: "CONTEO_FISICO" }).success, false));
test("CONTEO_FISICO exige motivo", () => assert.equal(ObjCrearAjuste.safeParse({ productoId: 1, inventarioId: 1, loteInventarioId:1, cantidad: "1", subtipo: "CONTEO_FISICO" }).success, false));
test("Existencia mínima exige decimal no negativo", () => { assert.equal(ObjEditarMinimo.safeParse({ existenciaMinima: "0.0000" }).success, true); assert.equal(ObjEditarMinimo.safeParse({ existenciaMinima: "-1" }).success, false); });
test("Almacén exige código manual", () => assert.equal(ObjCrearAlmacen.safeParse({ nombre: "Principal" }).success, false));
test("Producto no acepta campos de stock", () => assert.equal(ObjCrearProducto.safeParse({ categoriaId: 1, codigo: "INS01", nombre: "Insumo", unidadMedida: "kg", manejaLotes: false, existenciaActual: 2 }).success, false));
test("Transferencia exige lote, almacenes y cantidad positiva", () => { assert.equal(ObjCrearTransferencia.safeParse({ productoId: 1, inventarioOrigenId: 1, inventarioDestinoId: 2, loteInventarioId:1, cantidad: "1.5" }).success, true); assert.equal(ObjCrearTransferencia.safeParse({ productoId: 1, inventarioOrigenId: 1, inventarioDestinoId: 2, cantidad: "1.5" }).success, false); assert.equal(ObjCrearTransferencia.safeParse({ productoId: 1, inventarioOrigenId: 1, inventarioDestinoId: 2, loteInventarioId:1, cantidad: "0" }).success, false); });
test("Decimal conserva comparación exacta", () => assert.equal(new Prisma.Decimal("0.1000").equals(new Prisma.Decimal("0.1")), true));
test("Código no forma parte de PATCH de producto", async () => { const { ObjEditarProducto } = await import("./inventario.schemas.js"); assert.equal(ObjEditarProducto.safeParse({ codigo: "OTRO" }).success, false); });
test("No hay esquema DELETE", () => assert.equal(Object.keys(ObjSubtiposInventario).some((Str) => Str.includes("DELETE")), false));
test("PATCH de lote no acepta fecha de fabricacion", () => { assert.equal(ObjEditarLote.safeParse({ fechaFabricacion: "2026-08-01" }).success, false); assert.equal(ObjEditarLote.safeParse({ fechaVencimiento: null }).success, true); });
test("Booleanos de query distinguen false", () => { assert.equal(ObjConsultaProductos.parse({ manejaLotes: "false" }).manejaLotes, false); assert.equal(ObjConsultaExistencias.parse({ bajoMinimo: "true" }).bajoMinimo, true); assert.equal(ObjConsultaTransferencias.safeParse({ revertida: "no" }).success, false); });
