import { Prisma } from "../../../generated/prisma/client.js";
import { BaseDatos_obtenerCliente } from "../../database/prisma.js";
import { Fecha_obtenerAhoraGuatemala } from "../../datetime/fecha.js";

export const Inventario_obtenerCategoria = (IntCategoriaId: number) => BaseDatos_obtenerCliente().inventarioCategoria.findUnique({ where: { categoriaId: IntCategoriaId } });
export const Inventario_obtenerAlmacen = (IntInventarioId: number) => BaseDatos_obtenerCliente().inventarioAlmacen.findUnique({ where: { inventarioId: IntInventarioId } });
export const Inventario_obtenerProducto = (IntProductoId: number) => BaseDatos_obtenerCliente().inventarioProducto.findUnique({ where: { productoId: IntProductoId }, include: { categoria: true } });
export const Inventario_obtenerLote = (IntLoteId: number) => BaseDatos_obtenerCliente().inventarioLote.findUnique({ where: { loteInventarioId: IntLoteId }, include: { producto: true } });
export const Inventario_obtenerProveedorProducto = (IntProveedorId: number, IntProductoId: number) => BaseDatos_obtenerCliente().proveedorProducto.findUnique({ where: { proveedorId_productoId: { proveedorId: IntProveedorId, productoId: IntProductoId } }, include: { proveedor: true } });

export async function Inventario_listarCategorias(Obj: { IntPagina: number; IntLimite: number; StrBusqueda?: string | undefined; BoolActivo?: boolean | undefined }) {
  const where: Prisma.InventarioCategoriaWhereInput = { ...(Obj.BoolActivo === undefined ? {} : { activo: Obj.BoolActivo }), ...(Obj.StrBusqueda ? { nombre: { contains: Obj.StrBusqueda } } : {}) };
  const ObjPrisma = BaseDatos_obtenerCliente();
  const [datos, total] = await ObjPrisma.$transaction([ObjPrisma.inventarioCategoria.findMany({ where, orderBy: { categoriaId: "asc" }, skip: (Obj.IntPagina - 1) * Obj.IntLimite, take: Obj.IntLimite }), ObjPrisma.inventarioCategoria.count({ where })]);
  return { datos, total };
}
export async function Inventario_listarAlmacenes(Obj: { IntPagina: number; IntLimite: number; StrBusqueda?: string | undefined; BoolActivo?: boolean | undefined }) {
  const where: Prisma.InventarioAlmacenWhereInput = { ...(Obj.BoolActivo === undefined ? {} : { activo: Obj.BoolActivo }), ...(Obj.StrBusqueda ? { OR: [{ codigo: { contains: Obj.StrBusqueda } }, { nombre: { contains: Obj.StrBusqueda } }] } : {}) };
  const ObjPrisma = BaseDatos_obtenerCliente(); const [datos, total] = await ObjPrisma.$transaction([ObjPrisma.inventarioAlmacen.findMany({ where, orderBy: { inventarioId: "asc" }, skip: (Obj.IntPagina - 1) * Obj.IntLimite, take: Obj.IntLimite }), ObjPrisma.inventarioAlmacen.count({ where })]); return { datos, total };
}
export async function Inventario_listarProductos(Obj: { IntPagina: number; IntLimite: number; StrBusqueda?: string | undefined; BoolActivo?: boolean | undefined; IntCategoriaId?: number | undefined; BoolManejaLotes?: boolean | undefined }) {
  const where: Prisma.InventarioProductoWhereInput = { ...(Obj.BoolActivo === undefined ? {} : { activo: Obj.BoolActivo }), ...(Obj.IntCategoriaId ? { categoriaId: Obj.IntCategoriaId } : {}), ...(Obj.BoolManejaLotes === undefined ? {} : { manejaLotes: Obj.BoolManejaLotes }), ...(Obj.StrBusqueda ? { OR: [{ codigo: { contains: Obj.StrBusqueda } }, { nombre: { contains: Obj.StrBusqueda } }] } : {}) };
  const ObjPrisma = BaseDatos_obtenerCliente(); const select = { productoId: true, categoriaId: true, codigo: true, nombre: true, descripcion: true, unidadMedida: true, manejaLotes: true, activo: true, fechaCreacion: true, fechaActualizacion: true, categoria: { select: { categoriaId: true, nombre: true, activo: true } } } satisfies Prisma.InventarioProductoSelect;
  const [datos, total] = await ObjPrisma.$transaction([ObjPrisma.inventarioProducto.findMany({ where, select, orderBy: { productoId: "asc" }, skip: (Obj.IntPagina - 1) * Obj.IntLimite, take: Obj.IntLimite }), ObjPrisma.inventarioProducto.count({ where })]); return { datos, total };
}
export async function Inventario_listarProveedoresProductos(Obj: { IntPagina: number; IntLimite: number; StrBusqueda?: string | undefined; BoolActivo?: boolean | undefined }) { const where: Prisma.ProveedorProductoWhereInput = { ...(Obj.BoolActivo === undefined ? {} : { activo: Obj.BoolActivo }), ...(Obj.StrBusqueda ? { OR: [{ producto: { OR: [{ codigo: { contains: Obj.StrBusqueda } }, { nombre: { contains: Obj.StrBusqueda } }] } }, { proveedor: { OR: [{ codigo: { contains: Obj.StrBusqueda } }, { nombre: { contains: Obj.StrBusqueda } }, { nombreComercial: { contains: Obj.StrBusqueda } }] } }] } : {}) }; const P = BaseDatos_obtenerCliente(); const [datos, total] = await P.$transaction([P.proveedorProducto.findMany({ where, include: { producto: true, proveedor: true }, orderBy: { proveedorProductoId: "asc" }, skip: (Obj.IntPagina - 1) * Obj.IntLimite, take: Obj.IntLimite }), P.proveedorProducto.count({ where })]); return { datos, total }; }

async function Inventario_bitacora(ObjTx: Prisma.TransactionClient, IntUsuarioId: number, StrAccion: string, StrDescripcion: string, StrIp?: string | undefined) { await ObjTx.usuarioBitacora.create({ data: { usuarioId: IntUsuarioId, modulo: "INVENTARIO", accion: StrAccion, descripcion: StrDescripcion, resultado: "EXITO", direccionIp: StrIp ?? null } }); }

export function Inventario_crearCategoria(ObjDatos: { nombre: string; descripcion?: string | undefined | null; IntUsuarioId: number; StrIp?: string | undefined }) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioCategoria.create({ data: { nombre: ObjDatos.nombre, descripcion: ObjDatos.descripcion ?? null } }); await Inventario_bitacora(ObjTx, ObjDatos.IntUsuarioId, "INVENTARIO_CATEGORIA_CREADA", `Categoria ${ObjRegistro.categoriaId}.`, ObjDatos.StrIp); return ObjRegistro; }); }
export function Inventario_editarCategoria(IntId: number, ObjDatos: Prisma.InventarioCategoriaUpdateInput, IntUsuarioId: number, StrIp?: string | undefined) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioCategoria.update({ where: { categoriaId: IntId }, data: { ...ObjDatos, fechaActualizacion: Fecha_obtenerAhoraGuatemala() } }); await Inventario_bitacora(ObjTx, IntUsuarioId, "INVENTARIO_CATEGORIA_EDITADA", `Categoria ${IntId}.`, StrIp); return ObjRegistro; }); }
export function Inventario_crearAlmacen(ObjDatos: { codigo: string; nombre: string; descripcion?: string | undefined | null; ubicacion?: string | undefined | null; IntUsuarioId: number; StrIp?: string | undefined }) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioAlmacen.create({ data: { codigo: ObjDatos.codigo, nombre: ObjDatos.nombre, descripcion: ObjDatos.descripcion ?? null, ubicacion: ObjDatos.ubicacion ?? null } }); await Inventario_bitacora(ObjTx, ObjDatos.IntUsuarioId, "INVENTARIO_ALMACEN_CREADO", `Almacen ${ObjRegistro.inventarioId}; codigo ${ObjRegistro.codigo}.`, ObjDatos.StrIp); return ObjRegistro; }); }
export function Inventario_editarAlmacen(IntId: number, ObjDatos: Prisma.InventarioAlmacenUpdateInput, IntUsuarioId: number, StrIp?: string | undefined) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioAlmacen.update({ where: { inventarioId: IntId }, data: { ...ObjDatos, fechaActualizacion: Fecha_obtenerAhoraGuatemala() } }); await Inventario_bitacora(ObjTx, IntUsuarioId, "INVENTARIO_ALMACEN_EDITADO", `Almacen ${IntId}.`, StrIp); return ObjRegistro; }); }
export function Inventario_crearProducto(ObjDatos: { categoriaId: number; codigo: string; nombre: string; descripcion?: string | undefined | null; unidadMedida: string; manejaLotes: boolean; IntUsuarioId: number; StrIp?: string | undefined }) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioProducto.create({ data: { categoriaId: ObjDatos.categoriaId, codigo: ObjDatos.codigo, nombre: ObjDatos.nombre, descripcion: ObjDatos.descripcion ?? null, unidadMedida: ObjDatos.unidadMedida, manejaLotes: ObjDatos.manejaLotes } }); await Inventario_bitacora(ObjTx, ObjDatos.IntUsuarioId, "INVENTARIO_PRODUCTO_CREADO", `Producto ${ObjRegistro.productoId}; codigo ${ObjRegistro.codigo}.`, ObjDatos.StrIp); return ObjRegistro; }); }
export function Inventario_editarProducto(IntId: number, ObjDatos: Prisma.InventarioProductoUpdateInput, IntUsuarioId: number, StrIp?: string | undefined) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioProducto.update({ where: { productoId: IntId }, data: { ...ObjDatos, fechaActualizacion: Fecha_obtenerAhoraGuatemala() } }); await Inventario_bitacora(ObjTx, IntUsuarioId, "INVENTARIO_PRODUCTO_EDITADO", `Producto ${IntId}.`, StrIp); return ObjRegistro; }); }
export function Inventario_cambiarEstado(StrEntidad: "categoria" | "almacen" | "producto" | "lote", IntId: number, BoolActivo: boolean, IntUsuarioId: number, StrIp?: string | undefined) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const DtAhora = Fecha_obtenerAhoraGuatemala(); let ObjRegistro: unknown; if (StrEntidad === "categoria") ObjRegistro = await ObjTx.inventarioCategoria.update({ where: { categoriaId: IntId }, data: { activo: BoolActivo, fechaActualizacion: DtAhora } }); else if (StrEntidad === "almacen") ObjRegistro = await ObjTx.inventarioAlmacen.update({ where: { inventarioId: IntId }, data: { activo: BoolActivo, fechaActualizacion: DtAhora } }); else if (StrEntidad === "producto") ObjRegistro = await ObjTx.inventarioProducto.update({ where: { productoId: IntId }, data: { activo: BoolActivo, fechaActualizacion: DtAhora } }); else ObjRegistro = await ObjTx.inventarioLote.update({ where: { loteInventarioId: IntId }, data: { activo: BoolActivo, fechaActualizacion: DtAhora } }); await Inventario_bitacora(ObjTx, IntUsuarioId, `INVENTARIO_${StrEntidad.toUpperCase()}_ESTADO_CAMBIADO`, `${StrEntidad} ${IntId}; activo ${BoolActivo}.`, StrIp); return ObjRegistro; }); }

export function Inventario_gestionarProveedorProducto(ObjDatos: { proveedorId: number; productoId: number; precioReferencia?: string | undefined | null; activo?: boolean | undefined; IntUsuarioId: number; StrIp?: string | undefined }) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.proveedorProducto.upsert({ where: { proveedorId_productoId: { proveedorId: ObjDatos.proveedorId, productoId: ObjDatos.productoId } }, create: { proveedorId: ObjDatos.proveedorId, productoId: ObjDatos.productoId, precioReferencia: ObjDatos.precioReferencia ?? null, activo: ObjDatos.activo ?? true }, update: { ...(ObjDatos.precioReferencia === undefined ? {} : { precioReferencia: ObjDatos.precioReferencia }), ...(ObjDatos.activo === undefined ? {} : { activo: ObjDatos.activo }), fechaActualizacion: Fecha_obtenerAhoraGuatemala() } }); await Inventario_bitacora(ObjTx, ObjDatos.IntUsuarioId, "INVENTARIO_PROVEEDOR_PRODUCTO_GESTIONADO", `Relacion ${ObjRegistro.proveedorProductoId}; producto ${ObjRegistro.productoId}; proveedor ${ObjRegistro.proveedorId}.`, ObjDatos.StrIp); return ObjRegistro; }); }
export function Inventario_editarMinimo(IntExistenciaId: number, StrMinimo: string, IntUsuarioId: number, StrIp?: string | undefined) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioExistencia.update({ where: { inventarioProductoId: IntExistenciaId }, data: { existenciaMinima: new Prisma.Decimal(StrMinimo), fechaActualizacion: Fecha_obtenerAhoraGuatemala() } }); await Inventario_bitacora(ObjTx, IntUsuarioId, "INVENTARIO_EXISTENCIA_MINIMA_EDITADA", `Existencia ${IntExistenciaId}.`, StrIp); return ObjRegistro; }); }
export function Inventario_editarLote(IntLoteId: number, ObjDatos: Prisma.InventarioLoteUpdateInput, IntUsuarioId: number, StrIp?: string | undefined) { return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => { const ObjRegistro = await ObjTx.inventarioLote.update({ where: { loteInventarioId: IntLoteId }, data: { ...ObjDatos, fechaActualizacion: Fecha_obtenerAhoraGuatemala() } }); await Inventario_bitacora(ObjTx, IntUsuarioId, "INVENTARIO_LOTE_EDITADO", `Lote ${IntLoteId}.`, StrIp); return ObjRegistro; }); }

export async function Inventario_listarExistencias() { return BaseDatos_obtenerCliente().inventarioExistencia.findMany({ include: { producto: true, almacen: true, lotes: { include: { lote: true } } }, orderBy: { inventarioProductoId: "asc" } }); }
export async function Inventario_listarLotes(Obj: { IntPagina: number; IntLimite: number; StrBusqueda?: string | undefined; BoolActivo?: boolean | undefined; IntProductoId?: number | undefined; IntInventarioId?: number | undefined }) { const where: Prisma.InventarioLoteWhereInput = { ...(Obj.BoolActivo === undefined ? {} : { activo: Obj.BoolActivo }), ...(Obj.IntProductoId === undefined ? {} : { productoId: Obj.IntProductoId }), ...(Obj.IntInventarioId === undefined ? {} : { existencias: { some: { existencia: { inventarioId: Obj.IntInventarioId } } } }), ...(Obj.StrBusqueda ? { codigoLote: { contains: Obj.StrBusqueda } } : {}) }; const P = BaseDatos_obtenerCliente(); const [datos, total] = await P.$transaction([P.inventarioLote.findMany({ where, include: { producto: true, proveedor: true, existencias: { include: { existencia: { include: { almacen: true } } } } }, orderBy: { loteInventarioId: "asc" }, skip: (Obj.IntPagina - 1) * Obj.IntLimite, take: Obj.IntLimite }), P.inventarioLote.count({ where })]); return { datos, total }; }
export async function Inventario_listarMovimientos(Obj: { IntPagina: number; IntLimite: number; IntProductoId?: number | undefined; IntInventarioId?: number | undefined; StrTipo?: string | undefined; StrSubtipo?: string | undefined }) { const where: Prisma.InventarioTransaccionWhereInput = { ...(Obj.IntProductoId === undefined ? {} : { existencia: { productoId: Obj.IntProductoId } }), ...(Obj.IntInventarioId === undefined ? {} : { existencia: { inventarioId: Obj.IntInventarioId } }), ...(Obj.StrTipo === undefined ? {} : { tipoTransaccion: Obj.StrTipo }), ...(Obj.StrSubtipo === undefined ? {} : { subtipoTransaccion: Obj.StrSubtipo }) }; const P = BaseDatos_obtenerCliente(); const [datos, total] = await P.$transaction([P.inventarioTransaccion.findMany({ where, orderBy: { transaccionInventarioId: "asc" }, skip: (Obj.IntPagina - 1) * Obj.IntLimite, take: Obj.IntLimite }), P.inventarioTransaccion.count({ where })]); return { datos, total }; }

export function Inventario_registrarMovimiento(ObjDatos: { tipo: "INGRESO" | "SALIDA" | "AJUSTE"; subtipo: string; productoId: number; inventarioId: number; loteInventarioId?: number | undefined; codigoLote?: string | undefined; proveedorId?: number | undefined; cantidad: Prisma.Decimal; costoUnitario?: Prisma.Decimal | undefined | null; fechaFabricacion?: Date | undefined | null; fechaVencimiento?: Date | undefined | null; documentoReferencia?: string | undefined | null; motivo?: string | undefined | null; observaciones?: string | undefined | null; IntUsuarioId: number; StrIp?: string | undefined }) {
  return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => {
    const DtAhora = Fecha_obtenerAhoraGuatemala();
    const ObjExistencia = await ObjTx.inventarioExistencia.upsert({ where: { inventarioId_productoId: { inventarioId: ObjDatos.inventarioId, productoId: ObjDatos.productoId } }, create: { inventarioId: ObjDatos.inventarioId, productoId: ObjDatos.productoId }, update: {} });
    let IntExistenciaLoteId: number | undefined;
    if (ObjDatos.loteInventarioId !== undefined || ObjDatos.codigoLote !== undefined) {
      let ObjLote = ObjDatos.loteInventarioId === undefined ? null : await ObjTx.inventarioLote.findUnique({ where: { loteInventarioId: ObjDatos.loteInventarioId } });
      if (ObjLote === null && ObjDatos.codigoLote !== undefined) ObjLote = await ObjTx.inventarioLote.create({ data: { productoId: ObjDatos.productoId, proveedorId: ObjDatos.proveedorId ?? null, codigoLote: ObjDatos.codigoLote, costoUnitario: ObjDatos.costoUnitario ?? null, fechaFabricacion: ObjDatos.fechaFabricacion ?? null, fechaVencimiento: ObjDatos.fechaVencimiento ?? null } });
      if (ObjLote === null) throw new Error("LOTE_NO_ENCONTRADO");
      const ObjSaldoLote = await ObjTx.inventarioExistenciaLote.upsert({ where: { inventarioProductoId_loteInventarioId: { inventarioProductoId: ObjExistencia.inventarioProductoId, loteInventarioId: ObjLote.loteInventarioId } }, create: { inventarioProductoId: ObjExistencia.inventarioProductoId, loteInventarioId: ObjLote.loteInventarioId, productoId: ObjDatos.productoId }, update: {} });
      IntExistenciaLoteId = ObjSaldoLote.existenciaLoteId;
      const ObjActualizacionLote = await ObjTx.inventarioExistenciaLote.updateMany({ where: { existenciaLoteId: ObjSaldoLote.existenciaLoteId, existenciaActual: { gte: ObjDatos.cantidad.negated() } }, data: { existenciaActual: { increment: ObjDatos.cantidad }, fechaActualizacion: DtAhora } });
      if (ObjActualizacionLote.count !== 1) throw new Error("STOCK_INSUFICIENTE");
    }
    const ObjActualizacion = await ObjTx.inventarioExistencia.updateMany({ where: { inventarioProductoId: ObjExistencia.inventarioProductoId, existenciaActual: { gte: ObjDatos.cantidad.negated() } }, data: { existenciaActual: { increment: ObjDatos.cantidad }, fechaActualizacion: DtAhora } });
    if (ObjActualizacion.count !== 1) throw new Error("STOCK_INSUFICIENTE");
    const ObjMovimiento = await ObjTx.inventarioTransaccion.create({ data: { inventarioProductoId: ObjExistencia.inventarioProductoId, existenciaLoteId: IntExistenciaLoteId ?? null, usuarioId: ObjDatos.IntUsuarioId, proveedorId: ObjDatos.proveedorId ?? null, tipoTransaccion: ObjDatos.tipo, subtipoTransaccion: ObjDatos.subtipo, cantidad: ObjDatos.cantidad, costoUnitario: ObjDatos.costoUnitario ?? null, documentoReferencia: ObjDatos.documentoReferencia ?? null, motivo: ObjDatos.motivo ?? null, observaciones: ObjDatos.observaciones ?? null } });
    await Inventario_bitacora(ObjTx, ObjDatos.IntUsuarioId, `INVENTARIO_${ObjDatos.tipo}_REGISTRADO`, `Movimiento ${ObjMovimiento.transaccionInventarioId}; producto ${ObjDatos.productoId}; subtipo ${ObjDatos.subtipo}.`, ObjDatos.StrIp);
    return ObjMovimiento;
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export function Inventario_registrarTransferencia(ObjDatos: { productoId: number; inventarioOrigenId: number; inventarioDestinoId: number; loteInventarioId?: number | undefined; cantidad: Prisma.Decimal; documentoReferencia?: string | undefined | null; motivo?: string | undefined | null; observaciones?: string | undefined | null; IntUsuarioId: number; StrIp?: string | undefined }) {
  return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => {
    const DtAhora = Fecha_obtenerAhoraGuatemala();
    const ObjOrigen = await ObjTx.inventarioExistencia.findUnique({ where: { inventarioId_productoId: { inventarioId: ObjDatos.inventarioOrigenId, productoId: ObjDatos.productoId } } });
    if (!ObjOrigen) throw new Error("STOCK_INSUFICIENTE");
    const ObjDestino = await ObjTx.inventarioExistencia.upsert({ where: { inventarioId_productoId: { inventarioId: ObjDatos.inventarioDestinoId, productoId: ObjDatos.productoId } }, create: { inventarioId: ObjDatos.inventarioDestinoId, productoId: ObjDatos.productoId }, update: {} });
    let ObjLoteOrigen: { existenciaLoteId: number } | null = null;
    let ObjLoteDestino: { existenciaLoteId: number } | null = null;
    if (ObjDatos.loteInventarioId !== undefined) {
      ObjLoteOrigen = await ObjTx.inventarioExistenciaLote.findUnique({ where: { inventarioProductoId_loteInventarioId: { inventarioProductoId: ObjOrigen.inventarioProductoId, loteInventarioId: ObjDatos.loteInventarioId } } });
      if (!ObjLoteOrigen) throw new Error("STOCK_INSUFICIENTE");
      ObjLoteDestino = await ObjTx.inventarioExistenciaLote.upsert({ where: { inventarioProductoId_loteInventarioId: { inventarioProductoId: ObjDestino.inventarioProductoId, loteInventarioId: ObjDatos.loteInventarioId } }, create: { inventarioProductoId: ObjDestino.inventarioProductoId, loteInventarioId: ObjDatos.loteInventarioId, productoId: ObjDatos.productoId }, update: {} });
      const ObjCambioLote = await ObjTx.inventarioExistenciaLote.updateMany({ where: { existenciaLoteId: ObjLoteOrigen.existenciaLoteId, existenciaActual: { gte: ObjDatos.cantidad } }, data: { existenciaActual: { decrement: ObjDatos.cantidad }, fechaActualizacion: DtAhora } });
      if (ObjCambioLote.count !== 1) throw new Error("STOCK_INSUFICIENTE");
      await ObjTx.inventarioExistenciaLote.update({ where: { existenciaLoteId: ObjLoteDestino.existenciaLoteId }, data: { existenciaActual: { increment: ObjDatos.cantidad }, fechaActualizacion: DtAhora } });
    }
    const ObjCambio = await ObjTx.inventarioExistencia.updateMany({ where: { inventarioProductoId: ObjOrigen.inventarioProductoId, existenciaActual: { gte: ObjDatos.cantidad } }, data: { existenciaActual: { decrement: ObjDatos.cantidad }, fechaActualizacion: DtAhora } });
    if (ObjCambio.count !== 1) throw new Error("STOCK_INSUFICIENTE");
    await ObjTx.inventarioExistencia.update({ where: { inventarioProductoId: ObjDestino.inventarioProductoId }, data: { existenciaActual: { increment: ObjDatos.cantidad }, fechaActualizacion: DtAhora } });
    const ObjTransferencia = await ObjTx.inventarioTransferencia.create({ data: { productoId: ObjDatos.productoId, inventarioProductoOrigenId: ObjOrigen.inventarioProductoId, inventarioProductoDestinoId: ObjDestino.inventarioProductoId, existenciaLoteOrigenId: ObjLoteOrigen?.existenciaLoteId ?? null, existenciaLoteDestinoId: ObjLoteDestino?.existenciaLoteId ?? null, loteInventarioId: ObjDatos.loteInventarioId ?? null, usuarioId: ObjDatos.IntUsuarioId, cantidad: ObjDatos.cantidad, documentoReferencia: ObjDatos.documentoReferencia ?? null, motivo: ObjDatos.motivo ?? null, observaciones: ObjDatos.observaciones ?? null } });
    await ObjTx.inventarioTransaccion.createMany({ data: [
      { inventarioProductoId: ObjOrigen.inventarioProductoId, existenciaLoteId: ObjLoteOrigen?.existenciaLoteId ?? null, transferenciaId: ObjTransferencia.transferenciaId, usuarioId: ObjDatos.IntUsuarioId, tipoTransaccion: "SALIDA", subtipoTransaccion: "TRANSFERENCIA_SALIDA", cantidad: ObjDatos.cantidad.negated(), documentoReferencia: ObjDatos.documentoReferencia ?? null, motivo: ObjDatos.motivo ?? null, observaciones: ObjDatos.observaciones ?? null },
      { inventarioProductoId: ObjDestino.inventarioProductoId, existenciaLoteId: ObjLoteDestino?.existenciaLoteId ?? null, transferenciaId: ObjTransferencia.transferenciaId, usuarioId: ObjDatos.IntUsuarioId, tipoTransaccion: "INGRESO", subtipoTransaccion: "TRANSFERENCIA_ENTRADA", cantidad: ObjDatos.cantidad, documentoReferencia: ObjDatos.documentoReferencia ?? null, motivo: ObjDatos.motivo ?? null, observaciones: ObjDatos.observaciones ?? null },
    ] });
    await Inventario_bitacora(ObjTx, ObjDatos.IntUsuarioId, "INVENTARIO_TRANSFERENCIA_REGISTRADA", `Transferencia ${ObjTransferencia.transferenciaId}; producto ${ObjDatos.productoId}.`, ObjDatos.StrIp);
    return ObjTransferencia;
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export function Inventario_revertirMovimiento(IntTransaccionId: number, IntUsuarioId: number, StrIp?: string | undefined) {
  return BaseDatos_obtenerCliente().$transaction(async (ObjTx) => {
    const ObjOriginal = await ObjTx.inventarioTransaccion.findUnique({ where: { transaccionInventarioId: IntTransaccionId }, include: { reversion: true } });
    if (!ObjOriginal) throw new Error("MOVIMIENTO_NO_ENCONTRADO");
    if (ObjOriginal.subtipoTransaccion === "REVERSION" || ObjOriginal.reversion) throw new Error("MOVIMIENTO_YA_REVERTIDO");
    const ArrOriginales = ObjOriginal.transferenciaId === null ? [ObjOriginal] : await ObjTx.inventarioTransaccion.findMany({ where: { transferenciaId: ObjOriginal.transferenciaId }, orderBy: { transaccionInventarioId: "asc" } });
    for (const ObjMovimiento of ArrOriginales) {
      const DecReversion = ObjMovimiento.cantidad.negated();
      const ObjSaldo = await ObjTx.inventarioExistencia.updateMany({ where: { inventarioProductoId: ObjMovimiento.inventarioProductoId, existenciaActual: { gte: DecReversion.negated() } }, data: { existenciaActual: { increment: DecReversion }, fechaActualizacion: Fecha_obtenerAhoraGuatemala() } });
      if (ObjSaldo.count !== 1) throw new Error("STOCK_INSUFICIENTE");
      if (ObjMovimiento.existenciaLoteId !== null) { const ObjSaldoLote = await ObjTx.inventarioExistenciaLote.updateMany({ where: { existenciaLoteId: ObjMovimiento.existenciaLoteId, existenciaActual: { gte: DecReversion.negated() } }, data: { existenciaActual: { increment: DecReversion }, fechaActualizacion: Fecha_obtenerAhoraGuatemala() } }); if (ObjSaldoLote.count !== 1) throw new Error("STOCK_INSUFICIENTE"); }
      await ObjTx.inventarioTransaccion.create({ data: { inventarioProductoId: ObjMovimiento.inventarioProductoId, existenciaLoteId: ObjMovimiento.existenciaLoteId, usuarioId: IntUsuarioId, tipoTransaccion: "AJUSTE", subtipoTransaccion: "REVERSION", cantidad: DecReversion, costoUnitario: ObjMovimiento.costoUnitario, transaccionRevertidaId: ObjMovimiento.transaccionInventarioId, motivo: `Reversion del movimiento ${ObjMovimiento.transaccionInventarioId}.` } });
    }
    await Inventario_bitacora(ObjTx, IntUsuarioId, "INVENTARIO_MOVIMIENTO_REVERTIDO", `Movimiento ${IntTransaccionId}.`, StrIp);
    return { transaccionInventarioId: IntTransaccionId, movimientosRevertidos: ArrOriginales.length };
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

export async function Inventario_diagnosticarReconciliacion() {
  const ObjPrisma = BaseDatos_obtenerCliente();
  const saldos = await ObjPrisma.$queryRaw<Array<{ inventarioProductoId: number; saldoMaterializado: Prisma.Decimal; saldoHistorial: Prisma.Decimal }>>`
    SELECT e.inventario_producto_id AS inventarioProductoId, e.existencia_actual AS saldoMaterializado,
      COALESCE(SUM(t.cantidad), 0) AS saldoHistorial
    FROM dbo.inventario_existencias e LEFT JOIN dbo.inventario_transacciones t ON t.inventario_producto_id=e.inventario_producto_id
    GROUP BY e.inventario_producto_id,e.existencia_actual HAVING e.existencia_actual<>COALESCE(SUM(t.cantidad),0)`;
  const lotes = await ObjPrisma.$queryRaw<Array<{ inventarioProductoId: number; saldoProducto: Prisma.Decimal; saldoLotes: Prisma.Decimal }>>`
    SELECT e.inventario_producto_id AS inventarioProductoId,e.existencia_actual AS saldoProducto,COALESCE(SUM(l.existencia_actual),0) AS saldoLotes
    FROM dbo.inventario_existencias e JOIN dbo.inventario_productos p ON p.producto_id=e.producto_id AND p.maneja_lotes=1
    LEFT JOIN dbo.inventario_existencias_lotes l ON l.inventario_producto_id=e.inventario_producto_id
    GROUP BY e.inventario_producto_id,e.existencia_actual HAVING e.existencia_actual<>COALESCE(SUM(l.existencia_actual),0)`;
  const saldosLote = await ObjPrisma.$queryRaw<Array<{ existenciaLoteId: number; saldoMaterializado: Prisma.Decimal; saldoHistorial: Prisma.Decimal }>>`
    SELECT l.existencia_lote_id AS existenciaLoteId,l.existencia_actual AS saldoMaterializado,COALESCE(SUM(t.cantidad),0) AS saldoHistorial
    FROM dbo.inventario_existencias_lotes l LEFT JOIN dbo.inventario_transacciones t ON t.existencia_lote_id=l.existencia_lote_id
    GROUP BY l.existencia_lote_id,l.existencia_actual HAVING l.existencia_actual<>COALESCE(SUM(t.cantidad),0)`;
  return { saldos, lotes, saldosLote, consistente: saldos.length === 0 && lotes.length === 0 && saldosLote.length === 0 };
}
