import type { Request, Response } from "express";
import type { ZodType } from "zod";
import type { Prisma } from "../../../generated/prisma/client.js";
import { ErrorAplicacion } from "../../errors/error-aplicacion.js";
import * as E from "./inventario.schemas.js";
import * as S from "./inventario.service.js";

function Inventario_validar<T>(ObjEsquema: ZodType<T>, ObjValor: unknown): T { const ObjResultado = ObjEsquema.safeParse(ObjValor); if (!ObjResultado.success) throw new ErrorAplicacion(400, "VALIDACION_INVALIDA", "Los datos proporcionados no son válidos."); return ObjResultado.data; }
function Inventario_actor(ObjSolicitud: Request) { if (!ObjSolicitud.ObjAutenticacion) throw new ErrorAplicacion(401, "NO_AUTENTICADO", "Debe iniciar sesión."); return { IntUsuarioId: ObjSolicitud.ObjAutenticacion.IntUsuarioId, StrIp: ObjSolicitud.ip }; }
function Inventario_paginacion(ObjConsulta: { pagina: number; limite: number }, ObjResultado: { datos: unknown; total: number }) { return { datos: ObjResultado.datos, paginacion: { pagina: ObjConsulta.pagina, limite: ObjConsulta.limite, total: ObjResultado.total } }; }

export async function Inventario_listarCategorias(Req: Request, Res: Response) { const Q = Inventario_validar(E.ObjConsultaInventario, Req.query); Res.json(Inventario_paginacion(Q, await S.Inventario_listarCategorias({ IntPagina: Q.pagina, IntLimite: Q.limite, StrBusqueda: Q.busqueda, BoolActivo: Q.estado === undefined ? undefined : Q.estado === "ACTIVO" }))); }
export async function Inventario_crearCategoria(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjCrearCategoria, Req.body); Res.status(201).json({ datos: await S.Inventario_crearCategoria({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_editarCategoria(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroCategoria, Req.params); const B = Inventario_validar(E.ObjEditarCategoria, Req.body); Res.json({ datos: await S.Inventario_editarCategoria(P.categoriaId, B as Prisma.InventarioCategoriaUpdateInput, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_estadoCategoria(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroCategoria, Req.params); const B = Inventario_validar(E.ObjEstadoCategoria, Req.body); Res.json({ datos: await S.Inventario_cambiarEstado("categoria", P.categoriaId, B.activo, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_listarAlmacenes(Req: Request, Res: Response) { const Q = Inventario_validar(E.ObjConsultaInventario, Req.query); Res.json(Inventario_paginacion(Q, await S.Inventario_listarAlmacenes({ IntPagina: Q.pagina, IntLimite: Q.limite, StrBusqueda: Q.busqueda, BoolActivo: Q.estado === undefined ? undefined : Q.estado === "ACTIVO" }))); }
export async function Inventario_crearAlmacen(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjCrearAlmacen, Req.body); Res.status(201).json({ datos: await S.Inventario_crearAlmacen({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_editarAlmacen(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroAlmacen, Req.params); const B = Inventario_validar(E.ObjEditarAlmacen, Req.body); Res.json({ datos: await S.Inventario_editarAlmacen(P.inventarioId, B as Prisma.InventarioAlmacenUpdateInput, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_estadoAlmacen(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroAlmacen, Req.params); const B = Inventario_validar(E.ObjEstadoAlmacen, Req.body); Res.json({ datos: await S.Inventario_cambiarEstado("almacen", P.inventarioId, B.activo, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_listarProductos(Req: Request, Res: Response) { const Q = Inventario_validar(E.ObjConsultaProductos, Req.query); Res.json(Inventario_paginacion(Q, await S.Inventario_listarProductos({ IntPagina: Q.pagina, IntLimite: Q.limite, StrBusqueda: Q.busqueda, BoolActivo: Q.estado === undefined ? undefined : Q.estado === "ACTIVO", IntCategoriaId: Q.categoriaId, BoolManejaLotes: Q.manejaLotes }))); }
export async function Inventario_crearProducto(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjCrearProducto, Req.body); Res.status(201).json({ datos: await S.Inventario_crearProducto({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_editarProducto(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroProducto, Req.params); const B = Inventario_validar(E.ObjEditarProducto, Req.body); Res.json({ datos: await S.Inventario_editarProducto(P.productoId, B as Prisma.InventarioProductoUpdateInput & { categoriaId?: number | undefined }, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_estadoProducto(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroProducto, Req.params); const B = Inventario_validar(E.ObjEstadoProducto, Req.body); Res.json({ datos: await S.Inventario_cambiarEstado("producto", P.productoId, B.activo, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_gestionarProveedorProducto(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjGestionarProveedorProducto, Req.body); Res.json({ datos: await S.Inventario_gestionarProveedorProducto({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_listarProveedoresProductos(Req: Request, Res: Response) { const Q = Inventario_validar(E.ObjConsultaInventario, Req.query); Res.json(Inventario_paginacion(Q, await S.Inventario_listarProveedoresProductos({ IntPagina: Q.pagina, IntLimite: Q.limite, StrBusqueda: Q.busqueda, BoolActivo: Q.estado === undefined ? undefined : Q.estado === "ACTIVO" }))); }
export async function Inventario_listarExistencias(_Req: Request, Res: Response) { Res.json({ datos: await S.Inventario_listarExistencias() }); }
export async function Inventario_editarMinimo(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroExistencia, Req.params); const B = Inventario_validar(E.ObjEditarMinimo, Req.body); Res.json({ datos: await S.Inventario_editarMinimo(P.inventarioProductoId, B.existenciaMinima, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_listarLotes(Req: Request, Res: Response) { const Q = Inventario_validar(E.ObjConsultaLotes, Req.query); Res.json(Inventario_paginacion(Q, await S.Inventario_listarLotes({ IntPagina: Q.pagina, IntLimite: Q.limite, StrBusqueda: Q.busqueda, BoolActivo: Q.estado === undefined ? undefined : Q.estado === "ACTIVO", IntProductoId: Q.productoId, IntInventarioId: Q.inventarioId }))); }
export async function Inventario_editarLote(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroLote, Req.params); const B = Inventario_validar(E.ObjEditarLote, Req.body); Res.json({ datos: await S.Inventario_editarLote(P.loteInventarioId, B, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_estadoLote(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroLote, Req.params); const B = Inventario_validar(E.ObjEstadoLote, Req.body); Res.json({ datos: await S.Inventario_cambiarEstado("lote", P.loteInventarioId, B.activo, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_listarMovimientos(Req: Request, Res: Response) { const Q = Inventario_validar(E.ObjConsultaMovimientos, Req.query); Res.json(Inventario_paginacion(Q, await S.Inventario_listarMovimientos({ IntPagina: Q.pagina, IntLimite: Q.limite, IntProductoId: Q.productoId, IntInventarioId: Q.inventarioId, StrTipo: Q.tipo, StrSubtipo: Q.subtipo }))); }
export async function Inventario_entrada(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjCrearEntrada, Req.body); Res.status(201).json({ datos: await S.Inventario_registrarEntrada({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_salida(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjCrearSalida, Req.body); Res.status(201).json({ datos: await S.Inventario_registrarSalida({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_ajuste(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjCrearAjuste, Req.body); Res.status(201).json({ datos: await S.Inventario_registrarAjuste({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_transferencia(Req: Request, Res: Response) { const B = Inventario_validar(E.ObjCrearTransferencia, Req.body); Res.status(201).json({ datos: await S.Inventario_registrarTransferencia({ ...B, ...Inventario_actor(Req) }) }); }
export async function Inventario_revertir(Req: Request, Res: Response) { const P = Inventario_validar(E.ObjParametroTransaccion, Req.params); Res.status(201).json({ datos: await S.Inventario_revertirMovimiento(P.transaccionInventarioId, Inventario_actor(Req).IntUsuarioId, Req.ip) }); }
export async function Inventario_reconciliar(_Req: Request, Res: Response) { Res.json({ datos: await S.Inventario_diagnosticarReconciliacion() }); }
